heremaps/here-data-sdk-cpp

- olp-cpp-sdk-core/src/utils/Dir.cpp
When the SDK is built on Windows with _UNICODE definition defined paths were treated incorrectly.
Resolves: OLPEDGE-353
> Fix file system operations on Windows

- .gitignore
- .travis.yml
- olp-cpp-sdk-core/tests/cache/unittest/DefaultCacheTest.cpp
- scripts/linux_build.sh
- scripts/windows_build.sh
> Create initial Travis CI configuration

- CMakeLists.txt
- README.md
* Moved project on top to resolve the generator as early as possible
* Added information about the flag to the README
> Added option to enable multi threaded compilation on Windows

- .travis.yml
- examples/dataservice-read/example.cpp
- scripts/linux_build.sh
Travis CI setup without docker
Using xenial dist
Resolves: OLPEDGE-420
> Travis CI setup without docker

- .travis.yml
> This will setup Travis CI to use clang and gcc compilers.

- olp-cpp-sdk-core/include/olp/core/logging/Appender.h
- olp-cpp-sdk-core/include/olp/core/logging/Configuration.h
- olp-cpp-sdk-core/include/olp/core/logging/ConsoleAppender.h
- olp-cpp-sdk-core/include/olp/core/logging/DebugAppender.h
- olp-cpp-sdk-core/include/olp/core/logging/FileAppender.h
- olp-cpp-sdk-core/include/olp/core/logging/FilterGroup.h
- olp-cpp-sdk-core/include/olp/core/logging/MessageFormatter.h
- olp-cpp-sdk-core/src/logging/Configuration.cpp
- olp-cpp-sdk-core/src/logging/ConsoleAppender.cpp
- olp-cpp-sdk-core/src/logging/DebugAppender.cpp
- olp-cpp-sdk-core/src/logging/FileAppender.cpp
Return reference to itself instead of void in setters
Resolves: OLPEDGE-403
> Allow method chaining in logger classes

- azure-pipelines.yml
- scripts/windows/build.sh
Create inital Azure config file
Used only pull request for Azure pipelines trigger
Some syntax simplified in windows build script
Resolves: OLPEDGE-531
> Add build verification for Windows on Azure

- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
> CatalogRepository now logs all its major steps.

- olp-cpp-sdk-dataservice-read/src/repositories/ApiCacheRepository.cpp
> ApiCacheRepository now logs all its major steps.

- olp-cpp-sdk-dataservice-read/src/repositories/ApiRepository.cpp
> ApiRepository now logs all its major steps.

- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
> DataCacheRepository now logs all its major steps.

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
> PartitionsRepository now logs all its major steps.

- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
> DataRepository now logs all its major steps.

- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
> PrefetchTilesRepository now logs all its major steps.

- olp-cpp-sdk-dataservice-read/src/repositories/CatalogCacheRepository.cpp
> CatalogCacheRepository now logs all its major steps.

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
> ApiClientLookup class now logs all its major steps

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataRequest.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
DataRequest now provides CreatKey() method for its serialization
> DataRequest key generation optimization

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
- olp-cpp-sdk-dataservice-read/src/MultiRequestContext.h
- olp-cpp-sdk-dataservice-read/src/PrefetchTilesProvider.cpp
> PrefetchTilesProvider logging enhancement

- README.md
- azure-pipelines.yml
Add the Azure status badge and a nightly build schedule for the master branch.
> Azure badge

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/network2/Network.h
- olp-cpp-sdk-core/include/olp/core/network2/NetworkProxySettings.h
- olp-cpp-sdk-core/include/olp/core/network2/NetworkRequest.h
- olp-cpp-sdk-core/include/olp/core/network2/NetworkResponse.h
- olp-cpp-sdk-core/include/olp/core/network2/NetworkSettings.h
- olp-cpp-sdk-core/include/olp/core/network2/NetworkTypes.h
- olp-cpp-sdk-core/src/network2/Network.cpp
- olp-cpp-sdk-core/src/network2/NetworkProxySettings.cpp
- olp-cpp-sdk-core/src/network2/NetworkRequest.cpp
- olp-cpp-sdk-core/src/network2/NetworkResponse.cpp
- olp-cpp-sdk-core/src/network2/NetworkSettings.cpp
> Add new network inteface

- README.md
Fix coverage badge in README.md file.
Resolves: OLPEDGE-238
> Fix badges in README.md file.

- README.md
Relates-to: OLPEDGE-572
Signed-off-by: Leonid Ziskel <leonid.ziskel@here.com>
> Extend information about platforms, requirements and dependencies.

- docs/dataservice-read-catalog-example.md
- docs/dataservice-write-example.md
- examples/dataservice-read/example.cpp
- examples/dataservice-write/example.cpp
Example application sources now use prefix version
of logging macros.
> Logging prefix for examples

- README.md
Resolves: OLPDOC-46
Signed-off-by: Kateryna Nalezhyta <ext-kateryna.nalezhyta@here.com>
> Reviewed and edited README.md

- olp-cpp-sdk-core/cmake/curl.cmake
- olp-cpp-sdk-core/include/olp/core/utils/Dir.h
- olp-cpp-sdk-core/src/http/NetworkUtils.cpp
- olp-cpp-sdk-core/src/http/NetworkUtils.h
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
- olp-cpp-sdk-core/src/network/NetworkUtils.cpp
- olp-cpp-sdk-core/src/utils/Dir.cpp
> Port NetworkProtocolCurl to new network2::Network interface

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/cmake/winhttp.cmake
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.h
Changed NO_ERROR to SUCCESS, because it conflicts with define in windows.h
Nothing was changed.
Resolves: OLPEDGE-372
> Port windows network implementation to a new interface.

- examples/dataservice-read/CMakeLists.txt
- examples/dataservice-write/CMakeLists.txt
When the examples are built standalone, some packages are missing.
Resolves: OLPSUP-6783
> Added required packages to build standalone examples.

- scripts/ios/build.sh
Resolves: OLPEDGE-659
Signed-off-by: Andriy Zhernovskyi <ext-andriy.zhernovskyi@here.com>
> Add option to fail build script immediately on fail in any line

- olp-cpp-sdk-dataservice-write/test/unit/TestStreamLayerClient.cpp
Add initial call to publish so that URLs and metadata is filled
in cache and does not break expects during async call later.
Relates-to: OLPEDGE-667
> Make SDIIConcurrentPublishSameIngestApi test more stable.

- docs/GettingStartedGuide.md
Resolves: OLPEDGE-677
Signed-off-by: Leonid Ziskel <leonid.ziskel@here.com>
> Add a link to API reference

- examples/dataservice-read/example.cpp
- examples/dataservice-write/example.cpp
Adapted examples to the latest changes in the auth module.
Relates-To: OLPEDGE-543
> Adapted examples to the latest changes.

- .gitlab-ci.yml
- .travis.yml
- scripts/linux/fv/gitlab_build_fv.sh
- scripts/linux/psv/travis_build_psv.sh
Shared libs tuned ON. 
Linux libsegfault library added for segmentation fault crash identification in logs.
Resolves: OLPEDGE-383
>  OLPEDGE-383. Shared libs ON. Libsegfault lib added.

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
Added a mutex to protect http_requests_
Relates-To: OLPEDGE-544
> Added a mutex to protect http_requests_

- examples/dataservice-write/example.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestStreamLayerClient.cpp
This removed the raw std::thread usage and triggeres instead a task
to be executed in the context of the TaskScheduler. AutoFlushController
is the only class remaining that still uses raw std::thread but this
will need a big refactoring and will be postponed post v0.7.0 release.
Relates-to: OLPEDGE-457
> Adapts StreamLayerClient to use TaskScheduler for Flush context.

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationError.h
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-authentication/test/unit/ArcGisTestUtils.cpp
- olp-cpp-sdk-authentication/test/unit/ArcGisTestUtils.h
- olp-cpp-sdk-authentication/test/unit/AuthenticationProductionTests.cpp
- olp-cpp-sdk-authentication/test/unit/AuthenticationTests.cpp
- olp-cpp-sdk-authentication/test/unit/AuthenticationTests.h
- olp-cpp-sdk-authentication/test/unit/AuthenticationUtils.cpp
- olp-cpp-sdk-authentication/test/unit/AuthenticationUtils.h
- olp-cpp-sdk-authentication/test/unit/FacebookTestUtils.cpp
- olp-cpp-sdk-authentication/test/unit/FacebookTestUtils.h
- olp-cpp-sdk-authentication/test/unit/GoogleTestUtils.cpp
- olp-cpp-sdk-authentication/test/unit/GoogleTestUtils.h
- olp-cpp-sdk-authentication/test/unit/TestHereAccountOauth2IntegrationOnline.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestIndexLayerClient.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestVolatileLayerClient.cpp
ArcGis, Facebook, Google and Here utils for tests no longer try to use
outdated networking approach.
Relates-to: OLPEDGE-543
> Utils in test for socials fix

- scripts/linux/fv/gitlab-olp-cpp-sdk-core-network-test.sh
- scripts/linux/fv/gitlab_test_fv.sh
- scripts/linux/fv/olp-cpp-sdk-core-network-test.variables
* remove bash scripts
* remove variables list
Relates-to: OLPEDGE-585
> Remove FV  scripts for old network

- olp-cpp-sdk-dataservice-read/test/unit/src/CatalogClientTest.cpp
Adapt CatalogClient tests to the latest changes.
Relates-To: OLPEDGE-545
> Adapt CatalogClient tests.

- olp-cpp-sdk-dataservice-write/test/unit/TestStreamLayerClient.cpp
* fix disabled tests
* refactor cancellation tests
Relates-to: OLPEDGE-710
> Enable Stream Layer Client write tests

- olp-cpp-sdk-dataservice-write/test/unit/TestVolatileLayerClient.cpp
* fix disabled tests
* refactor cancellation tests
Relates-To: OLPEDGE-710
> Enable Volatile Layer Client write tests

- olp-cpp-sdk-core/include/olp/core/geo/projection/EarthConstants.h
Relates-to: OLPEDGE-731
Signed-off-by: Leonid Ziskel <leonid.ziskel@here.com>
> Fix doxygen warnings in EarthConstants

- scripts/linux/fv/gitlab-olp-cpp-sdk-authentication-test.sh
- scripts/linux/fv/gitlab-olp-dataservice-read-test.sh
- scripts/linux/fv/gitlab-olp-dataservice-write-test.sh
> Fix test names in FV CI scripts

- README.md
- docs/GettingStartedGuide.md
- docs/dataservice-read-catalog-example.md
- docs/dataservice-write-example.md
- examples/helpers/android/app/build.gradle.in
> Remove edge keyword from documentation.

- codecov.yml
Added codecov yaml to include tests directories from code coverage reports.
Resolves: OLPEDGE-744
> Added codecov yaml

- .travis.yml
- scripts/android/build.sh
- scripts/ios/build.sh
- scripts/macos/psv/travis_build_psv.sh
> Add ccache support to travis-ci builds

- olp-cpp-sdk-dataservice-read/src/MultiRequestContext.h
- olp-cpp-sdk-dataservice-read/src/repositories/ApiRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/ApiRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/tests/MultiRequestContextTest.cpp
MultiRequestContext template class now determines Callback on Response
parameter, rather an additional 2nd one.
Relates-to: OLPEDGE-678
> MultiRequestContext template optimization

- scripts/linux/fv/gitlab-olp-cpp-sdk-authentication-test.sh
- scripts/linux/fv/olp-cpp-sdk-authentication-test.variables
> Add env variables for authentication FV tests

- .travis.yml
- CMakeLists.txt
- scripts/linux/psv/travis_test_psv.sh
- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-core/NetworkTest.cpp
- testutils/mock_server/server.js
> Added a localhost server.

- scripts/linux/psv/travis_test_psv.sh
[skip ci] 
Relates-To: OLPEDGE-716
> Disable functional tests on PSV  [skip ci]

- CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/http/NetworkConstants.h
- olp-cpp-sdk-core/include/olp/core/logging/Log.h
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
- olp-cpp-sdk-core/src/thread/ThreadPoolTaskScheduler.cpp
> Renamed prefix of preprocessor definitions from EDGE_SDK to OLP_SDK

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
Added a header file for further VersionedLayerClient implementation
Relates-to: OLPEDGE-759
> VersionedLayerClient class skeleton

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
Updated doxygen documentation on VersionedLayerClient class skeleton.
Relates-to: OLPEDGE-759
> Cleaned up VersionedLayerClient class definition

- CONTRIBUTING.md
Review CONTRIBUTING.md for:
* consistency
* language quality
* compliance with HERE documentation standards and best practices of technical writing
Relates-to: OLPEDGE-622
Signed-off-by: Kateryna Osadchenko <ext-kateryna.osadchenko@here.com>
> Review CONTRIBUTING.md

- olp-cpp-sdk-dataservice-read/tests/CatalogClientTest.cpp
Remove online read tests from CatalogClientTest
> Remove online read tests from CatalogClientTest

- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-core/OlpClientDefaultAsyncHttpTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
Online parts of ApiTest & CatalogClientTest copied to functional tests
> Copy some read tests to tests/functional

- olp-cpp-sdk-dataservice-read/tests/CatalogClientTest.cpp
Fix variable and function names.
> Adapt codestyle in CatalogClientTest

- olp-cpp-sdk-dataservice-read/tests/CatalogClientTest.cpp
Use NetworkMock class and GenerateNetworkMockActions function
implementations from tests-common library instead of having your own.
> Use tests-common library in CatalogClientTest

- olp-cpp-sdk-dataservice-read/tests/MultiRequestContextTest.cpp
Align #includes. Rename variables and tests. Put tests into anonymous
namespace.
> Adopt codestyle in MultiRequestContextTest

- olp-cpp-sdk-dataservice-read/tests/ParserTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PendingRequestsTest.cpp
- olp-cpp-sdk-dataservice-read/tests/SerializerTest.cpp
Rename test and variable names. Put tests into anonymous namespace.
Relates-to:OLPEDGE-719
> Adopt codestyle in dataservice-read unit tests

- olp-cpp-sdk-dataservice-write/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/tests/StartBatchRequestTest.cpp
- olp-cpp-sdk-dataservice-write/tests/TestVersionedLayerClient.cpp
Move StartBatchRequestTest into separate file.
> Move StartBatchRequestTest into separate file

- olp-cpp-sdk-dataservice-write/tests/IndexLayerClientOnlineTest.cpp
- olp-cpp-sdk-dataservice-write/tests/IndexLayerClientTest.cpp
- olp-cpp-sdk-dataservice-write/tests/StartBatchRequestTest.cpp
- olp-cpp-sdk-dataservice-write/tests/TestCancellationTokenList.cpp
- olp-cpp-sdk-dataservice-write/tests/TestParser.cpp
- olp-cpp-sdk-dataservice-write/tests/TestSerializer.cpp
- olp-cpp-sdk-dataservice-write/tests/TestThreadSafeQueue.cpp
- olp-cpp-sdk-dataservice-write/tests/TestTimeUtils.cpp
- olp-cpp-sdk-dataservice-write/tests/VolatileLayerClientOnlineTest.cpp
Put tests into anonymous namespace, rename tests and variables.
Reorder #includes.
> Adopt codestyle in some dataservice-write tests

- olp-cpp-sdk-dataservice-write/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/tests/VersionedLayerClientOnlineTest.cpp
Rename source file and test. Put code into anonymous namespace. Rename
variables. Remove dead code.
> Adopt code style in VersionedLayerClientOnlineTest

- olp-cpp-sdk-dataservice-write/tests/ParserTest.cpp
> Adopt codestyle in ParserTest

- olp-cpp-sdk-dataservice-read/tests/ApiClientLookupTest.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- tests/common/mocks/NetworkMock.cpp
- tests/common/mocks/NetworkMock.h
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTestBase.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/IndexLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/VolatileLayerClientTest.cpp
This reverts commit 32f6dff2c153a0d61087f54e2146d2b5024c610f.
> Revert "Make ReturnHttpResponse action a free function"

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
Disabled failing FacebookAuthenticationTest.SignInFacebook on Gitlab FV stage.
Relates to: OLPEDGE-864
> Disabled FacebookAuthenticationTest on FV

- examples/dataservice-read/CMakeLists.txt
- examples/dataservice-write/CMakeLists.txt
- scripts/linux/psv/travis_build_psv.sh
> Fix examples compilation on psv.

- olp-cpp-sdk-dataservice-read/tests/PendingRequestsTest.cpp
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.h
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
Fixed typo CancellAll -> CancelAll.
Relates-To: OLPEDGE-880
> Fixed typo.

- olp-cpp-sdk-core/include/olp/core/porting/deprecated.h
Added a macro to deprecate classes/functions.
Resolves: OLPEDGE-877
> Added a DEPRECATED macro

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientTest.cpp
Added Tests for VolatileLayerClientImpl class
Resolves: OLPEDGE-760
> Implemented VolatileLayerClient::GetData() method

- olp-cpp-sdk-dataservice-read/src/TaskContext.h
- olp-cpp-sdk-dataservice-read/tests/TaskContextTest.cpp
Introduce sequence of operations in test on Condition instead of sleep.
Relates-To: OLPEDGE-909
> Reduce flakiness in TaskContext tests

- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteIndexLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientCacheTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
- tests/functional/utils/Utils.h
Adapt dataservice-write functional tests
Resolves: OLPEDGE-966
> Add a test macro.

- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
> Fix typo in dataservice read volatile test

- tests/functional/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/functional/utils/Utils.h
> Adapt dataservice-read functional tests for EXCPECT_SUCCESS macro

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
> Move Types to the separate header.

- external/boost/CMakeLists.txt.boost.in
Download link from https://www.boost.org/users/download/
Relates-To: OLPEDGE-959
> Fix boost download error

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVolatileLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
> Adapt Version and Volatile layers to use Types.h

- tests/functional/olp-cpp-sdk-authentication/HereAccountOauth2ProductionTest.cpp
The test expects that the total time taken to run 5 threads (each thread runs a
auth request) is less than the total time spent in the thread during running
the requests.
Theoretically could happen the following:
5 requests complete with the following duration:
1ms 1ms 2ms 3ms 15ms
Total time: 15ms
Total time for 5 requests: 22ms
2 * 15ms is not less than 22ms
Resolves: OLPEDGE-843
> Fix the flaky test RequestTokenConcurrent

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- add additional info about versions
- add usage example
- add info about saving request when version is provided
Resolves: OLPEDGE-854
> Improve Doxygen for VersionedLayerClient

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
> Fix Doxygen example for VolatileLayerClient

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/src/CatalogClient.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
> Adapt CancelPendingRequests method name to common style.

- CHANGELOG.md
> Update a CHANGELOG.md for v0.8.0-beta

- CHANGELOG.md
- docs/dataservice-read-catalog-example.md
- examples/dataservice-read/example.cpp
> Update the read example and documentation to reflect the latest changes.

- olp-cpp-sdk-authentication/src/AutoRefreshingToken.cpp
- Most of the parameters changed to match coding style.
- Added logs to see token request outcome and expiration time.
Relates-to: OLPEDGE-1012
> Adapts AutoRefreshingToken class to coding style.

- scripts/linux/fv/olp-cpp-sdk-functional-test.variables
> Change test catalog realm.

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- tests/integration/olp-cpp-sdk-dataservice-read/HttpResponses.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Implemented GetPartitions sync method in PartitionsRepository
Refactored VersionedLayerClient to use sync GetPartitions method
Resolves: OLPEDGE-1003
> Implemented Sync method for GetPartitions

- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
Added the explicit registering of native methods via registerNatives() JNI method. This will fix the problem when using the SDK when embedding Java VM inside native application.
Relates to: OLPEDGE-973
Signed-off-by: Miika Jan Jarvinen <miika-jan.jarvinen@here.com>
> Explicitly registered the native methods via registerNatives method

- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/Common.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
> Move handling of FetchOptions to the Common.h

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
Resolves: OLPEDGE-1043
Signed-off-by: Serhii Lozynskyi ext-serhii.lozynskyi@here.com
> Fixed Sonar Error in NetworkWinHttp.cpp

- tests/performance/CatalogClientTest.cpp
Change CatalogClient to VersionedLayerClient in performance test. Adapt
client construction.
Relates-To: OLPEDGE-1015
> Remove usage of deprecated API in performance tests

- scripts/android/build.sh
- scripts/ios/build.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-authentication-test.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-core-test.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-dataservice-read-test.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-dataservice-write-test.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-integration-test.sh
- scripts/linux/fv/gitlab_build_fv.sh
- scripts/linux/fv/gitlab_test_fv.sh
- scripts/linux/nv/gitlab_build_valgrind.sh
- scripts/linux/nv/gitlab_cppcheck_and_upload_sonar.sh
- scripts/linux/nv/gitlab_test_valgrind.sh
- scripts/linux/psv/travis_build_psv.sh
- scripts/linux/psv/travis_test_psv.sh
- scripts/macos/psv/travis_build_psv.sh
Small refactor of comments added to align style.
Resolves: OLPEDGE-1048
> Add copyright on top of all bash scripts

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogVersionRequest.h
> Removed const from CatalogVersionRequest::WithStartVersion() return value

- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
Copy integration tests from CatalogClient to VolatileLayerClient that
are relevant and use deprecated API.
Relates-To: OLPEDGE-984
> Add integration tests for VolatileLayerClient

- .travis.yml
- azure-pipelines.yml
- scripts/ios/azure_ios_build_psv.sh
- scripts/macos/psv/azure_macos_build_psv.sh
> Move OSX/IOS builds from Travis to Azure

- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Copy integration tests from CatalogClient to VersionedLayerClient that
are relevant and use deprecated API.
Relates-To: OLPEDGE-984
> Add integration tests for VersionedLayerClient

- README.md
- scripts/windows/build.sh
Add -DOLP_SDK_ENABLE_TESTING=NO for Windows.
Relates-To: OLPEDGE-1064
> Update README.md according to partial migration to Azure

- tests/performance/CMakeLists.txt
- tests/performance/MemoryTest.cpp
- tests/performance/NullCache.h
* Test with null cache
* Test with in memory cache
* Test with both in memory and disk cache
Relates-To: OLPEDGE-1052
> Add 3 test suite to test SDK memory

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
> Fix incorrect proxy host name

- tests/performance/MemoryTest.cpp
> Fix proxy settings in performance tests.

- scripts/linux/nv/gitlab_test_performance.sh
> Add a script to run performance tests

- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.h
- olp-cpp-sdk-dataservice-read/src/Common.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/ExecuteOrSchedule.inl
Remove CatalogClientImpl::AsFuture, align with layer clients.
Relates-To: OLPEDGE-1109
> Add AddTask method to remove duplicate code

- docs/OverallArchitecture.md
Changed the "Implemented" status to "Planned" for the following 2 items:
* Reading from stream layer
* Reading from indexed layer
Resolves: OLPEDGE-1112
> Corrected 2 errors in OverallArchitecture.md

- tests/utils/olp_server/query_service.js
> Add query quad tree API to a mocked OLP server

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/PlatformApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/PlatformApi.h
- olp-cpp-sdk-dataservice-read/src/generated/api/ResourcesApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/ResourcesApi.h
> Fix client capturing in ApiClientLookup

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Improved logging in NetworkCurl implementation by adding request ids, this pointer and url when do logging.
Relates to: OLPEDGE-1051
> Improved logging for NetworkCurl

- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.mm
- olp-cpp-sdk-core/src/http/ios/OLPHttpTask.mm
- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
Improved logging of iOS network (OLPHttpClient / OLPHttpTask / OLPNetworkIOS) by adding the URL into logs.
Relates to: OLPEDGE-1051
> Improved logging for iOS network by adding URL to logs

- docs/dataservice-read-catalog-example.md
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
Modified the following files with notes to the `GetPartitions` method:
* VersionedLayerClient.h
* VolatileLayerClient.h
* dataservice-read-catalog-example.md
Relates-to: OLPEDGE-812
> Added notes to the `GetPartitions` method

- olp-cpp-sdk-core/src/http/android/HttpClient.java
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
Improved NetworkAndroid logs by adding requests ids and this pointer.
Relates to: OLPEDGE-1051
> Improved logs for NetworkAndroid and HttpClient

- tests/performance/MemoryTest.cpp
> Refactor MemoryTest, add a test case for Prefetch

- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.inl
- olp-cpp-sdk-core/include/olp/core/client/CancellationToken.h
- olp-cpp-sdk-core/src/client/CancellationToken.cpp
- olp-cpp-sdk-core/src/client/PendingRequests.cpp
- olp-cpp-sdk-core/tests/client/TaskContextTest.cpp
- olp-cpp-sdk-core/tests/olpclient/OlpClientTest.cpp
- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/Common.h
- olp-cpp-sdk-dataservice-read/src/MultiRequestContext.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/MultiRequestContextTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- olp-cpp-sdk-dataservice-write/src/AutoFlushController.cpp
- olp-cpp-sdk-dataservice-write/src/CancellationTokenList.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationCommonTestFixture.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteIndexLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientCacheTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/IndexLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/VolatileLayerClientTest.cpp
> Align CancellationToken to google style

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
1. Improved logs in NetworkWinHttp class by adding the request_id to the corresponding logs and logging this pointer when destructing / constructing the Network object.
2. Also, added error-handling logs for corresponding WinHttp functions;
3. Removed unneeded lock when handling WinHttpOpenRequest failure;
Relates to:  OLPEDGE-1051
> Improved logs in NetworkWinHttp class

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
- scripts/linux/nv/gitlab_test_valgrind.sh
> Add retry to FV and NV online tests

- tests/performance/MemoryTest.cpp
Add logic to count callback invocations and compare it with number of
API calls.
Relates-To: OLPEDGE-1115
> Add callback count check for performance test

- olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
> Release resources in TaskContext before notifying user.

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
When task is schedulled and cancelled before execution,
no function executed and callback is called. Add callback
for covering such cases.
Relates-To: OLPEDGE-1005
> Add callback for outer-task in Prefetch

- tests/performance/MemoryTest.cpp
> Add guard for nullptr Cache Factory

- tests/performance/MemoryTest.cpp
- tests/performance/NetworkWrapper.h
Adds performance testing for CatalogClient::GetLatestVersion() and
CatalogClient::GetCatalog().
Relates-to: OLPEDGE-1151
> Adds performance test for CatalogClient.

- tests/performance/MemoryTest.cpp
- tests/performance/NetworkWrapper.h
Make a new network for every test run.
Relates-To: OLPEDGE-1156
> Added a random cancellation configuration for performance tests

- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
Relates-To: OLPEDGE-708
This reverts commit ee0f18e.
> Revert "Refactored assertion about GetBatch successful response in tests"

- olp-cpp-sdk-authentication/include/olp/authentication/ErrorResponse.h
- olp-cpp-sdk-authentication/src/BaseResult.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
> Propagate error_id to user.

- olp-cpp-sdk-core/include/olp/core/client/CancellationToken.h
- olp-cpp-sdk-core/src/client/CancellationToken.cpp
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/src/CatalogClient.cpp
> Remove deprecated methods.

- README.md
Add Embedded linux as supported target with dependencies on cross
compilers.
Relates-To: OLPSUP-8752
> Update list of supported platforms

- codecov.yml
> Exclude network implementation files from codecov

- .gitlab-ci.yml
- scripts/linux-armhf/fv/gitlab_build_armhf_fv.sh
Add build script. Update gitlab FV pipeline yml.
Relates-To: OLPEDGE-1187
> Add armhf linux build to FV

- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/generated/IngestApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/IngestApi.h
- olp-cpp-sdk-dataservice-write/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/tests/StreamLayerClientImplTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientTest.cpp
Introduce sync wrapper. Now IngestSDII schedules fetch task. For testing
purposes call to api performed through virtual method.
Relates-To: OLPEDGE-1180
Signed-off-by: Diachenko Mykhailo <ext-mykhailo.z.diachenko@here.com>
> Change IngestSDII of StreamLayer to use sync api.

- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/http/NetworkTypes.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/src/http/NetworkTypes.cpp
> Move the common function ErrorCodeToString to NetworkTypes.h

- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
According to the AAA team, we should expect one of 401 or 404 status.
Resolves: OLPEDGE-799
> Fix flaky SignUpInUser, SignInRefresh tests.

- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
> Switch MetadataApi and it's usage to new sync CallApi

- scripts/linux/fv/gitlab_test_fv.sh
Also add more informative echo messages.Remove redundant error files generation and printing.
Change order of FV tests for correct exitcode in FV pipeline.
Relates-To: OLPEDGE-1245
> Fix counter and exitcode in retry bash logic

- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/logging/MessageFormatterTest.cpp
Signed-off-by: Kirill Zhuchkov <643378+r0busta@users.noreply.github.com>
> Add unit tests for the MessageFormatter class

- README.md
Added the a _blank attribute to the external links.
Relates-to: OLPEDGE-1275
> Modified all the external links

- olp-cpp-sdk-core/src/client/HRN.cpp
- olp-cpp-sdk-core/src/client/Tokenizer.h
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/client/HRNTest.cpp
Add unit tests for HRN class
Adapt Tokenizer to google coding style
Remove unused functionality from Tokenizer
Remove handling of http and https protocol.
Relates-To: OLPEDGE-1201
> Review HRN::IsNull function

- olp-cpp-sdk-core/include/olp/core/http/NetworkUtils.h
- olp-cpp-sdk-core/src/http/NetworkUtils.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/http/NetworkUtils.cpp
NetworkUtils was moved to include/olp/core/http
Relates-To: OLPEDGE-1214
> Create unit tests for NetworkUtils.

- docs/GettingStartedGuide.md
- docs/dataservice-read-catalog-example.md
Modified and aligned the content of the following two files with
the Developer's Guide:
- GettingStartedGuide.md
- dataservice-read-catalog-example.md
Relates-to: OLPEDGE-1146
> Modify content (Read Example+Getting Started)

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationCredentials.h
- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationError.h
- olp-cpp-sdk-authentication/include/olp/authentication/AutoRefreshingToken.h
- olp-cpp-sdk-authentication/include/olp/authentication/ErrorResponse.h
- olp-cpp-sdk-authentication/include/olp/authentication/Settings.h
- olp-cpp-sdk-authentication/include/olp/authentication/SignInResult.h
- olp-cpp-sdk-authentication/include/olp/authentication/SignInUserResult.h
- olp-cpp-sdk-authentication/include/olp/authentication/SignOutResult.h
- olp-cpp-sdk-authentication/include/olp/authentication/SignUpResult.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenEndpoint.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenRequest.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenResult.h
Reviewed and modified the existing comments, added the missing comments.
Relates-to: OLPEDGE-859
> Review the Authentication API for comments

- olp-cpp-sdk-core/CMakeLists.txt
> Partially remove GLOB usage in olp-cpp-sdk-core.

- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
1. Removed unused async versions of publish methods from StreamLayerClientImpl and their helper methods:
- InitApiClients;
- InitApiClientsGreaterThanTwentyMib;
- InitCatalogModel;
- FindContentTypeForLayerId;
- PublishDataOld;
- PublishDataLessThanTwentyMib;
- InitPublishDataGreaterThanTwentyMib;
- PublishDataGreaterThanTwentyMib;
2. Removed initialization synchronization primitives from StreamLayerClientImpl.
3. Removed unneeded includes
Relates-to: OLPEDGE-1185
> Removed unused publish methods from StreamLayerClientImpl

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
Relates-To: OLPEDGE-1339
Signed-off-by: Kirill Zhuchkov <643378+r0busta@users.noreply.github.com>
> Fix broken links to the dev doc articles

- olp-cpp-sdk-authentication/include/olp/authentication/TokenEndpoint.h
> Mark TokenEndpoint class as deprecated.

- olp-cpp-sdk-core/src/http/android/HttpClient.java
- Provide consistency between Android and iOS error handling:
In iOS, offline error code is already correctly translated; For Android, the most similar error given in such situation is java.net.UnknownHostException.
Relates-To: IOTSDK-3924
Signed-off-by: Thiago F. Alencar <thiago.fariaalencar@here.com>
> Improve android HttpClient error handling

- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
Relates-to: OLPEDGE-731
Signed-off-by: Leonid Ziskel <leonid.ziskel@here.com>
> Improve caching documentation

- olp-cpp-sdk-core/tests/logging/ConfigurationTest.cpp
- olp-cpp-sdk-core/tests/logging/MessageFormatterTest.cpp
- olp-cpp-sdk-core/tests/logging/MockAppender.h
**Separate system and library includes**
> Separate system and library includes

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataRequest.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
> Fix the doxygen for DataRequest, added preconditions for GetData method

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogVersionRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/FetchOptions.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTileResult.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/VersionResponse.h
Reviewed and modified comments in the following files:
* CatalogRequest.h
* CatalogVersionRequest.h
* FetchOptions.h
* PartitionsRequest.h
* PrefetchTileResult.h
* PrefetchTilesRequest.h
* VersionedLayerClient.h
* VolatileLayerClient.h
* VersionResponse.h
Relates-to: OLPEDGE-856
> Modify comments in 9 files (dataservice-read)

- docs/GettingStartedGuide.md
> Fix broken link in GettingStartedGuide.md

- scripts/linux/nv/gitlab_test_performance.sh
Archives .gz should be used from job artifacts for heaptrack_gui
Relates-to: OLPEDGE-1269
> Add new tests to performance NV script

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogVersionRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
> Review and modify documentation (dataservice-read)

- .travis.yml
- azure-pipelines.yml
- scripts/android/build.sh
Build time should be lower than on Travis.
Also it will decrease number of runners in Travis.
Resolves: OLPEDGE-1074
> Migrate Android PSV/SV build. Travis > Azure

- CMakeLists.txt
- external/leveldb/CMakeLists.txt
> Fix build. Set CMAKE_POSITION_INDEPENDENT_CODE=ON.

- README.md
Add readme note with status URL.
Resolves: OLPEDGE-1074
> Documenting migration Android PSV/SV build. Travis > Azure

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/Catalog.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/Data.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/Partitions.h
Reviewed and added documentation for classes and methods.
Relates-to: OLPEDGE-856
> Modify and add comments(dataservice-read)

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/Messages.h
- olp-cpp-sdk-dataservice-read/src/generated/parser/MessagesParser.cpp
- olp-cpp-sdk-dataservice-read/src/generated/parser/MessagesParser.h
This class represents messages read from a stream layer.
Relates-To: OLPEDGE-1371
> Add Messages model for Stream API

- external/rapidjson/CMakeLists.txt.rapidjson.in
> Disable export package for rapidjson

- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientCacheTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientTest.cpp
> Remove static network and static task scheduler from Stream tests.

- olp-cpp-sdk-dataservice-read/tests/StreamLayerClientImplTest.cpp
> Add unit tests for StreamLayerClientImpl::GetData method

- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-dataservice-read/HttpResponses.h
- tests/integration/olp-cpp-sdk-dataservice-read/StreamLayerClientTest.cpp
> Add integration tests for StreamLayerClient Subscribe

- tests/integration/olp-cpp-sdk-dataservice-read/HttpResponses.h
- tests/integration/olp-cpp-sdk-dataservice-read/StreamLayerClientTest.cpp
> Add integration tests for StreamLayerClient Unsubscribe

- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/StreamApiTest.cpp
> Add integration tests for StreamApi::Subscribe method

- olp-cpp-sdk-dataservice-read/src/repositories/CatalogCacheRepository.cpp
> Expire catalog version after 5 minutes.

- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
* Fix functional tests.
Resolves: OLPEDGE-1494
> Fix error codes returned from GetTimeFromServer()

- olp-cpp-sdk-dataservice-read/tests/StreamApiTest.cpp
> Add intergation tests for StreamApi::DeleteSubscription method

- olp-cpp-sdk-dataservice-read/tests/StreamApiTest.cpp
> Add intergation tests for StreamApi::CommitOffsets method

- olp-cpp-sdk-core/include/olp/core/client/ApiError.h
- olp-cpp-sdk-core/include/olp/core/client/ApiNoResult.h
- olp-cpp-sdk-core/include/olp/core/client/ApiResponse.h
- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.h
- olp-cpp-sdk-core/include/olp/core/client/CancellationToken.h
- olp-cpp-sdk-core/include/olp/core/client/Condition.h
- olp-cpp-sdk-core/include/olp/core/client/ErrorCode.h
- olp-cpp-sdk-core/include/olp/core/client/HRN.h
- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClient.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientFactory.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
- olp-cpp-sdk-core/include/olp/core/client/PendingRequests.h
- olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
> Modify documentation (olp-cpp-sdk-core/client)

- olp-cpp-sdk-dataservice-read/tests/StreamApiTest.cpp
> Add intergation tests for StreamApi::SeekToOffset method

- olp-cpp-sdk-dataservice-read/tests/StreamApiTest.cpp
> Add intergation tests for StreamApi::ConsumeData method

- olp-cpp-sdk-core/include/olp/core/context/Context.h
> Modify documentation in core/include/context

- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/include/olp/core/cache/KeyValueCache.h
> Modify documentation (core/include/cache)

- examples/CMakeLists.txt
- examples/Options.h
- examples/main.cpp
> Fix windows build for examples

- olp-cpp-sdk-authentication/include/olp/authentication/TokenEndpoint.h
> Fix a typo in TokenEndpoint class

- olp-cpp-sdk-core/src/client/HRN.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/StreamLayerClientImplTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- olp-cpp-sdk-dataservice-write/tests/ApiClientLookupTest.cpp
- olp-cpp-sdk-dataservice-write/tests/StreamLayerClientImplTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
**Fix the case of the constant variable**
Relates-To: OAM-202
> Fix the case of the constant variable

- olp-cpp-sdk-core/include/olp/core/generated/serializer/SerializerWrapper.h
> Reduce data copy in SerializerWrapper

- olp-cpp-sdk-core/src/client/HRN.cpp
- olp-cpp-sdk-core/src/client/OlpClient.cpp
Fix the OlpClient log tag.
Resolves: OLPEDGE-1551
> Fix the issue with static HRN initialization

- README.md
> Update the License section

- olp-cpp-sdk-dataservice-read/tests/StreamApiTest.cpp
- olp-cpp-sdk-dataservice-read/tests/StreamLayerClientImplTest.cpp
- tests/common/matchers/NetworkUrlMatchers.h
> Add unit tests for StreamLayerClient::Poll method

- olp-cpp-sdk-core/include/olp/core/client/BackdownStrategy.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
> Modify documentation related to backdown strategy

- olp-cpp-sdk-authentication/include/olp/authentication/SignInResult.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenResult.h
> Review documentation for `GetExpiresIn`

- olp-cpp-sdk-core/include/olp/core/client/BackdownStrategy.h
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
- olp-cpp-sdk-dataservice-write/tests/ApiClientLookupTest.cpp
> Fix various warnings (MSVC)

- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
> Make destructor virtual.

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
> Fix signed/unsigned comparison warnings in NetworkCurl

- olp-cpp-sdk-authentication/src/AuthenticationCredentials.cpp
> Fix warning with parentheses

- olp-cpp-sdk-core/src/http/NetworkUtils.cpp
> Fix checking for size and offset in NetworkUtils

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogVersionRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/TileRequest.h
TileRequest will be used for GetData with TileKey.
Resolves: OLPEDGE-1528
> Add TileRequest class.

- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkRequest.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkTypes.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/src/http/NetworkRequest.cpp
Add headers to http responce. 
Resolves: OLPEDGE-1348
> Modify CallApi to return HTTP headers.

- tests/utils/olp_server/server.js
> Boost test server performance.

- olp-cpp-sdk-authentication/src/SignInResultImpl.cpp
> Fix uninitalized variable usage

- olp-cpp-sdk-core/include/olp/core/thread/Atomic.h
- olp-cpp-sdk-core/include/olp/core/thread/SyncQueue.h
- olp-cpp-sdk-core/include/olp/core/thread/TaskScheduler.h
- olp-cpp-sdk-core/include/olp/core/thread/ThreadPoolTaskScheduler.h
Review and modify public documentation for `thread` and test its build
in Doxygen.
Relates-to: OLPEDGE-1449
> Modify public documentation in core/include/thread

- CONTRIBUTING.md
Review CONTRIBUTING.md for typos, mistakes, and correspondence to
tech writing principles.
Relates-to: OLPEDGE-1369
> Correct grammar and punctuation in CONTRIBUTING.md

- README.md
> Update the required OpenSSL version to latest LTS in README

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
Needed for a new feature to request metadata for specified partitions.
Resolves: OLPEDGE-1016
> Add WithPartitions/GetPartitions to PartitionsRequest

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
Append 'partition' and 'partitions' for key values.
Relates-To: OLPEDGE-1568
> Fix Cache keys.

- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
Get QuadTreeIndex for requested tile with debth equal 4, convert to partitions.
Put partitions to cache. Get blob data using data handle for requested tile key. Return data to user.
Relates-To: OLPEDGE-1529
> Add implementation for get data using tile key.

- olp-cpp-sdk-core/src/client/OlpClient.cpp
Fix of thread concurrency problem in OlpClient
which in some situations resulted in crash
Resolves: OLPEDGE-1594
> Fix crash in OlpClient

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
> Fix the regression with the empty list of partitions

- olp-cpp-sdk-authentication/include/olp/authentication/IntrospectAppResult.h
This is a part of exposing introspect app API. IntrospectAppResult is
created to parse and store result of introspect request. It contains
application info like name, description, realm etc.
Resolves: OLPEDGE-1489
> Expose introspect app API. IntrospectAppResult part.

- CMakeLists.txt
- examples/CMakeLists.txt
- examples/android/app/CMakeLists.txt.in
- examples/ios/CMakeLists.txt.in
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
> Update the package version to 1.3.0

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
The commit caused a regression, the crash itself is a very exotic case.
Crash is added to the known issues.
Relates-To: OLPEDGE-1687
This reverts commit 4cdd52d.
> Revert "Fix a crash in the NetworkCurl"

- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
> Remove deprecated disk_path

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationProductionTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
> Remove deprecated SignInClient method.

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Functions Run, CompleteMessage, Initialize, Deinitialize are changed.
LostHandles functionality removed from Run function.
Relates-To:OLPEDGE-1694
> Change NetworkCurl according to os_adapation::NetworkProtocolCurl.

- tests/utils/mock-server-client/Client.h
**Add method that removes an expectation by a path-method matcher.**
The method is essential for cleaning expectations on the fly so that
the mock server doesn't eat up all available RAM.
Relates-To: OAM-188
> Add method that removes an expectation by a path-method matcher.

- olp-cpp-sdk-core/include/olp/core/http/Network.h
> Fix a warning about unused parameter.

- scripts/misc/commit_checker.sh
It would help to resolve failures on CI easier.
Relates-To: OLPEDGE-1753
> Add debug to Commit checker script

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.h
Move the DefaultCache implementation to DefaultCacheImpl class
Resolves: OLPEDGE-1587
> Move the DefaultCache implementation to Impl

- examples/CMakeLists.txt
- examples/Options.h
- examples/StreamLayerReadExample.cpp
- examples/StreamLayerReadExample.h
- examples/main.cpp
Create stream layer client with user specified catalog, layer id and credentials.
Try to poll data till all messages are consumed.
Check received messages from a stream layer. If received data is more than 1mb and data handle is returned, call GetData for each received message.
Relates_to:OLPEDGE-1306
> Add stream layer read example.

- docs/dataservice-read-from-stream-layer-example.md
Add documentation that describes how to subscribe to a stream layer,
get data from it, and unsubscribe.
Relates-To: OLPEDGE-1726
> Document how to read data from a stream layer

- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
On Creating Default cache through OlpClientSettingsFactory
there was not check for failure on opening DiskCache. Now in case of
error proper log message is printed.
Resolves: OLPSUP-9914
> Add log in case DiskCache open failed

- examples/StreamLayerReadExample.cpp
Add logs on subscription/unsubscription/start example.
Resolves: OLPEDGE-1743
> Fix logging for stream layer read example.

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
Expose leveldb iterator and write batch functionality.
Resolves: OLPEDGE-1589
> Expose leveldb functionality

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.h
Removed unused methods and members
Move the pointer to network instance from ConnectionData to RequestData
Relates-To: OLPEDGE-1760
> Cleanup NetworkWinHttp class

- olp-cpp-sdk-core/include/olp/core/http/NetworkResponse.h
- olp-cpp-sdk-core/src/http/NetworkResponse.cpp
Add the information about number of bytes downloaded/uploaded.
Relates-To: OLPEDGE-1761
> Add additional fields to NetworkResponse

- README.md
Add a section with information on backward compatibility.
Relates-To: OLPEDGE-1732
> Add information on backward compatibility

- olp-cpp-sdk-core/src/http/android/HttpClient.java
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.h
Calculate headers and payload for uploaded
and downloaded data.
Relates-To:OLPEDGE-1758
> Measurement of uploaded/downloaded data Android.

- olp-cpp-sdk-core/src/http/ios/OLPHttpTask.h
- olp-cpp-sdk-core/src/http/ios/OLPHttpTask.mm
- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
Add network download/upload statistics collection
for IOS platform.
Resolves: OLPEDGE-1757
> Add network stats to IOS

- scripts/misc/commit_checker.sh
- scripts/misc/commit_message_recom.txt
Minor fixes to comments and removed checks for branch
as job runs on PullRequests only.
Related-To: OLPEDGE-1573
> Minor fixes to commit checker job

- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
> Improve logging for PrefetchTilesRepository.

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
As was found during profiling, prefetch spawn too many tasks, and
settings are copied to every spawned task, as a result, there is
520 bytes overhead for each task, using a shared pointer to settings
we save this memory.
Relates-To: OLPEDGE-1804
> Use shared_ptr to settings for prefetch tasks

- olp-cpp-sdk-core/include/olp/core/geo/tiling/HalfQuadTreeSubdivisionScheme.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/ISubdivisionScheme.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/ITilingScheme.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/QuadTreeSubdivisionScheme.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/SubTiles.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/TileKey.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/TileKeyUtils.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/TileTreeTraverse.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/TilingScheme.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/TilingSchemeRegistry.h
- olp-cpp-sdk-core/src/geo/tiling/HalfQuadTreeSubdivisionScheme.cpp
- olp-cpp-sdk-core/src/geo/tiling/QuadTreeSubdivisionScheme.cpp
- olp-cpp-sdk-core/src/geo/tiling/TileKey.cpp
- olp-cpp-sdk-core/src/geo/tiling/TileKeyUtils.cpp
- olp-cpp-sdk-core/src/geo/tiling/TileTreeTraverse.cpp
This commit adapts all core/geo/tiling classes to coding style.
Relates-To: OLPEDGE-569
> Adapts core/geo/tiling classes to coding style.

- tests/performance/CMakeLists.txt
- tests/performance/MemoryTest.cpp
- tests/performance/MemoryTestBase.h
Extract a MemoryTestBase class.
Remove not used tests to catalog client.
Relates-To: OLPEDGE-1804
> Refactor Performance tests.

- scripts/linux/fv/olp-cpp-sdk-functional-test.variables
Changed Versioned Layer version to 120
Resolves: OLPEDGE-1792
> Fix FV Job

- .travis.yml
- scripts/misc/cpplint_ci.sh
Add cpplint tool to check the affected source files on CI.
Relates-To: OLPEDGE-1844
> Add cpplint tool and script

- olp-cpp-sdk-core/include/olp/core/http/HttpStatusCode.h
- olp-cpp-sdk-core/include/olp/core/http/Network.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkConstants.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkProxySettings.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkRequest.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkResponse.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkSettings.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkTypes.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkUtils.h
Reviewed and modified the API documentation for HTTP, added
missing documentation.
Relates-To: OLPEDGE-1445
> Modified API documentation for HTTP

- tests/performance/CMakeLists.txt
- tests/performance/MemoryTestBase.h
- tests/performance/PrefetchTest.cpp
Modify disk cache setup function to generate unique folder for each
test run.
Relates-To: OLPEDGE-1804
> Add prefetch memory tests.

- README.md
Add information on ABI compatibility.
Relates-To: OLPEDGE-1865
> Update the Backward Compatibility section

- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
- scripts/linux/fv/gitlab-olp-cpp-sdk-core-test.sh
- scripts/linux/nv/gitlab_test_valgrind.sh
Remove tests and filters.
Relates-To: OLPEDGE-419
> Remove DefaultCacheTest.BadPathMutable and BadPathProtected

- olp-cpp-sdk-core/include/olp/core/utils/Base64.h
- olp-cpp-sdk-core/include/olp/core/utils/Dir.h
- olp-cpp-sdk-core/include/olp/core/utils/Url.h
- olp-cpp-sdk-core/src/utils/Base64.cpp
- olp-cpp-sdk-core/src/utils/Dir.cpp
- olp-cpp-sdk-core/src/utils/Url.cpp
All core/utils classes are now adapted to our coding style, except
some Windows specific code from Dir.cpp.
Relates-To: OLPEDGE-1854
> Adapt core/utils classes to coding style.

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Update version in CMake.
Relates-To: OLPEDGE-1824
> Added changelog for 1.6.0 version

- olp-cpp-sdk-dataservice-read/src/generated/api/PlatformApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/PlatformApi.h
- olp-cpp-sdk-dataservice-read/src/generated/api/ResourcesApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/ResourcesApi.h
- olp-cpp-sdk-dataservice-read/tests/ApiClientLookupTest.cpp
Modify defines in lookup unit test.
Relates-To: OLPEDGE-1393
> Remove GetApi unused functions.

- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/include/olp/core/client/ApiError.h
- olp-cpp-sdk-core/include/olp/core/client/ApiResponse.h
- olp-cpp-sdk-core/include/olp/core/client/CancellationToken.h
- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
- olp-cpp-sdk-core/include/olp/core/generated/parser/JsonParser.h
- olp-cpp-sdk-core/include/olp/core/generated/serializer/SerializerWrapper.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/HalfQuadTreeSubdivisionScheme.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/QuadTreeSubdivisionScheme.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/SubTiles.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/TileKey.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/TileTreeTraverse.h
- olp-cpp-sdk-core/include/olp/core/http/Network.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkTypes.h
- olp-cpp-sdk-core/include/olp/core/logging/Configuration.h
- olp-cpp-sdk-core/include/olp/core/logging/ConsoleAppender.h
- olp-cpp-sdk-core/include/olp/core/logging/FileAppender.h
- olp-cpp-sdk-core/include/olp/core/logging/FilterGroup.h
- olp-cpp-sdk-core/include/olp/core/logging/MessageFormatter.h
- olp-cpp-sdk-core/include/olp/core/math/Math.h
- olp-cpp-sdk-core/include/olp/core/math/Vector.h
- olp-cpp-sdk-core/include/olp/core/thread/Atomic.h
- olp-cpp-sdk-core/include/olp/core/thread/TaskScheduler.h
- olp-cpp-sdk-core/include/olp/core/thread/ThreadPoolTaskScheduler.h
- olp-cpp-sdk-core/include/olp/core/utils/LruCache.h
Fix warnings in categories:
* build/include_what_you_use
* runtime/explicit
Relates-To: OLPEDGE-1909
> Fix cpplint warnings.

- scripts/misc/cpplint_ci.sh
> Block PSV on new warnings

- scripts/linux/nv/gitlab_cppcheck_and_upload_sonar.sh
> Fix the cppcheck parameters.

- tests/utils/olp_server/lookup_service.js
Add endpoints for platform and resource lookup apis
Resolves: OLPEDGE-1393
> Add missing mocked endpoints.

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
Test with mock server will be run using separate script.
Relates-To: OLPEDGE-732
> Remove test with mock server from functional tests.

- .gitlab-ci.yml
- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test-mock.sh
- scripts/linux/fv/gitlab_test_fv.sh
Script include starting Server and actually test.
Script will run on FV.
Start it just after normal func tests done.
Relates-To: OLPEDGE-732
> Add script for func tests with MockServer

- scripts/linux/fv/gitlab_test_fv.sh
- scripts/linux/nv/gitlab_test_valgrind.sh
Func tests used only on FV with Mock Server or without.
Also removed outdated staff from NV script and
other disabled tests. Small script refactor.
Fix artifacts URL.
Relates-To: OLPEDGE-732
> NV. Skip functional tests

- olp-cpp-sdk-core/include/olp/core/http/NetworkRequest.h
> Initialize NetworkRequest::settings_

- scripts/misc/commit_checker.sh
Now description is mandatory, trick with third line as
ticket reference will not pass.
Also added new feature: checking reference for lower case.
Relates-To: OLPEDGE-1919
> Commit checker:fix minor bug,add lower case check

- scripts/misc/commit_checker.sh
Fixed if condition typo
Resolves: OLPEDGE-1919
> Commit checker job:fix minor typo

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
Condition always evaluates to true
Relates-To: OLPEDGE-1989
> Fix the condition in LookupApi

- scripts/android/build-test-emulator.sh
Add minor fix for script compatibility on MacOS and Ubuntu.
Add more extended comments for developers.
Relates-To: OLPEDGE-1774
> Android Emulator job:minor fix,comments

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
Read expiration for protected cache. Add unit test.
Relates-To: OLPEDGE-1858
> Check expiration for protected cache.

- olp-cpp-sdk-core/include/olp/core/http/NetworkRequest.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/src/http/android/HttpClient.java
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/ios/OLPNetworkConstants.h
- olp-cpp-sdk-core/src/http/ios/OLPNetworkConstants.mm
- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
> Add OPTIONS http request type

- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
IntrospectApp and Authorize APIs now use new backdown_strategy instead
of old backdown_policy.
Resolves: OLPEDGE-1955
> Use a new backdown_strategy for auth APIs

- olp-cpp-sdk-dataservice-read/src/BlobDataReader.h
- olp-cpp-sdk-dataservice-read/src/BlobDataWriter.h
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.h
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/QuadTreeIndexTest.cpp
Add parsing quad tree data from json to blob.
Add unit test.
Relates-To: OLPEDGE-1931
> Binary storage of quad tree data.

- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
Remove duplicate code.
Remove callback wrappers.
Relates-To: OLPEDGE-2012
> Minor changes in AuthenticationClient

- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientTest.cpp
The test use CreateStreamLayerClient() method in several theads. This
method is not thread safe.
Resolves: OLPEDGE-1835
> Fix ConcurrentPublishDifferentIngestApi fv test

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/http/NetworkUtils.h
- olp-cpp-sdk-core/src/http/NetworkUtils.cpp
Add missing doxygen.
Add file to CMakeLists.txt
Relates-To: OLPEDGE-2026
> Add missing CORE_API export macro

- olp-cpp-sdk-dataservice-read/src/generated/parser/VersionInfosParser.cpp
- olp-cpp-sdk-dataservice-read/src/generated/parser/VersionInfosParser.h
Add functionality to parse versions infos types.
> Add VersionInfos json parser

- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.h
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/MetadataApiTest.cpp
Implement MetadataApi function.
> Add metadata api to get versions list

- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.cpp
- olp-cpp-sdk-authentication/tests/AuthenticationClientTest.cpp
Use different stream objects.
Resolves: OLPEDGE-2041
> Fix the regression caused by #899

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionsRequest.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.h
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/MetadataApiTest.cpp
Implement get versions list in CatalogRepository.
Add tests for CatalogRepository.
> Add functionality to request versions list

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/src/CatalogClient.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.h
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTestBase.cpp
Implement versions list in CatalogClient.
Add tests for CatalogClient.
> Add ListVersions functionality to CatalogClient

- olp-cpp-sdk-dataservice-read/src/generated/serializer/VersionInfosSerializer.cpp
- olp-cpp-sdk-dataservice-read/src/generated/serializer/VersionInfosSerializer.h
- olp-cpp-sdk-dataservice-read/tests/ParserTest.cpp
Add serialize to json.
Add tests for VersionInfos.
> Add ListVersions serialize functionality

- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- tests/common/mocks/NetworkMock.cpp
- tests/common/mocks/NetworkMock.h
- tests/integration/olp-cpp-sdk-dataservice-read/HttpResponses.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Exact same API requests are blocked, and wait for the first one to
complete.
Relates-To: OLPEDGE-2040
> Merge concurrent API requests.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionsRequest.h
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
List versions works only online.
> Remove fetch option from list versions request.

- olp-cpp-sdk-dataservice-write/src/generated/BlobApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/ConfigApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/IngestApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/MetadataApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/PublishApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/QueryApi.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/functional/utils/DefaultResponses.h
- tests/functional/utils/MockServerHelper.cpp
- tests/functional/utils/MockServerHelper.h
- tests/utils/mock-server-client/Client.h
Add versions list CatalogClient tests.
Change functional CatalogClient tests
to use mock server.
Add helper functionality for mock server.
> Add CatalogClient functional tests

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test-mock.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
> Move CatalogClientTests to mock server

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Add changelogs for 1.7.0 release.
Update package version in CMake.
Relates-To: OLPEDGE-1999
> Added 1.7.0 version CHANGELOG

- tests/integration/olp-cpp-sdk-dataservice-write/IndexLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/VolatileLayerClientTest.cpp
Use defines from HttpStatusCodes.h instead of hard-coded values
in integration tests.
Relates-To: OLPEDGE-686
> Change hard-coded values to HttpStatusCodes

- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
- tests/functional/olp-cpp-sdk-core/OlpClientDefaultAsyncHttpTest.cpp
Use defines from HttpStatusCodes.h instead of hard-coded values
Relates-To: OLPEDGE-686
> Change hard-coded values to HttpStatusCodes 

- README.md
Fix badges after renaming on Azure.
Relate-To: OLPEDGE-2082
> CI: Fix one more badge for Azure

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.h
Add explicit to some constructors
Resolves: OLPEDGE-1062
> Fix cppcheck warnings

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/include/olp/authentication/IntrospectAppResult.h
* AuthenticationClient.h
* IntrospectAppResult.h
Relates-To: OLPEDGE-1623
> Review and modify documentation in 2 files

- olp-cpp-sdk-dataservice-write/src/Common.h
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/tests/VersionedLayerClientImplTest.cpp
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-dataservice-write/VersionedLayerClientTest.cpp
Refactor StartBatch code to make it clear. Also added unit and
integration tests.
Resolves: OLPEDGE-1409
> VersionedLayerClient::StartBatch use sync repo

- tests/common/ReadDefaultResponses.cpp
- tests/common/mocks/CacheMock.h
- tests/utils/mock-server-client/Client.h
- tests/utils/mock-server-client/Expectation.h
- tests/utils/mock-server-client/JsonHelpers.h
Additionally fix the compilation of functional tests on windows.
Relates-To: OLPEDGE-2155
> Remove dependency of mockserver to generated code

- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/tests/VersionedLayerClientImplTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/VersionedLayerClientTest.cpp
Merging CompleteBatch lambdas into one sync task. Also added unit and
integration tests to improve coverage.
Resolves: OLPEDGE-1406
> Change CompleteBatch to use sync repo

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataRequest.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Remove deprecated WithVersion method from DataRequest class
Resolves: OLPEDGE-1794
> Remove deprecated methods

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
If tiles in PrefetchRequest have levels, which is greater than min
level we need to get data only for parent tiles starting from min
level, and all children of the tile till max level. In case if we
resived QueryTreeIndex with some sibiling tiles for requested tiles,
we need to skip them.
Change get data part for prefetch to check if data for tile is cached.
In this case we should not read it, and just return succes, as it is
already cached.
Add integration tests to check if prefetch gets only parent and
children tiles in case if requested tile greter than min level.
Check if no requests performed if data is cached.
Relates-To: OLPEDGE-2185
> Prefetch parent or children for requested tiles.

- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
Test trying to cancel request without blocking scheduler queue.
Sometimes this can lead to failed test expectations or even abort.
Resolves: OLPEDGE-2195
> Fix PrefetchTilesCancellableFutureCancel test.

- olp-cpp-sdk-core/include/olp/core/cache/KeyValueCache.h
- olp-cpp-sdk-core/include/olp/core/logging/Log.h
- olp-cpp-sdk-core/include/olp/core/utils/WarningWorkarounds.h
- olp-cpp-sdk-core/src/http/Network.cpp
- olp-cpp-sdk-core/src/thread/ThreadPoolTaskScheduler.cpp
Remove the CORE_LOOP_ONCE macro
Relates-To: OLPEDGE-2201
> Rename the CORE_UNUSED macro

- docs/authenticate.md
Create the following instructions:
- Authenticate using a default token provider
- Authenticate using project authentication
- Authenticate using federated credentials
Relates-To : OLPEDGE-2161
> Document how to authenticate to the HERE platform

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsCacheRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
Removed deprecated method WithVersion from
dataservice read ParttitionsRequest
Resolves: OLPEDGE-2188
> Remove deprecated API

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchStatus.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/PrefetchJob.cpp
- olp-cpp-sdk-dataservice-read/src/PrefetchJob.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Add PrefetchStatus structure.
Add PrefetchStatusCallback type.
Prefetch status callback invoked each time a new tile is prefetched.
> Add a prefetch status callback.

- .gitlab-ci.yml
- scripts/misc/api_compliance.sh
Script will be used in manual Gitlab Job.
As result, script save 4 reports in html format(every lib)
Relates-To: OLPEDGE-2027
> Add API compliance checker script

- olp-cpp-sdk-dataservice-write/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/generated/serializer/CatalogSerializer.cpp
- olp-cpp-sdk-dataservice-write/src/generated/serializer/CatalogSerializer.h
- olp-cpp-sdk-dataservice-write/tests/StreamLayerClientImplTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientTest.cpp
Cache the catalog configuration for 1 hour
Resolves: OLPEDGE-2214
> Fix the duplicate requests to config service

- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.h
- olp-cpp-sdk-authentication/src/SignInResultImpl.h
- olp-cpp-sdk-authentication/src/SignInUserResultImpl.h
- olp-cpp-sdk-authentication/src/SignUpResultImpl.h
- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
- olp-cpp-sdk-core/include/olp/core/geo/projection/EquirectangularProjection.h
- olp-cpp-sdk-core/include/olp/core/geo/projection/IdentityProjection.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.h
- olp-cpp-sdk-core/src/client/repository/ApiCacheRepository.h
- olp-cpp-sdk-core/src/geo/coordinates/GeoCoordinates3d.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/utils/Base64.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.h
- olp-cpp-sdk-dataservice-read/src/generated/api/StreamApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/StreamApi.h
- olp-cpp-sdk-dataservice-read/src/repositories/ApiCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.h
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/generated/PlatformApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/PlatformApi.h
- olp-cpp-sdk-dataservice-write/src/generated/ResourcesApi.cpp
Rename function parameters to be consistent between
declaration and definition
Resolves: OLPEDGE-1062
> Fix Cppcheck issues

- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-dataservice-read/src/ExtendedApiResponse.h
- olp-cpp-sdk-dataservice-read/src/ExtendedApiResponseHelpers.h
- olp-cpp-sdk-dataservice-read/src/PrefetchJob.cpp
- olp-cpp-sdk-dataservice-read/src/PrefetchJob.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/BlobApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/BlobApi.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Add information about bytes downloaded to the prefetch status callback.
Add network statistics to HttpResponse
Add network statistics PrefetchStatus
> Add information about bytes downloaded

- olp-cpp-sdk-dataservice-read/src/PrefetchJob.cpp
On 32Bit targets, size_t is 32 bits, i.e. unsigned int, which results
in a -Wc++11-narrowing error when it gets feed with uint64_t values.
This commit safely narrow-casts by trimming to std::numeric_limits
max for size_t which in case of 64Bit platforms will result in no
data loss while on 32Bit it gets trimmed by 32 upper bits.
This is ok in this case as the value is a counter for downloaded
bytes which is still more than 4GB. We do not expect such huge
values to be downloaded in one shot either way.
> Correct narrow cast from uint64_t to size_t.

- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
In the test we are trying to cancel data request, but scheduler isn't
blocked so sometimes request processed before cancel. Adding blocking
function to the scheduler to fix that.
Resolves: OLPEDGE-2205
> Fix GetDataCancellableFutureCancel test.

- .gitlab-ci.yml
- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-network-test.sh
Add nw test report to reporting job.
Update some variables in script.
Relates-To: OLPEDGE-2243
> Add network test executor to Gitlab FV job

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
This gives functionality to check if the aggregated data is available.
Change the IsCached behavior when the version is not set.
Resolves: OLPSUP-11431
> Extended IsCached API to support aggregated tiles

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Version updated to 1.8.0
Relates-To: OLPEDGE-2246
> Update CHANGELOG file, update package version

- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientGetDataTest.cpp
GetDataWithInvalidDataHandle and GetDataFromPartitionLatestVersionAsync
are moved to mock server.
Resolves: OLPEDGE-1970, OLPEDGE-1964
> Move GetData() tests to mock server.

- scripts/linux/fv/gitlab_test_fv.sh
Add verification of exitcode is not-zero after gtest run
of functional test.
Relates-To: OLPEDGE-2297
> Fix bug in script,catch crashes too

- scripts/misc/cpplint_ci.sh
Cpplint was failing every time when minor warnings found.
Now we fail only for issues in critical PATHs.
Resolves: OLPEDGE-1853
> Fix minor bug in cpplint script

- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/client/OlpClientSettingsFactoryTest.cpp
Add optional callback to PrewarmConnection.
It is called when request completed.
Add unit test,
Relates-To: OAM-665
> Add callback to PrewarmConnection

- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Fix potential crash in
DataserviceReadVersionedLayerClientTest.GetDataFromPartitionAsync.
Which was caused by write to a stack variable
after method return
Resolves: OLPEDGE-2258
>   Fix potential crash in tests 

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
> Update the changelogs, package version to 1.9.0

- README.md
> Add a link to the developer guide

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/porting/shared_mutex.h
Port is based on GCC 7.4 std::shared_mutex implementation
Relates-To: OAM-756
> Added C++11/14 compatible std::shared_mutex

- olp-cpp-sdk-dataservice-read/src/JsonResultParser.h
- olp-cpp-sdk-dataservice-write/src/JsonResultParser.h
GCC 5.4 not able to construct ApiResponse::ResultType due to
the ambiguity of constructors during braced initialization
Relates-To: OAM-756
> Fixed compilation errors under GCC 5.4

- olp-cpp-sdk-core/include/olp/core/porting/shared_mutex.h
Exceptions could be disabled on the target platform.
When they are disabled shared_mutex will use std::abort()
Relates-To: OAM-756
> Fixed shared_mutex for work with -fno-exceptions

- docs/GettingStartedGuide.md
- docs/authenticate.md
- docs/create-platform-client-settings.md
- docs/dataservice-cache-example.md
- docs/dataservice-read-catalog-example.md
- docs/dataservice-read-from-stream-layer-example.md
- docs/dataservice-write-example.md
- Modify several links.
- Change the following heading: "Get partition data from a versioned
layer" to "Get partition data from a versioned layer".
Relates-To: OLPEDGE-2348
> Minor doc updates

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
This commit removes a nasty 100ms wait at the end of the NetworkCurl
run loop which resulted that every CURL download took at least 100ms.
Additionally did some cosmetical clean-ups in the logs and in the code
which doesn't alter the logic.
Resolves: OLPEDGE-2405
> Remove unnecessary sleep in NetworkCurl.

- olp-cpp-sdk-authentication/.clang-format
- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/include/olp/authentication/Types.h
- olp-cpp-sdk-authentication/include/olp/authentication/UserAccountInfoResponse.h
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.h
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.h
- olp-cpp-sdk-authentication/src/Constants.cpp
- olp-cpp-sdk-authentication/src/Constants.h
- olp-cpp-sdk-authentication/src/ResponseFromJsonBuilder.h
- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationMockedResponses.h
GetMyAccount API will retrieve information about user:
firstname, lastname, email, phone number, etc.
Functional and integration tests added too.
Relates-To: OLPEDGE-2385
> Added GetMyAccount API to AuthenticationClient

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
> Add changelogs for 1.10.0 release

- docs/create-platform-client-settings.md
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
> Update the description to `backdown_strategy`

- olp-cpp-sdk-dataservice-read/src/PrefetchPartitionsHelper.h
- olp-cpp-sdk-dataservice-read/src/PrefetchTilesHelper.h
- olp-cpp-sdk-dataservice-read/src/QueryMetadataJob.h
Scheduling query and download jobs is wrapped by ExecuteOrCancelled().
If context is cancelled, jobs will not be scheduled and will never
trigger user callback with `Cancel` error. We must use cancel_fn
callback for such cases to notify user about cancel.
Resolves: OLPEDGE-2423
> Missing prefetch callback on cancel.

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
A potential place where the task can be canceled and not trigger a
callback.
Relates-To: OLPEDGE-2423
> Add a check if the Prefetch operation triggered

- .gitignore
- azure-pipelines.yml
Due to Azure public warning : switch latest on 20.04
Relates-To: OLPEDGE-2408
> Change Azure ubuntu image

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
TaskContext makes additional context.IsCancelled() check after
submitted task is executed. Thus, even if init prefetch task is
finished its still can be cancelled. Prefetch tasks chain can be
completed already, so both responses are sent to the user.
Wrapping user callback to ensure it called only once.
Resolves: OLPEDGE-2435
> Fix prefetch callback called twice after cancel.

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.h
Remove batch parameter from MaybeEvictData function.
Relates-To: OLPEDGE-2392
> Do not mix eviction and put writes in same batch.

- examples/Options.h
Update wrong license text
in examples\Options.h source file
Resolves: OLPEDGE-2420
> Update license text in Options.h

- scripts/misc/cpplint_ci.sh
Fix git error on Github Actions CI:  ambiguous argument
Relates-To: OLPEDGE-2451
> [Minor] Fix CI cpplint script: incorrect branch name

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
Prefetch must give statuses for all tiles, so user can check what is
loaded and what requests are failed. Same for cancel, if atleast one
tile prefetched successfully.
Resolves: oam-740
> Make prefetch report all statuses on cancel.

- docs/dataservice-read-catalog-example.md
- docs/dataservice-write-example.md
- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
* Add notes to `defaultCache.h`.
* Fix inconsistencies in the documentation (examples).
Relates-To: OLPEDGE-2370
> Minor documentation changes

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Update the changelog to package version to 1.11
Relates-To: OLPEDGE-2473
> Release 1.11.0

- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.h
- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.inl
Add CancellationContextHashto CancellationContext that
it could be used in collections.
Relates-To: OAM-865
>  Add CancellationContextHash to CancellationContext

- .gitlab-ci.yml
- scripts/linux/nv/gitlab_test_performance.sh
- scripts/misc/artifactory_upload.sh
All Gitlab test jobs will use this script for uploading
to HERE Artifactory.
Minor directory changes in test jobs for gathering reports.
Relates-To: OAM-796
> Add artifactory upload script for test reports

- olp-cpp-sdk-authentication/include/olp/authentication/AppleSignInProperties.h
First step on Apple Sign-In support
Relates-To: OLPEDGE-2482
> AppleSignInProperties structure

- README.md
Change to the current year.
Relates-To: OLPEDGE-2487
> Update the copyright date.

- olp-cpp-sdk-core/include/olp/core/utils/Base64.h
- olp-cpp-sdk-core/include/olp/core/utils/Config.h
- olp-cpp-sdk-core/include/olp/core/utils/Dir.h
- olp-cpp-sdk-core/include/olp/core/utils/LruCache.h
- olp-cpp-sdk-core/include/olp/core/utils/Url.h
- olp-cpp-sdk-core/include/olp/core/utils/WarningWorkarounds.h
In `olp-cpp-sdk-core/include/Utils`, review and modify the existing
documentation and add missing descriptions so that we have fewer errors
when building the API ref.
Relates-To: OLPEDGE-1450
> Review/modify/add the API doc (`utils` folder)

- scripts/linux/nv/gitlab_test_valgrind.sh
Add additional parameter to valgrind to
improve reports on CI
Resolves: OLPEDGE-2517
> Add additional parameter to valgrind

- .github/workflows/ci.yml
- .gitlab-ci.yml
Add 4 scanners which will scan project for:
- vulnerabilities
- secrets
- license
- dependencies with vulns
Relates-To: OLPEDGE-2506
> Add Gitlab security scanners

- olp-cpp-sdk-core/include/olp/core/math/AlignedBox.h
- olp-cpp-sdk-core/include/olp/core/math/Math.h
- olp-cpp-sdk-core/include/olp/core/math/Size.h
- olp-cpp-sdk-core/include/olp/core/math/Vector.h
In olp-cpp-sdk-core/include/math, review and modify the existing
documentation and add missing descriptions so that we have fewer errors
when building the API ref.
Relates-To: OLPEDGE-1447
> Review/modify/add the API doc (`math` folder)

- olp-cpp-sdk-core/include/olp/core/porting/shared_mutex.h
In olp-cpp-sdk-core/include/olp/core/porting,
review and modify the existing documentation and add missing
descriptions so that we have fewer errors when building the API ref.
Relates-To: OLPEDGE-1448
> Review/add the API doc (`porting`)

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
- tests/common/mocks/CacheMock.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Add posibility to protect/release
partition by its id, which includes
metadata and data handle for partition.
Resolves: OAM-1024
> Add Protect/Release partition

- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
Remove some excessing logging about removal of data
from DataCacheRepository and PartitionsCacheRepository
Resolves: OAM-1024
> Remove excessive logging

- olp-cpp-sdk-core/src/http/android/HttpClient.java
The HttpTask class is internal class, and it should not keep any
references to outer class
Resolves: OLPSUP-14277
> Break the cyclic dependency in android network

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
Old approach with evaluating cache size is quite inefficient and causes
slowdowns for the users. Instead evaluating initial cache size with a
leveldb routine GetApproximateSize(). Performance improvement here is
open now up to x200-x300 times faster. Broken cache size could be also
checked without any memory consumption spikes.
Relates-To: OLPSUP-14421
> Get cache size from leveldb for mutable cache

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
Temporarily revert L0 files detection for protected cache. We don't need
it for now
Relates-To: OAM-1116
> Do not mark as corrupted cache with L0 files

- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
Enable the handling of NSURLErrorNetworkConnectionLost network error
Resolves: OLPEDGE-2566
> Handling of NSURLErrorNetworkConnectionLost error

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Update the changelog and package version to 1.12
Relates-To: OLPEDGE-2555
> Release 1.12.0

- README.md
Correct errors in the list of CMake flags.
Relates-To: OLPEDGE-2573
> Correct errors

- .gitlab-ci.yml
It will be saved for long-term storage.
Relates-To: OAM-972
> Add API compliance report to Artifactory

- tests/performance/MemoryTest.cpp
Update the performance test to collect total bytes written to disk
by the cache.
Relates-To: OLPEDGE-1771
> Update the performance test

- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.h
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
It is done to prevent request repetition if the same request
in other thread have ended up with an error.
This change fixes an issue when task scheduler is overloaded
by the same requests that fails.
Relates-To: OLPSUP-15885
> Extend NamedMutex with an ability to share an ApiError among threads

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Update the changelog to package version to 1.13.
Resolves: OLPEDGE-2636
> Release 1.13.0

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
Path should exist in order to verify permissions and use proper
environment (read-write or read-only) for the cache
Relates-To: OLPEDGE-2664
> Ensure path exists before cache creation

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/IndexLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClientSettings.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/generated/model/ResponseOk.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/generated/model/ResponseOkSingle.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/CheckDataExistsRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/DeleteIndexDataRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/FlushRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/PublishDataRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/PublishIndexRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/PublishPartitionDataRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/PublishSdiiRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/StartBatchRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/UpdateIndexRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/VersionResponse.h
The API documentation should be aligned and follow the Doxygen
documentation rules.
Relates-To: OLPEDGE-855
> Review the `dataservice-write` API docs

- olp-cpp-sdk-authentication/include/olp/authentication/UserAccountInfoResponse.h
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.h
- olp-cpp-sdk-authentication/src/ResponseFromJsonBuilder.h
- olp-cpp-sdk-authentication/src/SignInResultImpl.cpp
- olp-cpp-sdk-authentication/src/SignInUserResultImpl.cpp
- olp-cpp-sdk-authentication/src/SignOutResultImpl.cpp
- olp-cpp-sdk-authentication/src/SignUpResultImpl.cpp
- olp-cpp-sdk-authentication/src/TokenEndpointImpl.cpp
- olp-cpp-sdk-authentication/src/TokenEndpointImpl.h
- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- olp-cpp-sdk-core/include/olp/core/logging/Format.h
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/ProtectedKeyList.cpp
- olp-cpp-sdk-core/src/cache/ProtectedKeyList.h
- olp-cpp-sdk-core/src/http/NetworkUtils.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/thread/ThreadPoolTaskScheduler.cpp
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/SeekRequest.h
- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.h
This commit fixes some of SonarCube reported issues with major and
minor levels including:
- Effective move of passed by value parameters.
- Moved ougth to be static methods to anonymous namespace.
- Pass parameters as reference if they are not copied or moved.
- Initialize variables and members before usage.
- Add check for out-of-bound array access.
Relates-To: OAM-1366
> First batch of SonarCube reported issues fixed.

- .gitlab-ci.yml
Check existing issues:
- whethr it crash scanning or not
- how it works with lambdas
- with c++11
Relates-To: OLPEDGE-2507
> Enable flawfinder again

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogVersionRequest.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
Update default version to exclude valid version from a default request.
Update condition as well to control allowed version to be stored as the
latest one
Relates-To: OAM-1387
> Change default version for CatalogVersionRequest

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CompatibleVersionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/CatalogVersion.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/VersionsResponse.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/VersionsResponseEntry.h
> Add classes for comptabile versions request.

- README.md
Set it to 2022.
Relates-To: OLPEDGE-2449
> Update copyright statement in Readme

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/cmake/curl.cmake
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Update the changelog to package version to 1.14.
Resolves: OLPEDGE-2658
> Release 1.14.0

- CHANGELOG.md
> Fix incorrect release date

- olp-cpp-sdk-core/src/client/PendingUrlRequests.cpp
Add thread id to log when calling CancelAll().
Related-To: OAM-1510
Signed-off-by: Yevhen Krasilnyk <ext-yevhen.krasilnyk@here.com>
> Add thread id to log for PendingUrlRequests.

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Updated changelog and CMakeLists files
Relates-To: OLPEDGE-2751
> Release 1.15.0

- olp-cpp-sdk-dataservice-read/src/DownloadItemsJob.h
- olp-cpp-sdk-dataservice-read/src/QueryMetadataJob.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientPrefetchPartitionsTest.cpp
This reverts commits 6ae2ab2d173298bfb6d09e5b3249e9b08952e128
and c0c64453b8cfe28cb5f59185d1b6f4eecf8ec11a
Relates-To: OLPEDGE-2746
> Revert "Add check if an operation was cancelled (#1338), (#1332)"

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Updated CHANGELOG and CMakeLists files for the HOTFIX release v1.15.1
Relates-To: OLPEDGE-2759, OLPSUP-19082
> Release 1.15.1 Hotfix

- olp-cpp-sdk-core/include/olp/core/client/ApiResponse.h
- olp-cpp-sdk-core/tests/client/ApiResponseTest.cpp
> Add a missing move constructor to the ApiResponse

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Enable the GetData API to return NetworkStatistics along with response
Relates-To: OAM-1718
> Extend the DataResponse with NetworkStatistics

- CHANGELOG.md
- CMakeLists.txt
> Updated files for the release v1.15.3

- README.md
> Update the year to 2023 in README.md file

- README.md
Update Dependencies table
Change Minimal version to Recommended version
Relates-To: OLPEDGE-2794
> Update Dependencies section

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Updated CHANGELOG and CMakeLists files for the release v1.15.4
Relates-To: OLPEDGE-2797
> Release v1.15.4

- olp-cpp-sdk-authentication/src/AutoRefreshingToken.cpp
> Use thread safe time formatting functions in the AutoRefreshingToken

- tests/integration/olp-cpp-sdk-dataservice-write/VersionedLayerClientTest.cpp
> Fixes warning about dangling pointer

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Updated CHANGELOG and CMakeLists files for the release v1.16.0
Relates-To: OAM-2055
> Release v1.16.0

- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.mm
Previosuly HTTP didn't work because HTTPS was set up unconditinally and in case when Proxy server didn't have signed certificate any request failed without attempt to send HTTP request.
This change separates support of HTTP and HTTPS proxy types.
Relates-To: IOTSDK-17819
> Improves support of HTTP proxy on iOS

- olp-cpp-sdk-core/include/olp/core/http/NetworkSettings.h
- olp-cpp-sdk-core/src/http/NetworkSettings.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/tests/http/NetworkSettingsTest.cpp
> Adds possibility to specify DNS in network request

- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
Show more log info in prod build
Change log level for error message when max number of
HTTP requests has been reached. Add status code for failed
HTTP requests.
Relates-To: IOTSDK-19103
Signed-off-by: Nazar Kacharaba <ext-nazar.kacharaba@here.com>
> MINOR: show more log info in prod build.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/Catalog.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/Partitions.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/VersionResponse.h
- olp-cpp-sdk-dataservice-read/src/generated/model/Api.h
- olp-cpp-sdk-dataservice-read/src/generated/model/Index.h
- olp-cpp-sdk-dataservice-read/src/generated/model/LayerVersions.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/generated/model/Details.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/generated/model/Index.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/generated/model/Publication.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/generated/model/ResponseOk.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/generated/model/ResponseOkSingle.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/generated/model/VersionDependency.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/CheckDataExistsRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/DeleteIndexDataRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/FlushRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/PublishDataRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/PublishIndexRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/PublishPartitionDataRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/PublishSdiiRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/StartBatchRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/UpdateIndexRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/VersionResponse.h
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/generated/model/Api.h
- olp-cpp-sdk-dataservice-write/src/generated/model/Catalog.h
- olp-cpp-sdk-dataservice-write/src/generated/model/LayerVersions.h
- olp-cpp-sdk-dataservice-write/src/generated/model/Partitions.h
- olp-cpp-sdk-dataservice-write/src/generated/model/PublishPartition.h
- olp-cpp-sdk-dataservice-write/src/generated/model/PublishPartitions.h
Added copy and move constructors and operators to classes with virtual destructors. Changed some Impl classes to final.
Resolves: OLPEDGE-2838
> Fix rule of five violation.

- olp-cpp-sdk-core/src/cache/DiskCacheEnv.cpp
- scripts/linux/fv/tsan_suppression.txt
- scripts/linux/nv/gitlab_test_valgrind.sh
File contains suppressions:
* leveldb detached thread in scheduler
* leveldb allocated environment
* threads TLS block
Relates-To: OLPEDGE-2827
> Add valgrind suppressions file

- olp-cpp-sdk-authentication/src/Crypto.cpp
- olp-cpp-sdk-core/include/olp/core/geo/tiling/TileKey.h
- olp-cpp-sdk-core/include/olp/core/utils/Dir.h
- olp-cpp-sdk-core/src/cache/ProtectedKeyList.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/VersionDependency.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/VersionInfo.h
cstdint header is required for std::int64_t type
Relates-To: OLPEDGE-2843
> Adapt the code to GCC-13

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Multi handle uses the cache of connections to reuse hot ones. The size of this cache is four times the number of added easy handles. Due to dynamic nature of implementation, number of added easy handles changes a lot, which results in the connection cache thrashing. Connection cache thrashing may result in hard to debug errors, when system returns connected socket with fd > 1024, which then cannot be used in the select due to limitations of FD_SET structure. Use speculatively high number for connection cache size, to accommodate for fluctuations in number of added easy handles.
Relates-To: OLPSUP-26861
> Set connection cache size to 4x of possible easy handles

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
It is possible for curl error to be caused by
reuse of handle or underlying caches with
new network. This occurs on Android after
network switch.
To be on the safe side, do not reuse handle
after any of the curl errors.
Relates-To: POSTI-3214
> Dispose easy_handle after any curl error

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Curl uses CURLOPT_SERVER_RESPONSE_TIMEOUT
for ping pong protocols (ftp, smtp, imap, pop3),
while NetworkCurl uses http exclusively, hence
timeout value specified in NetworkConfig was ignored.
Relates-To: OLPSUP-23107
Signed-off-by: Mykhailo Diachenko <ext-mykhailo.z.diachenko@here.com>
> Use CURLOPT_TIMEOUT_MS for timeout

- olp-cpp-sdk-dataservice-read/tests/AsyncJsonStreamTest.cpp
- olp-cpp-sdk-dataservice-read/tests/MetadataApiTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- tests/common/matchers/NetworkUrlMatchers.h
- tests/common/mocks/NetworkMock.cpp
- tests/common/mocks/NetworkMock.h
Request more than 100 partitions to enter the QueryPartitionsInBatches
Relates-To: OLPEDGE-2845
> Test PartitionsRepository::QueryPartitionsInBatches

- olp-cpp-sdk-core/include/olp/core/generated/parser/ParserWrapper.h
- olp-cpp-sdk-core/src/cache/KeyGenerator.cpp
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/Partitions.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
Mostly removing excess copying, or unnecessary allocations.
Relates-To: OLPEDGE-2848
> Various performance optimizations

- .clang-format
- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.mm
- olp-cpp-sdk-core/src/http/ios/OLPHttpTask.h
- olp-cpp-sdk-core/src/http/ios/OLPHttpTask.mm
- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.h
- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
No functional changes.
Relates-To: OLPEDGE-2849
> Add and apply ObjC clang-format configuration.

- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
To ensure parsing is in another thread so we can cancel it
Relates-To: OLPEDGE-2845
> Use thread in PartitionsRepositoryTest

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
The main goal is to decrease number of calls and number of log messages
Relates-To: OLPEDGE-2855
> Add multi partitions Protect and Release

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
This change contains one minor code cleanup (using a local variable 'curl_handle' instead of repeated 'handle->handle'), a fix for a Curl API deprecation warning (CURLINFO_SIZE_DOWNLOAD is deprecated >= 7.55.0), as well as one (potential) performance improvement.
The 'HeaderFunction' is called for every line of the header.  In case no 'header_callback' is given by the user then we can skip all of the processing.  Additionally, we can avoid one local string copy for the trimmed (trailing '\r' and '\n' removed) input buffer.
> NetworkCurl header parsing performance improvement

- .github/workflows/psv_pipelines.yml
CI: Add Linux gcc11,gcc13 jobs
One with cache and no-cache
Resolves: IMPROVE-CI
> Add linux gcc11,gcc13 CI

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Updated changelog, CMake versions
Relates-To: OLPEDGE-2868
> Release v1.18.1

- .github/workflows/fv_pipelines.yml
- scripts/android/build-test-emulator.sh
- scripts/ios/fv/gh-actions-build-with-tests-fv.sh
- scripts/ios/fv/gh-actions-functional-network-test.sh
- tests/utils/mock-server/package-lock.json
Fix minor CI jobs:
- switch to latest Ubuntu and macOS in FV jobs
- remove hardcoded git plugin version.
- update minor npm tool version.
- run FV only on master.
Resolves: MINOR-CI-FIXES
> Minor CI fixes

- olp-cpp-sdk-core/include/olp/core/porting/shared_mutex.h
Add missing system_error include
> Fix compilation error on gcc 13.2

- docs/authenticate.md
- docs/create-platform-client-settings.md
- docs/dataservice-cache-example.md
- docs/dataservice-read-catalog-example.md
- examples/ProtectedCacheExample.cpp
Verified snippets to be sure they works as expected
Relates-To: OLPEDGE-2865
> Update of code snippets in the docs

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
This may help to investigate issues related to certificates
Relates-To: OLPEDGE-2879
> Log used certificate paths for cURL

- .gitlab-ci.yml
Use image which runs under user instead of root
Resolves: OLPSUP-29798, OAM-2353
> Switch NV job to another docker image

- .github/workflows/psv_pipelines.yml
- scripts/linux/psv/test_psv.sh
Switch to proper Github Actions template
to use Application with token from template
> Fix Codecov job

- docs/dataservice-read-catalog-example.md
- docs/dataservice-write-example.md
Fixes anchor links 404s detected by the link checker.
Resolves: OLPEDGE-2875
Signed-off-by: Tom Papiernik <tomasz.papiernik@here.com>
> OLPEDGE-2875: Fix anchor links

- scripts/ios/fv/gh-actions-functional-network-test.sh
Swithc from iPhone11 to 14
Relates-To: OLPEDGE-2543
> Fix FV iOS job

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Updated CHANGELOG and CMakeLists files for the release v1.19.0
Relates-To: DATASDK-1
> Release v1.19.0

- README.md
- docs/OverallArchitecture.md
- docs/authenticate.md
- docs/create-platform-client-settings.md
- docs/dataservice-cache-example.md
- docs/dataservice-read-catalog-example.md
- docs/dataservice-read-from-stream-layer-example.md
- docs/dataservice-write-example.md
- docs/work-with-data-apis.md
> TECHDOCS-4675: Update developer.here.com links to here.com/docs.

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Update CHANGELOG.md and CMakeLists.txt files for the v1.20.0 release.
Relates-To: DATASDK-35
> Release v1.20.0

- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
Otherwise, this comment is being ignored
Relates-To: OCMAM-187
> Fix Doxygen comment

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Update CHANGELOG.md and CMakeLists.txt files for the v1.20.1 release.
Relates-To: OCMAM-226
> Release v1.20.1

- scripts/linux-armhf/fv/build_armhf_fv.sh
- scripts/linux/fv/build_fv.sh
- scripts/linux/fv/olp-common.variables
- scripts/linux/fv/olp-cpp-sdk-authentication-test.sh
- scripts/linux/fv/olp-cpp-sdk-authentication-test.variables
- scripts/linux/fv/olp-cpp-sdk-core-test.sh
- scripts/linux/fv/olp-cpp-sdk-core-test.variables
- scripts/linux/fv/olp-cpp-sdk-dataservice-read-test.sh
- scripts/linux/fv/olp-cpp-sdk-dataservice-read-test.variables
- scripts/linux/fv/olp-cpp-sdk-dataservice-write-test.sh
- scripts/linux/fv/olp-cpp-sdk-dataservice-write-test.variables
- scripts/linux/fv/olp-cpp-sdk-functional-network-test.sh
- scripts/linux/fv/olp-cpp-sdk-functional-test-mock.sh
- scripts/linux/fv/olp-cpp-sdk-functional-test.sh
- scripts/linux/fv/olp-cpp-sdk-functional-test.variables
- scripts/linux/fv/olp-cpp-sdk-integration-test.sh
- scripts/linux/fv/olp-cpp-sdk-integration-test.variables
- scripts/linux/fv/test_fv.sh
- scripts/linux/fv/tsan_suppression.txt
- scripts/linux/nv/build_valgrind.sh
- scripts/linux/nv/cppcheck_and_upload_sonar.sh
- scripts/linux/nv/sonar-project.propertiesValgrind
- scripts/linux/nv/test_performance.sh
- scripts/linux/nv/test_valgrind.sh
- scripts/linux/weekly/build_perf_tests.sh
- scripts/linux/weekly/performance_tests.json
- scripts/linux/weekly/reports/index.html
- scripts/linux/weekly/run_perf_test_metrics.sh
- scripts/linux/weekly/run_performance_test_metrics.py
- scripts/misc/api_compliance.sh
Full, nightly and performance
verification scripts added for local
and CI usage.
Relates-To: DATASDK-44
> Add FV,NV,Perf jobs

- scripts/misc/cpplint_ci.sh
Recent cpplint 2.0 generates a lot of false positive warnings
> Use cpplint 1.6.1

- external/CMakeLists.txt
- external/boost/CMakeLists.txt.boost.in
Add boost submodules needed by 1.82 boost
> Update boost submodules

- README.md
> Correct URL to getting started guide in README.md

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
Add a missing version additional field value
Relates-To: OCMAM-223
> Add a version additional field value

- olp-cpp-sdk-authentication/tests/CryptoTest.cpp
Need iomanip header for latest clang on macos
> Compile on newer clang

- external/CMakeLists.txt
- external/rapidjson/CMakeLists.txt.rapidjson.in
Newest changes breaks our build
> Use fixed RapidJSON version

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
Use RAII for curl easy handles
Change the RequestHandle initialization sequence
Relates-To: OCMAM-418
> Minor refactoring in NetworkCurl

- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
HttpClient's method `send` was not properly resolved
Relates-To: HERESDK-6072
> Fix the HttpClient method Id

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Updated CHANGELOG.md and CMakeLists.txt files
Relates-To: DATASDK-74
> Release v1.23.1
