heremaps/here-data-sdk-cpp

- olp-cpp-sdk-core/src/network/NetworkSystemConfig.cpp
Fixed a typo in Settings::GetEnvInt method
> Fix typo in NetworkSystemConfig.cpp

- .gitignore
- cmake/android/tester/app/build.gradle.in
- cmake/android/tester/build.gradle
- fixed problems occurred when configuring Android test applications via CMake;
- added missing build.gradle files required for Android test applications;
- changed the global .gitignore file to support buid.gradle files
Resolves: OLPEDGE-355
> Fixed CMake configuration errors of Android tests

- olp-cpp-sdk-core/cmake/android.cmake
- olp-cpp-sdk-core/src/network/android/NetworkProtocol.java
- olp-cpp-sdk-core/src/network/android/NetworkProtocolAndroid.cpp
- olp-cpp-sdk-core/src/network/android/NetworkSSLContextFactory.java
- olp-cpp-sdk-core/src/network/ios/HttpClient.mm
- renamed the NetworkProtocol's package name from com.here.network to com.here.olp.network to avoid name collisions with other projects;
- changed JNI bindings and export macros to avoid symbols collisions
Resolves: OLPEDGE-359
> Fixed linker errors when using EDGE SDK in other HERE Android projects

- .gitignore
- cmake/ios/gen_ios_test.cmake
- cmake/ios/ios_test.sh.in
- Fixed CMake errors when configuring tests on iOS
- Disabled the BUILD_FLAG option in ios_test.sh script
- changed root's .gitignore file to disable only build* folders, not files
Resolves: OLPEDGE-428
> Fixed generation of tester apps when configuring SDK on iOS

- olp-cpp-sdk-core/CMakeLists.txt
Added dependency of olp-cpp-sdk-core on EdgeNetworkProtocol.jar in order to make sure that it is build always when building separate OLP targets
Resolves: OLPSUP-6840
> Build EdgeNetworkProtocol.jar with olp-cpp-sdk-core for Android

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.h
- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.inl
- olp-cpp-sdk-core/tests/client/CMakeLists.txt
- olp-cpp-sdk-core/tests/client/unittest/CancellationContextTest.cpp
- scripts/linux_build.sh
Currently to be able to share the CancellationContext accross multiple contexts
you need to wrap it inside a shared_ptr. As this is designed to be used accross
multiple contexts only, applying a pimpl idiom with shared_ptr automatically
takes care of sharing the CancellationContext.
Relates-to: OLPEDGE-402
> Applies pimpl idiom with shared_ptr to CancellationContext.

- .travis.yml
- scripts/android/build.sh
- scripts/ios/build.sh
This will setup Travis CI to run Android build and IOS build in each job.
Add names labels to jobs.
Resolves: OLPEDGE-531
> Configure Travis CI for Android & IOS build

- olp-cpp-sdk-core/include/olp/core/thread/TaskScheduler.h
To be able to remove the std::thread().detach() usage this introduces
a base class named TaskScheduler for scheduling sync/async tasks, depending
on the user's implementation. As this is interface users are free to
implement their own task scheduling algorithm by overloading this class.
Relates-to: OLPEDGE-393
> Adds TaskScheduler base class for sync/async task scheduling.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogVersionRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/MultiRequestContext.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
PartitionsRequest, CatalogRequest and CatalogVersionRequest now can
generate readable keys by themselves.
CatalogClientImpl class now logs all its major steps.
Relates-to: OLPEDGE-547
> CatalogClientImpl logging improvement

- olp-cpp-sdk-core/include/olp/core/logging/Configuration.h
- olp-cpp-sdk-core/src/logging/Configuration.cpp
This commit removes Configuration::addConsoleAppender() and
Configuration::addDebugAppender() as they are specialized methods which
can also be achieved trough addAppender().
Also applies rule of zero to Configuration class as default operations
are not needed if members have special functions defined.
Relates-to: OLPEDGE-406
> Remove specialized methods from logging::Configuration class.

- olp-cpp-sdk-core/include/olp/core/network2/NetworkResponse.h
- olp-cpp-sdk-core/src/network2/NetworkResponse.cpp
NetworkResponse's GetRequestId() method now returns plain RequestId
instead of const, as constant qualifier has no effect on return value.
Relates-to: OLPEDGE-368
> minor: return value adjustment of NetworkResponse

- .travis.yml
- README.md
- scripts/linux/build.sh
- scripts/linux/test.sh
This will setup Travis CI to run code coverage on gcc compiler job.
Add badges to README.md file.
Remove windows build from Travis CI because of Azure pipelines.
Resolves: OLPEDGE-238
> Configure Travis CI for code coverage

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/cmake/CompileChecks.cmake
- olp-cpp-sdk-core/include/olp/core/thread/ThreadPoolTaskScheduler.h
- olp-cpp-sdk-core/include/olp/core/utils/WarningWorkarounds.h
- olp-cpp-sdk-core/src/thread/ThreadPoolTaskScheduler.cpp
- olp-cpp-sdk-core/tests/thread/unittest/ThreadPoolTaskSchedulerTest.cpp
ThreadPoolTaskScheduler is an async task handler with user-defined amount of
concurrent threads listening to a SyncQueue that is fed by the user with
tasks to be executed trough the TaskScheduler API. Each thread started gets a distinct name, 
this way it is easier to profile or debug the thread pool in case of an error or in a complex system to track which component uses to much CPU time. Thread name setup is currently only supported for Linux, QNX and macOS.
Two basic unit tests scenarios with single-user push and multi-user push also added.
Relates-to: OLPEDGE-394
> Add ThreadPoolTaskScheduler implementing TaskScheduler class.

- olp-cpp-sdk-core/include/olp/core/logging/Log.h
Internally-used macros inside Log.h file now have EDGE_SDK_ prefix
> Internal Log.h macros renaming

- olp-cpp-sdk-core/include/olp/core/logging/Log.h
- olp-cpp-sdk-core/src/network/Network.cpp
- olp-cpp-sdk-core/src/network/RequestContext.h
- olp-cpp-sdk-core/src/network/ios/HttpTask.mm
The macro-enabler is now called EDGE_SDK_LOGGING_DISABLED
> General LOGGING_DISABLED macro prefix adjustment

- olp-cpp-sdk-core/include/olp/core/logging/Log.h
All macros in Log.h now have EDGE_SDK_ prefix.
To ease code review, all currently used macros from Log.h are mocked
with old names.
This allows further step-by-step migration to 'prefixed' logging.
> Log.h macros migration preparation

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/MultiRequestContext.h
- olp-cpp-sdk-dataservice-read/src/PrefetchTilesProvider.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/ApiCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/ApiRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/test/unit/src/CatalogClientTest.cpp
All instances of loggging macros usage in olp-cpp-sdk-dataservice-read
now utilize ones with EDGE_SDK prefix.
> Logging prefix for 'dataservice-read' subproject

- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
All instances of loggging macros usage in olp-cpp-sdk-dataservice-write
now utilize ones with EDGE_SDK prefix.
> Logging prefix for 'dataservice-write' subproject

- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
- olp-cpp-sdk-authentication/test/unit/ArcGisTestUtils.cpp
- olp-cpp-sdk-authentication/test/unit/AuthenticationTests.h
- olp-cpp-sdk-authentication/test/unit/FacebookTestUtils.cpp
- olp-cpp-sdk-authentication/test/unit/GoogleTestUtils.cpp
All instances of loggging macros usage in olp-cpp-sdk-authentication
now utilize ones with EDGE_SDK prefix.
> Logging prefix for 'authentication' subproject

- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/network/Network.cpp
- olp-cpp-sdk-core/src/network/NetworkFactory.cpp
- olp-cpp-sdk-core/src/network/NetworkSystemConfig.cpp
- olp-cpp-sdk-core/src/network/RequestContext.h
- olp-cpp-sdk-core/src/network/android/NetworkProtocolAndroid.cpp
- olp-cpp-sdk-core/src/network/curl/NetworkProtocolCurl.cpp
- olp-cpp-sdk-core/src/network/ios/HttpClient.mm
- olp-cpp-sdk-core/src/network/ios/HttpTask.mm
- olp-cpp-sdk-core/src/network/ios/NetworkProtocolIosImpl.mm
- olp-cpp-sdk-core/src/network/socket/NetworkConnectivitySocketImpl.cpp
- olp-cpp-sdk-core/src/network/winhttp/NetworkProtocolWinHttp.cpp
- olp-cpp-sdk-core/src/thread/ThreadPoolTaskScheduler.cpp
All instances of loggging macros usage in olp-cpp-sdk-core now utilize
ones with EDGE_SDK prefix.
> Logging prefix for 'core' subproject

- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
- olp-cpp-sdk-core/include/olp/core/logging/Log.h
Non-prefix macros are now removed from Log.h since all changes to
various subprojects are merged.
Resolves: OLPEDGE-407
> Temporary macro substitution clean-up

- README.md
Fixed EDGE_SDK_BUILD_EXTERNAL_DEPS description in README.md - now it
represents actual default value from CMakeLists.txt
Resolves: OLPSUP-7011
> Default cmake values in README.md adjustments

- olp-cpp-sdk-core/include/olp/core/network2/Network.h
- olp-cpp-sdk-core/include/olp/core/network2/NetworkTypes.h
This is required to avoid calling callback in the same thread
where Send method was called
Related-To: OLPEDGE-369
> Change return type of Send method in Network from olp::network2

- olp-cpp-sdk-core/include/olp/core/network2/Network.h
- olp-cpp-sdk-core/include/olp/core/network2/NetworkTypes.h
NetworkStatus implied that the return indicates if Network is online/offline
and not that the Send() request was successfull or failed. Renamed to SendOutcome
to mark that it is a outcome pattern applied on to the Send() method.
This Also adapts doxygen comments and certain variable names to make
them more explicit.
Relates-to: OLPEDGE-369
> Rename NetworkStatus to SendOutcome to mark it is a outcome class.

- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
In order to setup OlpClientSettings user should fill-in task_scheduler
field. One of the ways to do that is so use newly introduced
TaskSchedulerFactory class.
Resolves: OLPEDGE-453
> TaskScheduler added to OlpClientSettings

- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
This field meant to be used by all client classes to access web
services.
Resolves: OLPEDGE-542
> Netowk member added to OlpClientSettings

- olp-cpp-sdk-core/cmake/ios.cmake
- olp-cpp-sdk-core/include/olp/core/http/NetworkTypes.h
- olp-cpp-sdk-core/src/http/ios/OLPHttpClient+Internal.h
- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.h
- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.mm
- olp-cpp-sdk-core/src/http/ios/OLPHttpTask+Internal.h
- olp-cpp-sdk-core/src/http/ios/OLPHttpTask.h
- olp-cpp-sdk-core/src/http/ios/OLPHttpTask.mm
- olp-cpp-sdk-core/src/http/ios/OLPNetworkConstants.h
- olp-cpp-sdk-core/src/http/ios/OLPNetworkConstants.mm
- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.h
- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
Implemented the iOS port of Network2 interface based on the NSURLSession.
Basically, this implementation used previous Network1 version as a core,
however some unused functionality were removed.
Resolves: OLPEDGE-370
> Added iOS implementation of Network2 interface

- olp-cpp-sdk-core/include/olp/core/http/NetworkTypes.h
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Changed NO_ERROR to SUCCESS, because it conflicts with define in windows.h
Relates-To: OLPEDGE-372
> Changed NO_ERROR to SUCCESS, because of enum macro conflict

- olp-cpp-sdk-dataservice-write/test/unit/TestIndexLayerClient.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestStreamLayerClient.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestVersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestVolatileLayerClient.cpp
Change the test parameters.
Environment variables must not contain dashes.
Relates-To: OLPEDGE-486
> Replaced dashes to underscores in test parameters.

- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
Align the offline error when we destroy the instance.
Added a conversion of http code to string.
Relates-To: OLPEDGE-370
> Align iOS network implementation with Curl and Windows

- scripts/linux/test.sh
Enable mocked and offline tests for linux PSV.
Some failing tests are disabled.
Relates-To: OLPEDGE-486
> Enable offline read and write tests

- examples/dataservice-read/example.cpp
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
- olp-cpp-sdk-core/include/olp/core/thread/TaskScheduler.h
- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
- olp-cpp-sdk-core/tests/thread/unittest/ThreadPoolTaskSchedulerTest.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/ApiRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/ApiRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/ExecuteOrSchedule.inl
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
Instead o fcreating detached threads use TaskScheduler to invoke
callbacks.
Based on draft PR #82.
Relates-To:OLPEDGE-456
> Remove std::thread raw usage replacing it with TaskScheduler

- olp-cpp-sdk-core/cmake/android.cmake
- olp-cpp-sdk-core/src/http/android/NetworkProtocol.java
- added NetworkProtocol.java, which implements the http network interface,
which is based on the previous version of NetworkProtocol.java;
- also, aligned the java code to Google Java code style;
In order to generate the new EdgeNetworkProtocol.jar based on http interface,
use the EDGE_SDK_USE_HTTP_NETWORK_PROTOCOL=YES cmake var.
Relates to: OLPEDGE-371
> Ported NetworkProtocol.java to the new http network interface

- olp-cpp-sdk-core/cmake/android.cmake
- olp-cpp-sdk-core/src/http/android/HttpClient.java
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
Renamed the NetworkProtocol.java into HttpClient.java to avoid collision
with old implementation of the NetworkProtocol.java (see previous network).
Resolves: OLPEDGE-646
> Renamed http NetworkProtocol into HttpClient to avoid collision

- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/ApiRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
Fix double callback in catalog client.
Partition repository captures cache by shared_ptr (Fix for dangling pointer).
Resolves: OLPEDGE-633
> Adapt Api repository to use task scheduler instead of std::thread

- olp-cpp-sdk-core/src/logging/MessageFormatter.cpp
- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-write/src/ApiClientLookup.cpp
To support china use cases two new URLs will be used for
here-cn and here-cn-dev partitions based on the provided HRN.
This also fixes a small bug in the logging formatter.
Relates-to: OLPEDGE-558
> Add china URLs to read and write lookup API.

- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/PrefetchTilesProvider.cpp
- olp-cpp-sdk-dataservice-read/src/PrefetchTilesProvider.h
Adapt PrefetchTilesProvider to use task scheduler instead of std::thread.
Resolves: OLPEDGE-631
> Adapt PrefetchTilesProvider to use task scheduler.

- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
Adapt PrefetchTilesRepository to use task scheduler.
For a scenario when the task scheduler not present, std::thread is used.
Else, the network thread is blocked with a waiting for promise.
Resolves: OLPEDGE-632
> Adapt PrefetchTilesRepository to use task scheduler.

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
- olp-cpp-sdk-core/include/olp/core/http/Network.h
- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
- olp-cpp-sdk-core/src/http/Network.cpp
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
Provide a free function that returns unique_ptr to default network
implementation.
Related-To: OLPEDGE-641
> Add factory for default network implementation

- CMakeLists.txt
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/http/Network.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkConstants.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
Added OLP-CPP-SDK User-Agent header for all request in olp-cpp-sdk-core with next format:
User-Agent: OLP-SDK-CPP/<Version> (<PlatformName>)
Resolves: OLPEDGE-552
> Added the User-Agent header to http network request

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-authentication/test/unit/AuthenticationTests.cpp
- olp-cpp-sdk-authentication/test/unit/AuthenticationTests.h
Internal implementation classes in authentication now are marked as
final.
Members in test classes aligned to code style.
Relates-to: OLPEDGE-543
> minor style changes to authentication

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/test/unit/src/CatalogClientTest.cpp
- scripts/linux/fv/gitlab-olp-dataservice-read-test.sh
- scripts/linux/psv/travis_test_psv.sh
When adding a layers partition metadata response to the cache the
key is hrn::layer::version::partitions. In case we receive a 403 error
we try to delete the entire entry from the cache with RemoveKeysWithPrefix()
were the key was hrn::layer::::partitions which didn't work as the entries
include version also. Changing the key in case no version is provided to
hrn::layer:: which will get successfull prefix comparison in the cache impl.
Relates-to: OLPEDGE-643
> Fixes the cache clear key for partitions and the according test.

- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
- olp-cpp-sdk-core/include/olp/core/http/Network.h
- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
- olp-cpp-sdk-core/src/http/Network.cpp
Changed network factory method to produce a shared_ptr instead of unique_ptr.
Currently network implementation are derived from std::enable_shared_from_this
and it requires to be a shared_ptr.
Relates-To: OLPEDGE-543
> Temporary change network factory method to produce shared_ptr.

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
The body's data now stored at CURL's handle structure as a shared
pointer. This allows to be sure the data would not be destroyed during
the send process.
Relates-to: OLPEDGE-692
> NetworkCurl body payload handling fix

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.h
Previously network requests was captured as a copy on upper levels (by a user),
and there was no such problem.
Relates-To: OLPEDGE-692
> Added a capture for a network body for winhttp implementation

- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.h
Fixed bug with inability to send the requests because NetworkAndroid wasn't initialized.
Relates to: OLPEDGE-371, OLPEDGE-543
> Fixed problem with inability to send new requests with NetworkAndroid

- docs/dataservice-read-catalog-example.md
- docs/dataservice-write-example.md
- examples/dataservice-read/example.cpp
- examples/dataservice-write/example.cpp
- olp-cpp-sdk-core/include/olp/core/client/OlpClient.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/include/olp/core/utils/Url.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/src/http/Network.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/utils/Url.cpp
- olp-cpp-sdk-core/tests/olpclient/unittest/OlpClientTest.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/serializer/ApiSerializer.cpp
- olp-cpp-sdk-dataservice-read/src/generated/serializer/CatalogSerializer.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/ApiRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/ApiRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/test/unit/src/ApiTest.cpp
- olp-cpp-sdk-dataservice-read/test/unit/src/CatalogClientTest.cpp
- olp-cpp-sdk-dataservice-read/test/unit/src/SerializerTest.cpp
- olp-cpp-sdk-dataservice-write/src/generated/serializer/IndexInfoSerializer.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestIndexLayerClient.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestParser.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestStreamLayerClient.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestVersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestVolatileLayerClient.cpp
Adapt OLP SDK to use new network implementation
* OlpClient now uses new Network
* Core online & offline tests
* Dataservice-read online & offline tests
* Dataservice-write online & offline tests
Relates-To: OLPEDGE-544, OLPEDGE-545, OLPEDGE-546
> Adapt OLP SDK to use net network implementation

- olp-cpp-sdk-core/src/http/android/HttpClient.java
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
Fixed problem with `StreamLayerClientOnlineTest.ConcurrentPublishDifferentIngestApi` test, which
was deadlocked because of invalid NetworkAndroid uniqueId generating policy:
there was the data race that there are could be created several instances of NetworkAndroid,
which had same unique id, thus, it resulted that some requests were lost.
Relates to: OLPEDGE-697
> Fixed data race when generating NetworkAndroid's unique id

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.h
Removed WinHttp inheritance from std::enable_shared_from_this.
Fixes the issue with new network design when network expected to be
destroyed after the last pointer is destroyed.
Relates-To: OLPEDGE-544
> Removed WinHttp inheritance from std::enable_shared_from_this

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestIndexLayerClient.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestStreamLayerClient.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestVersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestVolatileLayerClient.cpp
Network is instantiated once for every test suite and reused in all tests of that suite.
Relates-to: OLPEDGE-544
> Keep network instance in unit tests alive until inner thread is running

- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.cpp
Fix mutex double locking when the callback is executed sync.
Relates-To: OLPEDGE-667
> Fix mutex double locking when the callback is executed sync.

- olp-cpp-sdk-dataservice-write/test/unit/TestVolatileLayerClient.cpp
Disabled flaky VolatileLayerClientOnlineTest.StartBatchDeleteClientTest because we receive the 500 internal server error.
Related-to: OLPEDGE-697, OLPEDGE-709
> Disabled StartBatchDeleteClientTest in volatile layer client test

- olp-cpp-sdk-dataservice-write/test/unit/TestVersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-write/test/unit/TestVolatileLayerClient.cpp
Some dataservice-write tests uses the same getBatchResponse waiting logic to determine whether batch was correctly submitted and succeeded. However, because of some limitations on server, we might not receive the response in time (i.e. after 100 iterations). Thus, such tests appear to be flaky. Because of this, need to temporarily disable failing checks in those tests until proper solution will be found.
Relates to: OLPEDGE-697, OLPEDGE-708
> Fixed flaky tests about waiting for the getBatchResponse success

- olp-cpp-sdk-core/cmake/android.cmake
- olp-cpp-sdk-core/cmake/curl.cmake
- olp-cpp-sdk-core/cmake/ios.cmake
- olp-cpp-sdk-core/cmake/winhttp.cmake
Removed outdated references from CMake.
Fixed incorrect paths for winhttp
Relates-To: OLPEDGE-683
> Removed outdated references from CMake

- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
- re-enabled the DefaultCacheTest.bad_path in order to increase code coverage;
- aligned DefaultCacheTest naming with new naming guidelines.
Relates to: OLPEDGE-419
> Enabled DefaultCacheTest.bad_path test

- olp-cpp-sdk-core/tests/CMakeLists.txt
Make core tests a part of olp-cpp-sdk-core project
Relates-to: OLPEDGE-591
> Make core tests a part of olp-cpp-sdk-core project

- olp-cpp-sdk-core/include/olp/core/http/NetworkResponse.h
- olp-cpp-sdk-core/src/http/NetworkResponse.cpp
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogClientTest.cpp
- olp-cpp-sdk-dataservice-write/tests/TestCommons.cpp
Cancellation flag is duplicated by status code.
Method is not used by SDK.
Resolves: OLPEDGE-780
> Remove cancelled flag from NetworkResponse

- olp-cpp-sdk-dataservice-read/tests/CatalogClientTest.cpp
Update-related tests no longer wait for cancel signal.
Relates-to: OLPEDGE-678
> Fixed some disabled unit test GetCatalogClient

- scripts/linux/fv/gitlab-olp-cpp-sdk-core-test.sh
This commit disables DefaultCacheTest.BadPath test on FV until the actual reason will be found.
Maybe it somehow related to docker configuration, because FV uses docker in contrary to PSV.
skip ci 
Relates to: OLPEDGE-419
> Disabled DefaultCacheTest.BadPath test on FV. skip ci

- cmake/android/tester/app/jni/com_here_android_olp_TesterActivity.cpp
- cmake/ios/tester/CMakeLists.txt.in
- cmake/ios/tester/MyViewController.mm
- olp-cpp-sdk-authentication/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/tests/CMakeLists.txt
- Fixed CMake and build errors, which were caused by refactoring of unit tests folder structure;
- Removed dependency on CustomParameters in iOS / Android tester applications;
Relates to: OLPEDGE-788, OLPEDGE-422, OLPEDGE-421
> Fixed CMake and build errors when configuring tests for iOS / Android

- olp-cpp-sdk-core/include/olp/core/logging/Log.h
- Renamed the prefix from EDGE_SDK to OLP_SDK in Log.h;
- Preserved old EDGE_SDK macros until all usage of macros will be removed from SDK.
> Renamed the prefix EDGE_SDK in logging macros to OLP_SDK in Log.h

- .gitlab-ci.yml
Updated .gitlab-ci.yml with nv job. No script execution yet, only echo.
Gitlab CI will have now two "Schedules":
- nightly (once at midnight). Env. variable to be defined in schedule: $NIGHTLY ;
- full (every hour). Env. variable to be defined in schedule: $FULLY;
skip travis
Resolves: OLPEDGE-485
Signed-off-by: Yaroslav Stefinko <ystefinko@intellias.com>
> Updated .gitlab-ci.yml with nv job. No script execution yet, only echo.[skip travis]

- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.mm
- olp-cpp-sdk-core/src/http/ios/OLPHttpTask.mm
- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/thread/ThreadPoolTaskScheduler.cpp
Renamed logging macros in olp-cpp-sdk-core module from EDGE_SDK prefix to OLP_SDK prefix.
> Renamed logging macros in olp-cpp-sdk-core module

- .gitlab-ci.yml
Fixed minor bug, so translate_report and deploy will run on schedule only. [skip ci]
[skip travis]
Resolves: OLPEDGE-485
> Fixed minor bug, so translate_report and deploy will run on schedule only. [skip travis]

- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
Instead of passing the KeyValueCache to the clients trough constructor,
rather pass it as part of OlpClientSettings and keep the constructor clean.
This is the first step towards splitting the CatalogClient into layers.
- Add KeyValueCache as shared_ptr to OlpClientSettings struct.
- Add default cache method to OlpClientSettingsFactory.
Relates-to: OLPEDGE-671
> Adds the KeyValueCache as shared to the OlpClientSettings.

- CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/ApiTest.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogClientTest.cpp
- olp-cpp-sdk-dataservice-write/tests/TestIndexLayerClient.cpp
- olp-cpp-sdk-dataservice-write/tests/TestStreamLayerClient.cpp
- olp-cpp-sdk-dataservice-write/tests/TestVersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-write/tests/TestVolatileLayerClient.cpp
- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-integration-test.sh
- scripts/linux/fv/gitlab_test_fv.sh
- scripts/linux/fv/olp-cpp-sdk-functional-test.variables
- scripts/linux/fv/olp-cpp-sdk-integration-test.variables
- scripts/linux/fv/olp-dataservice-read-test.variables
- tests/functional/olp-cpp-sdk-core/OlpClientDefaultAsyncHttp.cpp
- tests/integration/CMakeLists.txt
- tests/integration/placeholder.cpp
* use different ENV variable names for dataservice-read & -write
* move 2 online tests from core to tests/integration
Relates-To: OLPEDGE-717
> Separate unit & integration core tests

- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
- olp-cpp-sdk-authentication/tests/ArcGisTestUtils.cpp
- olp-cpp-sdk-authentication/tests/AuthenticationOnlineTest.h
- olp-cpp-sdk-authentication/tests/FacebookTestUtils.cpp
- olp-cpp-sdk-authentication/tests/GoogleTestUtils.cpp
Renamed logging macros in olp-cpp-sdk-authentication module from EDGE_SDK prefix to OLP_SDK
> Renamed logging macros in olp-cpp-sdk-authentication module

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/MultiRequestContext.h
- olp-cpp-sdk-dataservice-read/src/PrefetchTilesProvider.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/ApiCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
Renamed logging macros in olp-cpp-sdk-dataservice-read module from EDGE_SDK prefix to OLP_SDK
+ fixed warning regarding invalid usage of format usage in formatting log macros
> Renamed logging macros in olp-cpp-sdk-dataservice-read module

- docs/dataservice-read-catalog-example.md
- docs/dataservice-write-example.md
- examples/dataservice-read/example.cpp
- examples/dataservice-write/example.cpp
Renamed logging macros in examples and docs from EDGE_SDK prefix to OLP_SDK
> Renamed logging macros in examples and docs

- olp-cpp-sdk-dataservice-write/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
Renamed logging macros in olp-cpp-sdk-dataservice-write module from EDGE_SDK prefix to OLP_SDK
> Renamed logging macros in olp-cpp-sdk-dataservice-write module

- olp-cpp-sdk-dataservice-read/src/repositories/ApiRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- Renamed the leftover EDGE_SDK logging macros to OLP_SDK in dataservice-read module
- Fixed formatting according to Google C++ Code Style
> Renamed leftover EDGE_SDK logging macros to OLP_SDK

- olp-cpp-sdk-core/include/olp/core/logging/Log.h
Removed deprecated EDGE_SDK_LOG macros from Log.h.
Please, use the OLP_SDK_LOG instead.
> Removed deprecated EDGE_SDK_LOG from Log.h

- CMakeLists.txt
- CONTRIBUTING.md
- README.md
- docs/CMakeLists.txt
- docs/dataservice-read-catalog-example.md
- docs/dataservice-write-example.md
- external/googletest/CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
- scripts/android/build.sh
- scripts/ios/build.sh
- scripts/linux/fv/gitlab_build_fv.sh
- scripts/linux/psv/travis_build_psv.sh
- scripts/macos/psv/travis_build_psv.sh
- testutils/custom-params/CMakeLists.txt
Renamed prefix of all the public CMake variables, which are accessible for the user, from EDGE_SDK to OLP_SDK;
> Renamed prefix of public CMake variables from EDGE_SDK to OLP_SDK

- cmake/android/tester/CMakeLists.txt.in
- examples/helpers/android/app/CMakeLists.txt.in
- examples/helpers/android/app/build.gradle.in
- examples/helpers/cmake/gen_android_example.cmake.in
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/cmake/android.cmake
Renamed the generated jar, which contains HttpClient.java file from EdgeHttpClient.jar into OlpHttpClient.jar
> Renamed EdgeHttpClient.jar artifact into OlpHttpClient.jar

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Return ErrorCode::NETWORK_OVERLOAD_ERROR if CURL network implementation
has no free curl handles.
Add more log messages to non-happy execution paths.
Relates-to: OLPEDGE-813
> Change error code returned by CURL network

- CMakeLists.txt
- tests/common/CMakeLists.txt
- tests/common/mocks/NetworkMock.cpp
- tests/common/mocks/NetworkMock.h
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationMockedResponses.h
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
- Moved Authentication integration tests (basically all authentication offline tests) from olp-cpp-sdk-authentication/tests/ folder to tests/integration/olp-cpp-sdk-authentication folder;
- Created a olp-cpp-sdk-tests-helpers target which contains common mocks (currently only NetworkMock.h).
> Moved Authentication integration tests to tests/integration folder

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
- scripts/linux/fv/gitlab_test_fv.sh
Add local server and enable functional testing on FV Gitlab
Server starts on Nodejs. Functional tests run against that server.
Then tests are finished and server is stopped.
[skip ci] skip travis
Relates-To: OLPEDGE-716
> Create localhost server and setup a network test suite on FV [skip travis]

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
skip ci
Relates-To: OLPEDGE-716
Signed-off-by: Yaroslav Stefinko <ystefinko@intellias.com>
> Fix incorrect path to server.js in functional tests script

- tests/common/CMakeLists.txt
- tests/common/matchers/NetworkUrlMatchers.h
- tests/common/mocks/CacheMock.cpp
- tests/common/mocks/CacheMock.h
- tests/common/mocks/NetworkMock.cpp
- tests/common/mocks/NetworkMock.h
Network and Cache mocks moved to tests/common
IsGetRequest matcher moved from inline definition to a dedicated place
> Common tests mocks refactoring

- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.h
- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.inl
- olp-cpp-sdk-core/include/olp/core/client/Condition.h
- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.h
- olp-cpp-sdk-dataservice-read/tests/ApiClientLookupTest.cpp
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/HttpResponses.h
ApiClientLookup class now has a static LookupApi() method.
It is aimed to provide synchronous interface for querying lookup api.
ApiClientLookupTest introduced to test it.
Relates-to: OLPEDGE-832
> ApiClientLookupTest online mocks implementation

- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-authentication/AuthenticationCommonTestFixture.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationCommonTestFixture.h
- tests/functional/olp-cpp-sdk-authentication/AuthenticationFunctionalTest.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationUtils.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationUtils.h
- tests/functional/olp-cpp-sdk-authentication/TestConstants.h
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
Copied AuthenticationOnlineTest from olp-sdk-cpp-authentication/tests folder to <root>/tests/functional folder in order to meet the Pitchfork layout model.
Also, following changes were applied:
- renamed AuthenticationOnlineTest.h -> AuthenticationCommonTestFixture.h
- added AuthenticationCommonTestFixture.cpp to reduce compilation times between other test suites;
- renamed AuthenticationOnlineTest.cpp -> AuthenticationFunctionalTest.cpp
- renamed CommonTestUtils.h -> TestConstants.h
- applied Google C++ Code Style guidelines
Realtes to: OLPEDGE-718
> Copied AuthenticationOnlineTest to <root>/tests/functional folder

- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-authentication/FacebookAuthenticationTest.cpp
- tests/functional/olp-cpp-sdk-authentication/FacebookTestUtils.cpp
- tests/functional/olp-cpp-sdk-authentication/FacebookTestUtils.h
Copied functional test FacebookAuthenticationOnlineTest to <root>/tests/functional folder with following changes:
- FacebookAuthenticationOnlineTest fixture class moved to cpp side;
- FacebookAuthenticationOnlineTest renamed to FacebookAuthenticationTest;
Relates To: OLPEDGE-718
> Copied FacebookAuthenticationOnlineTest to <root>/tests/functional

- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/CatalogClientTestBase.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogClientTestBase.h
This will ease separation of CatalogClientTest and
CatalogClientCacheTest.
> Copy CatalogClient Fixture to the base class

- olp-cpp-sdk-dataservice-read/tests/CatalogClientTestBase.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogClientTestBase.h
* #pragma once in CatalogClientTestBase.h
* make all public methods of CatalogClientTestBase protected
> Add pragma once guard to the header

- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-authentication/ArcGisAuthenticationTest.cpp
- tests/functional/olp-cpp-sdk-authentication/ArcGisTestUtils.cpp
- tests/functional/olp-cpp-sdk-authentication/ArcGisTestUtils.h
Copied the ArcGisAuthenticationOnlineTest from olp-sdk-authentication/tests to <root>/tests/functional folder with following changes:
- renamed ArcGisAuthenticationOnlineTest to ArcGisAuthenticationTest;
- moved ArcGisAuthenticationTest class fixture to cpp file;
> Copy ArcGis functional tests to <root>/tests

- olp-cpp-sdk-dataservice-read/tests/CatalogClientCacheTest.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogClientTest.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogClientTestBase.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogClientTestBase.h
* inherit CatalogClientTestBase in CatalogClientTest
* cleanup #includes in CatalogClientBase
* move operator<<(ostream, CacheType) to CatalogClientTestBase source
*  remove GetExecutionTime function, get CatalogClient response directly
> Inherit CatalogClientTestBase in CatalogClientTest

- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-authentication/GoogleAuthenticationTest.cpp
- tests/functional/olp-cpp-sdk-authentication/GoogleTestUtils.cpp
- tests/functional/olp-cpp-sdk-authentication/GoogleTestUtils.h
Copied the GoogleAuthenticationOnlineTest from olp-sdk-authentication/tests to <root>tests/functional folder with following changes:
- renamed GoogleAuthenticationOnlineTest to GoogleAuthenticationTest;
- moved GoogleAuthenticationTest class fixture to cpp file;
> Copy Google functional tests to <root>/tests

- codecov.yml
Exclude mocks and matchers from coverage reports.
> Exclude non-unit tests from coverage report

- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-authentication/AuthenticationProductionTest.cpp
Copied the AuthenticationProductionTest from olp-sdk-authentication/tests to tests/functional folder with following changes:
- reused constants from TestConstants.h;
- applied Google C++ code style.
> Copy Auth production test to <root>/tests folder

- tests/common/mocks/NetworkMock.cpp
- tests/common/mocks/NetworkMock.h
GenerateNetworkMocks is now called GenerateNetworkMockActions and
defined in NetworkMock source file.
> Copy GenerateNetworkMocks function to tests-common

- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-authentication/HereAccountOauth2ProductionTest.cpp
Copied the HereAccountOauth2IntegrationOnlineTest from olp-sdk-authentication/tests to <root>tests/functional folder with following changes:
- renamed HereAccountOauth2IntegrationOnlineTest to HereAccountOauth2ProductionlTest;
- removed unused free functions;
- moved free functions to the top of the tests file;
- refactor code to adhere to C++ Google style;
> Copy HereAccountOauth2 test to root/tests folder

- tests/functional/olp-cpp-sdk-authentication/AuthenticationCommonTestFixture.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationCommonTestFixture.h
- tests/functional/olp-cpp-sdk-authentication/AuthenticationFunctionalTest.cpp
Moved the AuthenticationFunctional specific methods from AuthenticationCommonTestFixture to the AuthenticationFunctionalTest.
Realtes to: OLPEDGE-718
> Move AuthFunctional methods to corresponding test

- olp-cpp-sdk-core/include/olp/core/client/Condition.h
- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/tests/ApiClientLookupTest.cpp
The test aligned to have appropriate suffix according to coding style.
The test extended for 'cancel' and 'error' cases.
Relates-to: OLPEDGE-832
> ApiClientLookupTest extension

- olp-cpp-sdk-dataservice-write/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/tests/IndexLayerClientTest.cpp
Rename test and source file. Remove dead code. Switch from parameterized
test to fixture.
> Adapt codestyle in IndexLayerClient test

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/tests/ApiClientLookupTest.cpp
Added the condition's unblock on cancel event to cover a case when user
cancelled the operation before it actually was set up.
Relates-to: OLPEDGE-832
> ApiClientLookup cancel-before-execution case

- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.h
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
Add sync version of GetLatestVersion to CatalogRepository, based
on sync LookupApi and adaptation of async MetadataApi. Cover
implementation with tests.
Relates-to: OLPEDGE-834
> Add sync GetLatestVersion

- tests/functional/olp-cpp-sdk-authentication/ArcGisAuthenticationTest.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationCommonTestFixture.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationCommonTestFixture.h
- tests/functional/olp-cpp-sdk-authentication/AuthenticationFunctionalTest.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationProductionTest.cpp
- tests/functional/olp-cpp-sdk-authentication/FacebookAuthenticationTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
Fixed the review comments in authentication functional and integration tests:
- moved tests into anonymous namespace to adhere to Google C++ code style;
- removed future.wait() method because of request.get() is already present;
- includes reordering and improvement;
> Fixed review comments in authentication tests

- olp-cpp-sdk-dataservice-write/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/tests/StreamLayerClientTest.cpp
Rename source file and test. Reorder #includes. Rename variables.
Replace parameterized test by fixture. Remove dead code.
> Adopt code style in StreamLayerClient test

- scripts/linux/psv/travis_test_psv.sh
Disable dataservice-write cache offline tests.
Relates-to: OLPEDGE-857
> Disable dataservice-write cache offline tests

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/FlushSettings.h
- olp-cpp-sdk-dataservice-write/src/AutoFlushController.cpp
- olp-cpp-sdk-dataservice-write/src/TimeUtils.cpp
- olp-cpp-sdk-dataservice-write/src/TimeUtils.h
- olp-cpp-sdk-dataservice-write/tests/TimeUtilsTest.cpp
1. Removed auto_flush_time_period property from FlushSettings.
2. Removed TimePeriod enum class.
3. Removed corresponding methods which used the auto_flush_time_period in AutoFlushController
4. Removed unused TimeUtils methods and updated TestTimeUtils's tests.
Resolves: OLPEDGE-814
> Removed auto_flush_time_period from FlushSettings

- olp-cpp-sdk-dataservice-write/tests/CMakeLists.txt
- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteIndexLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
Affected tests:
* IndexLayerClientOnlineTest
* StreamLayerClientOnlineTest
* VersionedLayerClientOnlineTest
* VolatileLayerClientOnlineTest
> Move online tests to tests/functional/

- olp-cpp-sdk-dataservice-write/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/tests/VolatileLayerClientTest.cpp
Rename test and source file. Put code into anonymous namespace. Replace
parameterized test by fixture. Reorder #includes.
> Adopt codestyle on VolatileLayerClient test

- olp-cpp-sdk-dataservice-read/src/MultiRequestContext.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
Added sync version of DataRepository::GetData in olp::dataservice::read module
Added tests that cover DataRepository::GetBlobData method
Added #include<memory> to MultiRequestContext.h to fix tests compilation
Resolves: OLPEDGE-835
> Added DataRepository::GetBlobData() sync method

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
Add sync version of GetPartitionById to PartitionsRepository, based
on sync LookupApi of ApiClientLookup and QueryApi::GetPartitionsbyId.
PartitionsRepositoryTest introduced to cover the functionality with unit
tests.
Relates-to: OLPEDGE-833
> Sync API for Partition repo's GetPartitionById

- CMakeLists.txt
- tests/performance/CMakeLists.txt
- tests/performance/CatalogClientTest.cpp
The test performs N request per second for M seconds.
Valgrind, heaptrack, other tools are used to collect the output.
Local OLP server required.
Relates-to: OLPEDGE-745
> Add performance test for CatalogClient GetData.

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
PartitionsRepository now can handle empty version in DataRequest.
PartitionsRepositoryTest cleaned up.
> PartitionsRepository version handling

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.h
Pass HRN, settings and callbacks to VersionedLayerClient by value. This
aligns interface with read dataservice API.
> Pass arguments to VersionedLayerClient by value

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.h
Pass HRN, settings and callbacks to VolatileLayerClient by value. This
aligns interface with read dataservice API.
> Pass arguments to VolatileLayerClient by value

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientTest.cpp
Create VolatileLayerClient and VolatileLayerClientImpl classes:
- document usage of VolatileLayerClient
- add test skeletons for VolatileLayerClient and VolatileLayerClientImpl
Relates-to: OLPEDGE-758
> Add VolatileLayerClient class.

- olp-cpp-sdk-dataservice-read/tests/ApiClientLookupTest.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- tests/common/matchers/NetworkUrlMatchers.h
- tests/common/mocks/CacheMock.cpp
- tests/common/mocks/CacheMock.h
- tests/common/mocks/NetworkMock.cpp
- tests/common/mocks/NetworkMock.h
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTestBase.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTestBase.h
- tests/integration/olp-cpp-sdk-dataservice-write/IndexLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/VolatileLayerClientTest.cpp
All mocks and matchers are now under olp::tests::common.
> Put all test-related code into namespace

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/FlushEventListener.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/FlushMetrics.h
- tests/common/CMakeLists.txt
- tests/common/testables/FlushEventListenerTestable.h
- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientCacheTest.cpp
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
- added FlushMetrics struct to dataservice-write component;
- removed all GetNum...() methods from FlushEventListener;
- added NotifyFlushMetricsHasChanged callback;
- updated integration and functional tests with FlushEventListenerTestable.
Resolved: OLPEDGE-816
> Added FlushMetrics to FlushEventListener

- examples/dataservice-read/example.cpp
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/src/CatalogClient.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.h
- tests/functional/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTestBase.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTestBase.h
- tests/performance/CatalogClientTest.cpp
Pass HRN and settings to CatalogClient by value. Cache is passed as
OlpClientSettings. This aligns interface with read dataservice API.
> Pass arguments to CatalogClient by value

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/IndexLayerClient.h
- olp-cpp-sdk-dataservice-write/src/IndexLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.h
Pass HRN, settings and callbacks to IndexLayerClient by value, cache is
passed in OlpClientSettings. This aligns interface with read dataservice
API.
> Pass arguments to IndexLayerClient by value

- olp-cpp-sdk-dataservice-read/tests/ApiClientLookupTest.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- tests/common/mocks/NetworkMock.cpp
- tests/common/mocks/NetworkMock.h
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTestBase.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/IndexLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/VolatileLayerClientTest.cpp
Now ReturnHttpResponse is a free function that generates action for
mocked Send() method in NetworkMock.
> Move ReturnHttpResponse action out of NetworkMock

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClient.h
- olp-cpp-sdk-dataservice-write/src/StreamLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
Pass HRN, settings and callbacks to StreamLayerClient by value, cache is
passed in OlpClientSettings. This aligns interface with read dataservice
API.
> Pass arguments to StreamLayerClient by value

- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
Renamed the AuthenticationFunctionalTest from tests/functional/olp-cpp-sdk-authentication to AuthenticationClientTest
> Renamed AuthenticationFunctionalTest -> AuthenticationClientTest

- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
Added service parameter to DataRepository::GetDataBlob() to switch between blob and volatile-blob REST API
Adjusted tests to use blob service
Relates-to: OLPEDGE-760
> Added service parameter to DataRepository::GetBlobData()

- scripts/linux/fv/gitlab_test_fv.sh
Add more details in case of failure
Generate better data at the end of script
That info become more useful(with summarized data) when we receive failure emails from GitLab.
Resolves: OLPEDGE-473
> Improve FV test script

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClient.h
- olp-cpp-sdk-dataservice-write/src/AutoFlushController.cpp
- olp-cpp-sdk-dataservice-write/src/AutoFlushController.h
- olp-cpp-sdk-dataservice-write/src/StreamLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
- tests/common/testables/FlushEventListenerTestable.h
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
Removed next methods from StreamLayerClient:
- void Enable(std::shared_ptr<FlushListener> listener = nullptr);
- std::future<void> Disable();
- static std::shared_ptr<FlushListener> DefaultListener()
Also, disabled all the integration & functional tests which were using those API.
Relates to: OLPEDGE-825
> Removed Enable, Disable, DefaultListener from StreamLayerClient

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.h
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
Cancel pending requests when Versioned/Volatile/Index clients are destroyed.
Resolves: OLPEDGE-880
> Cancel pending requests when clients are destroyed.

- docs/dataservice-read-catalog-example.md
- docs/dataservice-write-example.md
- examples/dataservice-read/example.cpp
- examples/dataservice-write/example.cpp
- olp-cpp-sdk-authentication/include/olp/authentication/Settings.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenEndpoint.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
- tests/functional/olp-cpp-sdk-authentication/HereAccountOauth2ProductionTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteIndexLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientCacheTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
- tests/performance/CatalogClientTest.cpp
Remove old constructor in TokenProvider, because the constructed
authentication client had no network instance and is considered invalid.
Reorder members in Settings, first required then optional.
Update examples to reflect changes.
Update docs to reflect changes.
Relates-To: OLPEDGE-839
> Move credentials to authentication settings.

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/FlushEventListener.h
- olp-cpp-sdk-dataservice-write/src/DefaultFlushEventListener.cpp
- olp-cpp-sdk-dataservice-write/src/DefaultFlushEventListener.h
- tests/common/testables/FlushEventListenerTestable.h
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
- Removed the DefaultFlushEventListener from public API - now it resides  in dataservice-write/src folder.
- Updated the corresponding tests which were using this class.
Relates to: OLPEDGE-825
> Removed DefaultFlushEventListener from public API

- olp-cpp-sdk-authentication/include/olp/authentication/Settings.h
Added a missing AuthenticationCredentials.h include.
Relates-To: OLPEDGE-839
> Add missing include.

- olp-cpp-sdk-core/CMakeLists.txt
Added missing dependencies on system frameworks for iOS build when building with shared libraries turned on.
Relates to: OLPEDGE-532
> Added dependency on system frameworks for iOS build

- .travis.yml
- scripts/android/build.sh
Added build-in NDK instead of downloading full archive every time.
Documented by Google Travis build there: https://github.com/googlesamples/android-ndk/blob/master/.travis.yml
and https://stackoverflow.com/questions/47782349/ndk-cmake-and-android-in-travisci
Relates-To: OLPEDGE-784
> Improve Android build process on PSV

- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-core/include/olp/core/http/NetworkTypes.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- tests/functional/olp-cpp-sdk-core/NetworkTest.cpp
Renamed the SendOutcome::IsSuccessfull into SendOutcome::IsSuccessful.
Resolves: OLPEDGE-897
> Fixed typo in SendOutcome::IsSuccessful method

- olp-cpp-sdk-dataservice-read/src/repositories/ExecuteOrSchedule.inl
ExecuteOrSchedule() now has an overloaded function that takes only a
TaskScheduler pointer, rather than whole OlpClientSettings.
Resolves: OLPEDGE-902
> TaskScheduler-only variant of ExecuteOrSchedule

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientTest.cpp
- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
The class' GetData method is introduced.
It fetches data from a layer using a partition id or data handle.
The data is fetched asynchronously if the task scheduler is set
properly. The synchronous implementation of the logic is placed to
DataRepository::GetData() as it fits better from an architectural
point of view.
Resolves: OLPEDGE-759
> VersionedLayerClient class implementation

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
DataserviceRead's DataRequest, PartitionsRequest, PrefetchTilesRequest
now deprecates all members related to LayerId
Resolves: OLPEDGE-876
> Deprecation of WithLayerId/GetLayerId of requests

- scripts/linux/fv/olp-common.variables
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
Added missing initialization of auth settings to
DataserviceReadVersionedLayerClientTest
Relates-to: OLPEDGE-903
> Crash of versioned layer test fix

- scripts/linux/fv/olp-common.variables
- scripts/linux/fv/olp-cpp-sdk-functional-test.variables
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
All related environment variables required for
DataserviceReadVersionedLayerClientTest are now placed to
olp-dataservice-read-test.variables CI script.
Also these vars now has a unique prefix to avoid possible collisions
with other tests in 'read' suite.
Relates-to: OLPEDGE-907
> Dataservice-read's test variables arrangement

- examples/helpers/android/app/CMakeLists.txt.in
Fixed the Android examples, when they used the dynamic OLP libraries.
This fix basically introduces copying the shared libraries on POST_BUILD command.
Relates to: OLPEDGE-532
> Fix Android examples when used with built shared OLP libraries

- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Added export compile definitions (DATASERVICE_WRITE_LIBRARY and  DATASERVICE_WRITE_SHARED_LIBRARY) for dataservice-write.
This is required for successfully building the dataservice-write as a shared library
Relates to: OLPEDGE-532
> Added export compile definitions for dataservice-write

- olp-cpp-sdk-core/include/olp/core/client/ApiResponse.h
- olp-cpp-sdk-core/include/olp/core/client/Condition.h
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/client/ConditionTest.cpp
- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/PendingRequests.cpp
- olp-cpp-sdk-dataservice-read/src/PendingRequests.h
- olp-cpp-sdk-dataservice-read/src/TaskContext.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/TaskContextTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
Class take care of users callbacks, and make sure that client
callback is called exactly 1 time.
VolatileLayerClientImpl::GetData adapted to TaskContext usage
VersionedLayerClientImpl::GetData adapted to TaskContext usage
Resolves: OLPEDGE-909
> Add a task context class.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTileResult.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Implemented the VersionedLayerClient::PrefetchTiles method in dataservice-read component, which is based on the CatalogClient::PrefetchTiles implementation.
Also, moved the integration and functional tests regarding the pre-fetch functionality from CatalogClientTest with following changes:
- added DataserviceReadVersionedLayerClientTest.cpp file to integration tests target;
- removed the PrefetchEmbedded integration test from tests in DataserviceReadVersionedLayerClientTest test suite (see OLPEDGE-906);
- re-enabled the PrefetchBusy test in both CatalogClientTest and DataserviceReadVersionedLayerClientTest.
Relates to: OLPEDGE-795
> Added VersionedLayerClient::PrefetchTiles method

- olp-cpp-sdk-dataservice-write/src/StreamLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
If the user do not provide a default cache, SDK will create a default one.
Resolves: OLPEDGE-873
> Align cache according to requirements, dataservice write.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/src/CatalogClient.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.h
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTestBase.h
If the user do not provide a default cache, SDK will create a default one.
Remove CreateDefaultCache from CatalogClient.h
Changed CatalogClientImpl class constructor to take settings by value.
Resolves: OLPEDGE-872
Resolves: OLPEDGE-908
> Align cache according to requirements, dataservice read.

- examples/dataservice-write/example.cpp
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/FlushRequest.h
- olp-cpp-sdk-dataservice-write/src/AutoFlushController.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
- scripts/linux/psv/travis_test_psv.sh
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
Added the model::FlushRequest class, which manages the parameters for the customization of StreamLayerClient::Flush method calls.
+ re-enabled the StreamLayerClientCacheTest integration tests on PSV.
Relates to: OLPEDGE-826
> Added the FlushRequest class in StreamLayerClient's API

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
Remove olp namespace for parameters.
Align GetData implementation.
Align the order of parameters in DataRepository.
Relates-To: OLPEDGE-957
> Align VersionedLayerClient with VolatileLayerClient

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
GetData/Prefetch/GetPartitions in CatalogClient are marked as deprecated
and to be removed prior v1.0
Resolves: OLPEDGE-875
> Deprecate obsolete methods in CatalogClient

- .gitlab-ci.yml
- .travis.yml
- scripts/linux/fv/gitlab_build_fv.sh
- scripts/linux/fv/gitlab_test_fv.sh
- scripts/linux/psv/travis_build_psv.sh
- scripts/linux/psv/travis_test_psv.sh
For more crash backtraces in case of signal Aborted add SEGFAULT_SIGNALS = all for linux builds.
Tested and reproduced crash on Gitlab.
Relates-To: OLPEDGE-473, OLPEDGE-903, OLPEDGE-917
> Update FV test scripts. Add extra error logs into console of crashed test

- examples/dataservice-write/example.cpp
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClientSettings.h
- olp-cpp-sdk-dataservice-write/src/StreamLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientCacheTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientTest.cpp
Renamed the FlushSettings into StreamLayerClientSettings. Also, changed the order of parameters in StreamLayerClient.
Relates to: OLPEDGE-826
> Renamed the FlushSettings -> StreamLayerClientSettings

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.h
- scripts/linux/fv/olp-cpp-sdk-functional-test.variables
- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVolatileLayerClientTest.cpp
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
Added functional tests for VolatileLayerClient::GetPartitions()
Resolves: OLPEDGE-792
> Implemented VolatileLayerClient::GetPartitions() method

- olp-cpp-sdk-dataservice-read/src/PendingRequests.cpp
Introduce log in PendingRequests' CancelPendingRequests on timeout from
BlockingCancel
Relates-To: OLPEDGE-909
> Add log when BlockingCancel timeouts

- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVolatileLayerClientTest.cpp
Cleared all network pointers on test TearDown
Formatting fix
Resolves: OLPEDGE-970
> Fixed Functional tests for DatastoreRead VolatileClientTest

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- Implemented the PrefetchTiles method which returns CancellableFuture in the dataservice-read VersionedLayerClient class.
- aligned the API of PrefetchTiles methods with other methods;
- used the move semantics for the PrefetchTiles responses;
Relates to: OLPEDGE-958
> Implemented the PrefetchTiles with CancellableFuture in versioned client

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClientSettings.h
- olp-cpp-sdk-dataservice-write/src/AutoFlushSettings.h
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
Changed the type of StreamLayerClientSettings's maximum_requests property type from boost::optional to size_t.
Relates to: OLPEDGE-826
> Changed the type of StreamLayerClientSettings.maximum_requests

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
Add GetData and GetPartitions methods to VolatileLayerClient
that return CancellableFuture. Add tests.
Resolves: OLPEDGE-959
> Add CancellableFuture methods in VolatileLayerClient

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Implemented the GetData method which returns CancellableFuture in the dataservice-read VersionedLayerClient class.
Also, added integration tests.
Relates to: OLPEDGE-958
> Implemented the GetData with CancellableFuture in versioned client

- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Removed unused mocks from DataserviceReadVersionedLayerClientTest (integration test).
Relates to: OLPEDGE-795
> Removed unused mocks from VersionedLayerClientTest

- olp-cpp-sdk-dataservice-read/tests/TaskContextTest.cpp
Sometimes 0ms timeout is not enough, and test fails.
Resolves: OLPEDGE-989
> Fix a timeout in TaskContextTest.BlockingCancelIsWaiting test.

- olp-cpp-sdk-core/src/http/Network.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
NetworkCurl now has a configurable parameter in constructor for maximum
allowed requests. Any additional queued request produces
NETWORK_OVERLOAD_ERROR
Resolves: OLPEDGE-778
> Configurable max requests count for Curl

- olp-cpp-sdk-core/include/olp/core/http/HttpStatusCode.h
- olp-cpp-sdk-core/tests/olpclient/OlpClientTest.cpp
Error code from network code was lost in translation and if there's no
free handles client receives UnknownError. Now this error is propagated
to client as SlowDown error.
Relates-To: OLPEDGE-831
> Convert NETWORK_OVERLOAD_ERROR to SlowDown error

- external/CMakeLists.txt
- external/boost/CMakeLists.txt.boost.in
- external/googletest/CMakeLists.txt.googletest.in
- external/leveldb/CMakeLists.txt.leveldb.in
- external/rapidjson/CMakeLists.txt.rapidjson.in
Build of external dependencies is decoupled from main build script, so
that is not possible to share variables, other that separate
configuration stage. Substitution variables are used as means to pass
correct version.
Relates-To: OLPEDGE-221
> Add cmake target URL & HASH hook

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/IndexLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClient.h
Reviewed and modified comments to classes and methods in
IndexLayerClient.h and StreamLierClient.h to make sure that they are
written in accordance with the Here Style Guide and Doxygen
documentation requirements.
Relates-to: OLPEDGE-855
Signed-off-by: HalynaDumych <ext-halyna.dumych@here.com>
> Reviewed IndexLayerClient and StreamLayerClient

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-read/src/CatalogClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClient.cpp
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/CatalogClientTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientTest.cpp
Added unit tests to test that clients are movable at compile-time.
Relates-To: OLPEDGE-1014
> Make CatalogClient and LayerClients movable non-copyable

- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- olp-cpp-sdk-core/include/olp/core/generated/parser/JsonParser.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/tests/olpclient/OlpClientTest.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/BlobApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/ConfigApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/PlatformApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/ResourcesApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/VolatileBlobApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/BlobApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/ConfigApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/IndexApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/IngestApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/MetadataApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/PlatformApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/PublishApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/QueryApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/ResourcesApi.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationTestUtils.cpp
- tests/functional/olp-cpp-sdk-core/OlpClientDefaultAsyncHttpTest.cpp
The class now hold the stream to response data rather a string.
JsonParser.h extended with stream variant of the parser.
Resolves: OLPEDGE-684
> HttpResponse now holds data as a stream

- cmake/android/tester/CMakeLists.txt.in
- olp-cpp-sdk-authentication/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/tests/CMakeLists.txt
- tests/functional/CMakeLists.txt
- tests/integration/CMakeLists.txt
Fixed broken Android test runner because of invalid dependency on custom-params and incorrect setup of test library for Android test runner.
Relates to: OLPEDGE-788
> Fixed generating of Android test runner

- olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/client/TaskContextTest.cpp
- olp-cpp-sdk-dataservice-read/src/PendingRequests.cpp
- olp-cpp-sdk-dataservice-read/src/PendingRequests.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
Move TaskContext to core component and document public API. Will be used
by sync versions of Dataservice-write.
Relates-To: OLPEDGE-1006
> Move TaskContext to public API

- tests/functional/olp-cpp-sdk-authentication/AuthenticationProductionTest.cpp
- tests/functional/olp-cpp-sdk-authentication/HereAccountOauth2ProductionTest.cpp
AuthenticationProductionTest and HereAccountOauth2ProductionTest are now
use default settings for creating network handler. This allows the
library to avoid problems with multiple http requests at the same time
being discarded due to requests limit.
Relates-to: OLPEDGE-778
> Default network scheduler settings for tests

- olp-cpp-sdk-core/include/olp/core/client/PendingRequests.h
- olp-cpp-sdk-core/src/client/PendingRequests.cpp
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/client/PendingRequestsTest.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
Move PendingRequests to core component and fix document public API. Will
be used by sync versions of Dataservice-write.
Relates-To: OLPEDGE-1006
> Move PendingRequests to public API

- tests/performance/CMakeLists.txt
Disabled the performance tests for mobile platforms. This will fix the CMake setup errors while configuring iOS build.
Relates to: OLPEDGE-788
> Disabled the performance tests for iOS and Android

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Now tests are using shared pointer to promise to prevent crash on timeout while waiting result.
Increased result waiting timeout to 3 seconds.
Resolves: OLPEDGE-996
> Fixed Integration tests for VersionedLayerClient

- olp-cpp-sdk-core/src/http/android/HttpClient.java
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.h
Removed the `client_id` usage from `NetworkAndroid.cpp` and `HttpClient.java` files.
Also, removed `std::enable_shared_from_this` from `NetworkAndroid` inteface.
Relates to: OLPEDGE-735
> Removed client_id from NetworkAndroid and HttpClient

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
Capture copies of request, not references, which are modified on the
fly.
Relates-To: OLPEDGE-1002
> Fix data race in sync GetData methods

- CMakeLists.txt
- examples/dataservice-read/CMakeLists.txt
- examples/dataservice-write/CMakeLists.txt
- examples/helpers/ios/CMakeLists.txt.in
- external/boost/CMakeLists.txt.boost.in
- external/googletest/CMakeLists.txt.googletest.in
- external/rapidjson/CMakeLists.txt.rapidjson.in
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-authentication/tests/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/tests/CMakeLists.txt
- tests/common/CMakeLists.txt
- tests/functional/CMakeLists.txt
- tests/integration/CMakeLists.txt
- tests/performance/CMakeLists.txt
Update cmake_minimum_version to 3.9 in root CMakeLists. Remove version
check in non-root CMakeLists.
Resolves: OLPEDGE-361
> Align cmake_minimum_version to 3.9

- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.h
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTestBase.cpp
Add sync version of GetCatalog in CatalogRepository and port GetCatalog
from CatalogClient to use that version. Add default task scheduler for
tests.
Resolves: OLPEDGE-1002
> Add sync GetCatalog in CatalogRepository

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/src/CatalogClient.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.h
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
The new methods replace older GetCatalogMetadataVersion ones.
Resolves: OLPEDGE-1000
> CatalogClient now have GetLatestVersion methods

- olp-cpp-sdk-core/src/http/Network.cpp
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.h
Implemented maximum requests count limit for Android implementation of Network (NetworkAndroid).
Also fixed crash when NetworkAndroid was cancelling requests without callbacks on NetworkAndroid destruction.
Resolved: OLPEDGE-777
> Implemented custom requests limit for NetworkAndroid

- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
CatalogClientImpl now uses general TaskContext approach for querying
GetLatestVersion()
Relates-to: OLPEDGE-1001
> Utilization of sync GetLatestVersion

- olp-cpp-sdk-core/src/http/Network.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.h
NetworkWinHttp now has a configurable parameter in constructor for maximum
allowed requests. Any additional queued request produces
NETWORK_OVERLOAD_ERROR
Resolves: OLPEDGE-779
> Configurable max requests count for WinHttp

- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- scripts/linux/fv/olp-cpp-sdk-functional-test.variables
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVolatileLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/HttpResponses.h
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
Implement sync GetVolatilePartitions on top of GetPartitions::PartitionRepository.
Fix functional test to use volatile layer. Fix disabled integration test.
Resolves: OLPEDGE-1004
> Add sync GetPartitions in VolatileLayerClient

- olp-cpp-sdk-core/src/cache/InMemoryCache.cpp
- olp-cpp-sdk-core/src/cache/InMemoryCache.h
- olp-cpp-sdk-core/tests/cache/InMemoryCacheTest.cpp
Adapts most of the internals of the InMemoryCache to the coding style.
Also removes static methods from InMemoryCache and replaces them with
nested structures to be used by the LRUCache and time provider default
parameter values. Add mutex lock for Size() method.
Promote private members to protected to be able to test via testable.
Adapts unit tests to coding style.
Relates-to: OLPEDGE-566
> Adapts InMemoryCache class to coding style.

- examples/dataservice-read/example.cpp
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/src/CatalogClient.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.h
- olp-cpp-sdk-dataservice-read/src/PrefetchTilesProvider.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/performance/CatalogClientTest.cpp
Add includes, that are mandatory for non-trivial class usage. Remove
redundant includes from examples and tests. Remove redundant forward
declarations.
Relates-To: OLPEDGE-798
> Clean up CatalogClient

- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientCacheTest.cpp
Add Volatile* and VersionedLayerCacheTest. Remove CatalogClientCacheTests
which use deprecated API.
Relates-To: OLPEDGE-1015
> Separate CatalogClientCacheTest

- olp-cpp-sdk-core/cmake/ios.cmake
Using CMAKE_CURRENT_SOURCE_DIR instead of CMAKE_CURRENT_LIST_DIR
will not provide the full path to the iOS src files.
Resolves: OLPEDGE-1067
> Fix wrong include path for iOS HTTP layer.

- tests/functional/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
> Fixed crash in CatalogClientTest.GetPartitionsWithInvalidHrn

- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
Crash was due to unchecked access to pointer. Add asserts to guard
pointer access.
Resolves: OLPEDGE-1054
> Add asserts on nullptr

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/src/CatalogClient.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.h
Remove deprecated method GetData from CatalogClient
Relates-To: OLPEDGE-984
> Remove deprecated CatalogClient::GetData

- olp-cpp-sdk-authentication/src/AutoRefreshingToken.cpp
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
Add check for for online error in AutoRefreshingToken. Add log for such
case with http status, error code and message. Add test.
Relates-To: OLPEDGE-1025
> Add log on error when Autorefreshing token

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
- olp-cpp-sdk-dataservice-read/src/PrefetchTilesProvider.cpp
- olp-cpp-sdk-dataservice-read/src/PrefetchTilesProvider.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
Pass layer_id in constructors of Repositories, or pass as argument from
repositories. Pass layer_id as parameter for key generation and as
explicit parameter in cache operations.
Relates-To: OLPEDGE-984
> Remove usage of deprecated GetLayerId

- olp-cpp-sdk-core/include/olp/core/client/ApiResponse.h
- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.h
- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.inl
- olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
- olp-cpp-sdk-core/tests/client/TaskContextTest.cpp
Allows injecting CancellationContext into TaskContext so that we can
share a single CancellationContext for multiple tasks. This is mandatory
for the PrefetchTiles where one CancellationToken, resp. CancellationContext,
is handed over to the caller and should be able to cancelled all scheduled
tasks.
Changes ApiResponse from const reference on the ResultType to by copy passing
so that we can move effectively OLP responses.
Modifies CancellationContext::ExecuteOrCancelled() to return bool denoting
if operation was successfully executed or cancelled.
Relates-to: OLPEDGE-1005
> Small changes needed for VersionedLayerClient::PrefetchTiles.

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
> NetworkCurl now uses RequestId in RequestHandle

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Curl may raise SIGPIPE in few situations. Add option for curl to not
use any signal logic. Add signal mask to ignore situation, where SIGPIPE
may be raised as result of write in closed socket. Remove check for
Threads on cmake, as Threads are required.
Relates-To: OLPSUP-8508
> Add CURLOPT_NOSIGNAL options to Curl easy handles

- tests/performance/MemoryTest.cpp
> Fix the lifetime of the VersionedLayerClient in performance test

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
The crash happens when the request is canceled in the middle, and the handle is already reset.
Resolves: OLPEDGE-1098
> Fix a crash in WinHttp client

- tests/performance/CMakeLists.txt
- tests/performance/MemoryTest.cpp
- tests/performance/NetworkWrapper.h
Node server s limited to http, and to run performance tests code should
be modified accordingly. Wrapper alter ongoing requests to use http.
Relates-To: OLPEDGE-1050
> Add network wrapper for performance test

- docs/GettingStartedGuide.md
Installation details should be taken into account when integrating
SDK into a project, to reflect that add reference to readme, where
installation process is described.
Relates-To: OLPEDGE-1080
> Add reference to installation process in GettingStarted.md

- olp-cpp-sdk-core/include/olp/core/client/PendingRequests.h
- olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
- olp-cpp-sdk-core/src/client/PendingRequests.cpp
- olp-cpp-sdk-core/tests/client/PendingRequestsTest.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
Made PendingRequests::CancelPendingRequests() to first cancel all requests then check for completion
Now ErrorCode::RequestTimeout is propagated properly to user
Resolves: OLPEDGE-678
> Fixed test CancelPendingRequestsCatalog

- docs/dataservice-read-catalog-example.md
Change `catalog metadata` to `catalog configuration`. Reflect api changes
in CatalogClient documentation. Add mentions of VersionLayerClient, where
it used: retrieve partitions metadata and retrieve data.
Resolves: OLPEDGE-1070
> Align dataservice-read-catalog-example.md with latest changes

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Add Add CancelPendingRequests in VersionedLayerClient and provide it
implementation. Enable test DataserviceReadVersionedLayerClientTest.CancelPendingRequestsPartitions.
Resolves: OLPEDGE-1093
> Add CancelPendingRequests in VersionedLayerClient

- tests/performance/MemoryTest.cpp
- tests/performance/NetworkWrapper.h
- tests/utils/olp_server/errors_generator.js
- tests/utils/olp_server/server.js
Add emulation of errors and timeouts for mock server. This behavior is
controlled by 'debug' header in http requests. Network wrapper for
performance test implements interface to set this header.
Relates-To: OLPEDGE-1115
> Add errors and timeouts to mock server

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- tests/performance/MemoryTest.cpp
Add 1 second timeout in performance test. Add log when wait on condition
is timeouted.
Relates-To: OLPEDGE-1133
> Add timeout in performance test and add log on timeout error

- .gitlab-ci.yml
Add check for file exist. It will exist only if NV pipeline started.
FV should skipp that step.
Relates-To: OLPEDGE-746
> Fix FV pipeline failure due to file not found

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
- scripts/linux/nv/gitlab_test_valgrind.sh
Add echo about last return code for debug online tests
Relates-to: OLPEDGE-1144
> Add fix to retry mechanism for NV/FV online tests.

- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
Refactored the assertion about waiting for the successful result of GetBatch response in functional tests. Now we only check whether the GetBatch response from serve was either 'submitted' or 'succeeded'. We can't rely on the continuous waiting for the 'succeeded' state as it might not be finished in a determined way.
Resolves: OLPEDGE-708
> Refactored assertion about GetBatch successful response in tests

- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
Fix occurred due to missing cache.
Resolves: OLPEDGE-1153
> Fix a crash in ApiTests

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
- scripts/linux/fv/gitlab_test_fv.sh
- scripts/linux/nv/gitlab_test_valgrind.sh
Retry will run only for return code 1. Means will run only in gtest failure. Crashes will not be retried.
Also changed order FV test groups running.
Relates-to: OLPEDGE-1144
> Modify retry mechanism for NV/FV online tests

- olp-cpp-sdk-core/include/olp/core/client/PendingRequests.h
- olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
Add exports for classes to fix Windows exports in dynamic libraries.
Resolves: OLPEDGE-1159
> Add CORE_API macro for TaskContext and PendingRequests

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
Fix a scenario when the network is destroyed and user callback is not triggered.
Resolves: OLPEDGE-1160
> Fix a scenario when network do not trigger user callback 

- docs/GettingStartedGuide.md
- docs/dataservice-write-example.md
Modified the following files:
* dataservice-write-example.md - corrected punctuation, changed
"e.g." to "for example", and corrected structure of several sentences
* GettingStartedGuide.md - fixed broken links, corrected structure of
several sentences, and added missing punctuation
Relates-to: OLPEDGE-1158
> Fixed broken links, modified punctuation

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
- scripts/linux/fv/gitlab_test_fv.sh
- scripts/linux/nv/gitlab_test_valgrind.sh
Changed way we call retry in shell
Relates-to: OLPEDGE-1144
> Fix retry mechanism in FV/Nv online tests

- README.md
Remove 'work-in-progress'. Align used build commands from 'make'
to more generic 'cmake --build'.
Resolves: OLPEDGE-1082
> Remove 'work-in-progress' and align build commands style

- olp-cpp-sdk-dataservice-write/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-write/src/ApiClientLookup.h
- olp-cpp-sdk-dataservice-write/tests/ApiClientLookupTest.cpp
- olp-cpp-sdk-dataservice-write/tests/CMakeLists.txt
Implemented the sync version of ApiClientLookup::LookupApiClient in dataservice-write component in the same way it is done in dataservice-read component.
Also, covered this new function with unit tests.
Relates to: OLPEDGE-1103
> Added sync version of LookupApiClient in dataservice-write

- olp-cpp-sdk-dataservice-write/src/generated/BlobApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/BlobApi.h
- olp-cpp-sdk-dataservice-write/src/generated/ConfigApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/ConfigApi.h
- olp-cpp-sdk-dataservice-write/src/generated/IngestApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/IngestApi.h
- olp-cpp-sdk-dataservice-write/src/generated/PublishApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/PublishApi.h
Remove non-used CancellableFuture APIs.
Relates-To: OLPEDGE-1010
> Remove unused API from BlobAPI, ConfigAPI, IngestAPI and PublishAPI.

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
- scripts/linux/fv/gitlab_test_fv.sh
Retry works, but gitlab-olp-cpp-sdk-functional-test.sh returns 0 not always when tests succeded, so retry work till the end of retry limit and does not end on success
Relates-to: OLPEDGE-1144
> Add improvement to retry mechanism for exit when success

- docs/GettingStartedGuide.md
In the **Get Creadentials** section, changed "Typescript" to "C++".
Relates-to: OLPEDGE-1172
> Corrected a typo

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
Functional tests were exited with error code from last command which is `wait`
Add exit with correct exit code for futher handling in retry mechanism.
Resolves: OLPEDGE-1144
> Fix incorrect exit code in functional test FV script

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Add static cast to size_t of unsigned constant inside ::max. Currently
cpp doesn't have built-in literal fir size_t type.
Relates-To: OLPSUP-8752
> Fix 32-bit build, by using same types inside ::max

- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientCacheTest.cpp
- tests/performance/MemoryTest.cpp
* Add disk_path_mutable.
* Deprecate the disk_path in favor of a new disk_path_mutable.
* Update the SDK to use a new disk_path_mutable.
* When disk_path_mutable is empty, disk_path is used (backwards compatibility).
Resolves: OLPEDGE-1039
> Update CacheSettings structure.

- scripts/linux/fv/gitlab_test_fv.sh
- scripts/linux/nv/gitlab_test_valgrind.sh
Currently functional tests run twice every time on NV because condition absent.
Added more comments, added set +x to avoid dirty output at the end on logs.
Relates-To: OLPEDGE-1144
> Add condition to run retry in functional NV scripts

- olp-cpp-sdk-core/include/olp/core/client/OlpClient.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/tests/olpclient/OlpClientTest.cpp
Add sync OlpClient::CallApi and cover it with same suite as
async CallApi:
- add testable polymorphic CallApi wrapper
- add parametric tests over polymorph CallApi
Relates-To: 1168
> Implement Sync CallApi in OlpClient

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
- scripts/linux/fv/gitlab_test_fv.sh
Result variable was storing last failure so not needed for next retry in case we got 0.
Fix minor echo messages for first run of test.
Relates-To: OLPEDGE-1144
> Add small fix to retry mechanism for exit on success

- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
The new option is required for configuring a path to the protected cache.
This cache is meant to be read-only and is the primary cache for lookups.
If the path is not set the protected cache is not expected to be used.
Resolves: OLPEDGE-1194
> Added protected cache path option to olp::cache::CacheSettings

- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
Added sleep after DeleteUser call in authentication tests to
prevent server error when signin to deleted user to check that
it has been deleted.
Resolves: OLPEDGE-799
> Added sleep after DeleteUser() call in authentication tests

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
- scripts/linux/fv/gitlab_test_fv.sh
Bug reproduced only on CI when sometimes functional tests run in infinite loop in FV pipelines.
Removed export as it's not needed and causing issue when retry happens.
Decreased retry count limit to 2.
Resolves: OLPEDGE-1245
> Fix bash retry mechanism bug when loop becomes infinite

- olp-cpp-sdk-dataservice-read/src/generated/api/ConfigApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/ConfigApi.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
Replaced the async ConfigApi::GetCatalog method with synchronous version.
Relates-to: OLPEDGE-1189
> Replaced async version of ConfigApi::GetCatalog with sync

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Due to some errors were returned by curl/network that were not
covered in text and sometimes returned by server. This change
will print actual status code to log to improve further debugging
of unexpected messages that may be returned by server.
Relates-to: OLPEDGE-1215
> Added http status logging to curl request complete messages

- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
Replaced the async QueryApi::GetPartitionsbyId and QueryApi::QuadTreeIndex methods with synchronous version.
Relates-to: OLPEDGE-1191
Signed-off-by: Kuchma, Mykhailo <ext-mykhailo.kuchma@here.com>
> Replaced async version of dataservice-read QueryApi with sync

- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
- tests/performance/MemoryTest.cpp
Attempt to initiate the protected cache if CacheSettings::disk_path_protected
is provided. Returns OpenDiskPathFailure if the provided path is incorrect.
Added tests to cover the protected cache initializing.
Resolves: OLPEDGE-1041
> Added a protected disk cache instance to DefaultCache

- scripts/linux/fv/gitlab-olp-cpp-sdk-core-test.sh
- scripts/linux/nv/gitlab_test_valgrind.sh
DefaultCacheTest.BadPathMutable(initially DefaultCacheTest.BadPath) was already in black list
but this has been lost after its renaming. Restoring.
Resolves: OLPEDGE-1266
> Added DefaultCacheTest.BadPathMutable to black list.

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/PlatformApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/PlatformApi.h
- olp-cpp-sdk-dataservice-read/src/generated/api/ResourcesApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/ResourcesApi.h
- olp-cpp-sdk-dataservice-read/src/generated/api/VolatileBlobApi.cpp
Adapt implementation to use sync CallApi of OlpClient. Fix code style.
Relates-To: OLPEDGE-1168
> Adapt Lookup API to sync CallApi of OlpClient

- olp-cpp-sdk-dataservice-read/src/generated/api/BlobApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/BlobApi.h
- olp-cpp-sdk-dataservice-read/src/generated/api/VolatileBlobApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/VolatileBlobApi.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
Adapt implementation to use sync CallApi of OlpClient. Fix tests to use
fixed Blob api. Fix code style.
Relates-To: OLPEDGE-1168
> Adapt Blob API to sync CallApi of OlpClient

- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
Fix flaky tests in dataservice-write versioned and volatile layer clients.
* Added a sleep between retry.
* Reverted the assert back, to mark the right test as failed.
Resolves: OLPEDGE-708
> Fix flaky tests in dataservice write versioned and volatile layer

- codecov.yml
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
1. Removed next dataservice-write heders and sources from compilation and codecov:
- AutoFlushController.h/cpp;
- AutoFlushSettings.h
- BackgroundTaskCollection.h/cpp
- DefaultFlushEventListener.h/cpp
- FlushEventListener.h
- FlushMetrics.h
2. Replaced GLOB with explicitly specifying the headers and source files in dataservice-write/CMakeLists.txt.
Relates-to: OLPEDGE-1211
> Removed unused dataservice-write files from compilation and codecov

- olp-cpp-sdk-dataservice-write/src/generated/ConfigApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/ConfigApi.h
Added the sync version of dataservice-write ConfigApi::GetCatlog method.
Tested only with custom functional tests. Unit tests will be provided once we will find a common ground with unit testing of generated API.
Relates to: OLPEDGE-1267
> Added sync version of dataservice-write ConfigApi::GetCatalog

- olp-cpp-sdk-dataservice-write/src/generated/IngestApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/IngestApi.h
Implemented sync version of IngestApi::IngestData in dataservice-write component. No tests for now. Note, that after we finish with switching the StreamLayerClientImpl to SyncApi, the async version of IngestApi::IngetData should be removed.
Relates-to: OLPEDGE-1268
> Added sync version of IngestApi::IngestData in dataservice-write

- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
Protected cache should be checked before mutable cache.
Added test to cover that.
Resolves: OLPEDGE-1040
> Added protected cache usage in DefaultCache::Get method

- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
> Mark TokenProvider class as deprecated.

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
Disable warnings for all current usages.
Deprecated methods:
Constructor
SetNetworkProxySettings
SetNetwork
SetTaskScheduler
Relates-To: OLPEDGE-1259
> Mark methods in Authentication client as deprecated.

- olp-cpp-sdk-authentication/include/olp/authentication/AutoRefreshingToken.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenEndpoint.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenRequest.h
- olp-cpp-sdk-authentication/src/AutoRefreshingToken.cpp
- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
Disable warnings for all current usages of TokenRequest.
Relates-To: OLPEDGE-1263
> Mark TokenRequest class as deprecated. 

- olp-cpp-sdk-core/include/olp/core/client/Condition.h
Fixed the data race in the Condition class, which occurred while running the dataservice-read unit tests.
Looks like the issue was that the waiting thread was spuriously woke up right before the condition is about to be signaled, but after the `Condition::signaled_` var is set to `true`.
This happened because the `std::conditional_variable::notify_one` on the condition wasn't under the `std::lock_guard`. After the execution was returned to the signaling thread, the `condition_` might be dead, as in the example with OlpClient::SendRequest. So, we have to make sure that access to condition_ and signaled_ are always protected with same mutex.
Alternatively, we could rewrite the `Condition` class usage via std::make_shared<> instead using the local variable - see OlpClient::SendRequest and …
> Fixed the data race in the Condition class

- examples/dataservice-read/example.cpp
- olp-cpp-sdk-authentication/src/AutoRefreshingToken.cpp
- olp-cpp-sdk-core/include/olp/core/client/ApiResponse.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-write/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
Internal code was addapted to use MoveResult function instead GetResult.
Reduced unnesesary object copying, where it is possible.
Relates-To: OLPEDGE-1110
> Add MoveResult function for ApiResponse.

- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/tests/StreamLayerClientImplTest.cpp
1. Implemented the sync version of PublishDataLessThanTwentyMib in dataservice-write::StreamLayerClientImpl class, which uses sync generated API (ConfigApi and IngestApi).
2. Also, added 'unit tests' to the StreamLayerClientTest.cpp regarding this function. I suggest to move those tests to `integration` tests component, once we will finish moving of `PublishData` method to the sync API.
3. Added StreamLayerClientImpl::FindContentTypeForLayerId with catalog as a parameter.
Relates-to: OLPEDGE-1181
> Implemented the sync version of PublishDataLessThanTwentyMib

- olp-cpp-sdk-dataservice-write/src/generated/BlobApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/BlobApi.h
Implemented the synchronous version of BlobApi::PutBlob method, which is required for the sync version of StreamLayerClientImpl::InitPublishDataGreaterThanTwentyMib.
No tests for now (in future will be added).
Relates-to: OLPEDGE-1182
> Implemented the sync version of BlobApi::PutBlob

- olp-cpp-sdk-dataservice-write/src/generated/PublishApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/PublishApi.h
Implemented the next synchronous PublishApi methods required for the StreamLayerClient:
- InitPublication;
- UploadPartitions;
- SubmitPublication.
No tests for now.
Relates-to: OLPEDGE-1182
> Implemented the sync PublishApi required for StreamLayerClient

- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/tests/StreamLayerClientImplTest.cpp
- Implemented the sync version of PublishDataGreaterThanTwentyMib in StreamLayerClientImpl. Added tests for success and failure cases, which would cover the sync PublishApi and BlobApi
- Moved GeneratedUuid method from anonymous namespace to the virtual protected method, so it can be mocked;
- improved logging;
Relates-to: OLPEDGE-1182
> Implemented the sync version of PublishDataGreaterThanTwentyMib

- docs/dataservice-read-catalog-example.md
Changed "authentification" to "authentication".
Relates-to: OLPEDGE-1323
> Fix a typo in dataservice-read-catalog-example.md

- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientTest.cpp
1. Implemented the StreamLayerClientImpl::PublishData to use the sync API methods:
- PublishDataLessThanTwentyMibSync;
- PublishDataGreaterThanTwentyMibSync;
2. Switched the public PublishData API and tests to use those new methods.
3. Renamed old versions of PublishData into PublishDataOld
Relates-to: OLPEDGE-1183
> Implemented StreamLayerClientImpl::PublishData that uses sync API

- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/tests/StreamLayerClientImplTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
Switched the StreamLayerClientImpl::Flush method to use new sync PublishDataTask API.
Also, fixed the integration tests to reorder them according to new sync API design.
Relates-to: OLPEDGE-1184
> Switched the StreamLayerClientImpl::Flush to use PublishDataTask

- olp-cpp-sdk-core/include/olp/core/geo/coordinates/GeoPoint.h
Added missing information and comments to the `GeoPoint` class
documentation.
Relates-to: OLPSUP-7192
> Extend documentation (`GeoPoint`)

- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/tests/StreamLayerClientImplTest.cpp
- Renamed the PublishDataLessThanTwentyMibSync and PublishDataGreaterThanTwentyMibSync method into respectively PublishDataLessThanTwentyMib and PublishDataGreaterThanTwentyMib.
- changed signature of PublishData... methods.
Relates-to: OLPEDGE-1185
> Renamed PublishData... methods in StreamLayerClientImpl

- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
Relates-To: OLPEDGE-1258
This reverts commit d166fb86fe86c1d22005cd42c8efcdfce4bf0fc4.
> Revert "Mark TokenProvider class as deprecated."

- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/logging/ConfigurationTest.cpp
- olp-cpp-sdk-core/tests/logging/MockAppender.cpp
- olp-cpp-sdk-core/tests/logging/MockAppender.h
Introducing MockAppender that will be used for testing
this and other logging classes.
Signed-off-by: Kirill Zhuchkov <643378+r0busta@users.noreply.github.com>
> Add unit tests for olp::logging::Configuration class

- olp-cpp-sdk-authentication/include/olp/authentication/SignInResult.h
- olp-cpp-sdk-authentication/src/SignInResult.cpp
- olp-cpp-sdk-authentication/src/SignInResultImpl.cpp
- olp-cpp-sdk-authentication/src/SignInResultImpl.h
- olp-cpp-sdk-authentication/tests/CMakeLists.txt
- olp-cpp-sdk-authentication/tests/SignInResultImplTest.cpp
- scripts/linux/fv/olp-common.variables
Now ClientId that is associated with access token can be
retrieved using SignInResult::GetClientId() method
Resolves: OLPEDGE-1287
> Added parsing of Client Id from Access Token

- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/logging/DisabledLoggingTest.cpp
**Test logging with the OLP_SDK_LOGGING_DISABLED flag**
> Test logging with the OLP_SDK_LOGGING_DISABLED flag

- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/logging/FileAppenderTest.cpp
**Add tests for the olp::logging::FileAppender class**
> Add tests for the olp::logging::FileAppender class

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/StreamLayerClient.h
- olp-cpp-sdk-dataservice-read/src/StreamLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.h
StreamLayerClient provides the ability to consume data from a stream layer
in real-time. The client reads the data in the order it is added to the
queue. Once it reads the data, the data is no longer available to
that client, but the data remains available to other clients.
The StreamLayerClient is movable-only since each client is distinguished by
the back-end by its personal ID (consumerID) which is required to be unique within
the same group (the consumer group).
Resolves: OLPEDGE-1349
> Add StreamLayerClient and StreamLayerClientImpl skeletons

- olp-cpp-sdk-core/include/olp/core/generated/parser/ParserWrapper.h
- olp-cpp-sdk-core/include/olp/core/generated/serializer/SerializerWrapper.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/StreamOffsets.h
- olp-cpp-sdk-dataservice-read/src/generated/parser/StreamOffsetParser.cpp
- olp-cpp-sdk-dataservice-read/src/generated/parser/StreamOffsetParser.h
- olp-cpp-sdk-dataservice-read/src/generated/serializer/StreamOffsetsSerializer.cpp
- olp-cpp-sdk-dataservice-read/src/generated/serializer/StreamOffsetsSerializer.h
Models were generated using Swagger from OLP Stream API v2 and adapted
to be consistent with existing models for other layers and with Stream
Layer Client Detailed Design proposal.
Relates-To: OLPEDGE-1196
> Add StreamOffset and StreamOffsets models for Stream Api

- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/logging/FilterGroupTest.cpp
**Add tests for the olp::logging::FilterGroup class**
> Add tests for the olp::logging::FilterGroup class

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataServiceReadApi.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
Most of the dataservice-read request classes are not fully implemented
using the Google coding style. This commit adapts them and also removes
some unused variables.
Relates-to: OLPEDGE-1366
> Adapt dataservice-read request classes to coding style.

- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/logging/FormatTest.cpp
**Add tests for the olp::logging::Format format methods**
> Add tests for the olp::logging::Format format methods

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/ConsumerProperties.h
- olp-cpp-sdk-dataservice-read/src/generated/serializer/ConsumerPropertiesSerializer.h
This class holds Kafka consumer properties to be passed to
the OLP Stream API.
Relates-To: OLPEDGE-1370
> Add ConsumerProperties class for Stream API

- olp-cpp-sdk-dataservice-read/src/generated/model/SubscribeResponse.h
- olp-cpp-sdk-dataservice-read/src/generated/parser/SubscribeResponseParser.cpp
- olp-cpp-sdk-dataservice-read/src/generated/parser/SubscribeResponseParser.h
Holds subscription info to use to pass further requests to the OLP
stream layer.
Relates-To: OLPEDGE-1373
> Add SubscribeResponse model for Stream API

- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
- Changed the implementation of StreamLayerClient::Flush in a way to support client::TaskContext and pending requests. This is required in order to properly cancel all the scheduled Flush operations when client is destroyed. Also, this will allow user to cancel pending Flush requests via public CancelPendingRequests method;
- re-enabled FlushDataCancel tests;
- removed std::enable_shared_from_this from StreamLayerClientImpl, because all scheduled async operations using client instance will be cancelled and finished in StreamLayerClientImpl' dtor.
Relates-to: OLPEDGE-1184
> Implemented the StreamLayerClient::Flush via TaskContext

- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/logging/LogTest.cpp
**Add tests for the olp::logging::Log class**
> Add tests for the olp::logging::Log class

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/ConsumerProperties.h
- olp-cpp-sdk-dataservice-read/src/generated/api/StreamApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/StreamApi.h
- olp-cpp-sdk-dataservice-read/src/generated/serializer/ConsumerPropertiesSerializer.h
Will be used by StreamLayerClient to interact with OLP Stream Layer.
Contains only Subscribe and DeleteSubscription calls for now.
Relates-To: OLPEDGE-1196
> Add Stream API for reading

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClient.h
- olp-cpp-sdk-dataservice-write/src/StreamLayerClient.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientTest.cpp
Implemented CancelPendingRequests method to a StreamLayerClient with corresponding tests.
This will help users to cancel all the on-going requests without destroying instance of the client.
Resolves: OLPEDGE-975
> Add a public CancelPendingRequests method to a StreamLayerClient

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/IndexLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-write/src/IndexLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.h
Implemented CancelPendingRequests in the public API of next dataservice-write clients:
- IndexLayerClient;
- VolatileLayertClient;
- VersionedLayerClient.
This was done in order to not confuse readers with slightly incorrect previous naming.
Note that current implemenatation uses `CancelAll()` method until all these clients will be moved to the tasks approach.
Relates-to: OLPEDGE-1361
> Added CancelPendingRequests to dataservice-write clients

- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
DiskCache was not fully compliant with the coding style.
This commit applies the coding style on this class with several
paramters name chaning and methods renaming, including public API.
Class is private and only visible to DefaultCache so no API break expected.
Also improved the doxygen comments.
Relates-to: OLPEDGE-566
> Adapts DiskCache class to coding style.

- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/include/olp/core/cache/KeyValueCache.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCacheSizeLimitEnv.cpp
- olp-cpp-sdk-core/src/cache/DiskCacheSizeLimitEnv.h
- olp-cpp-sdk-core/src/cache/DiskCacheSizeLimitWritableFile.cpp
KeyValueCache is now optimized with some aliases to be also used above
by parent class and users. DefaultCache is now marking overriden methods
from KeyValueCache with the override keyword. DiskCacheSizeLimitEnv and
DiskCacheSizeLimitWritableFile are also adapted where needed to coding style.
Relates-to: OLPEDGE-566
> Adapt DefaultCache and other cache files to coding style.

- olp-cpp-sdk-dataservice-read/src/generated/api/StreamApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/StreamApi.h
Will be used by StreamLayerClient to interact with OLP Stream Layer.
The only difference of these methods is the URI endpoint. So the logic
is extracted to one private method.
Relates-To: OLPEDGE-1196
> Add CommitOffsets and SeekToOffset public methods to the read StreamApi

- olp-cpp-sdk-core/include/olp/core/client/ApiError.h
- olp-cpp-sdk-core/include/olp/core/client/ApiResponse.h
- olp-cpp-sdk-core/include/olp/core/client/CancellationToken.h
- olp-cpp-sdk-core/include/olp/core/client/ErrorCode.h
- olp-cpp-sdk-core/src/client/CancellationToken.cpp
Some of the most commonly used olp::client namespace classes
are now aligned with the coding style. This also enhances doxygen
documentation, introduces some usefull aliases.
Additionally this alters ApiError and CancellableFuture constructors
to use pass by value for efficient moving instead of by reference.
Relates-to: OLPEDGE-567
> Adapts part of the olp::client classes to coding style.

- olp-cpp-sdk-dataservice-read/src/generated/api/StreamApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/StreamApi.h
Will be used by StreamLayerClient to get data messages from OLP Stream
Layer.
Relates-To: OLPEDGE-1196
> Add ConsumeData public method to the read StreamApi

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/StreamLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/src/StreamLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/tests/StreamLayerClientImplTest.cpp
Unsubscribe is used for disabling the consumption from the specific stream layer.
The result of successful unsubscribe operation is subscriptionID of the delete subscription.
If unsubscribe operation succeeds the client's internal state (related to subscription) is repealed.
Relates-To: OLPEDGE-1351
> Add StreamLayerClient Unsubscribe method

- olp-cpp-sdk-dataservice-read/src/generated/parser/MessagesParser.cpp
- olp-cpp-sdk-dataservice-read/tests/ParserTest.cpp
Add unit tests covering parse of Metadata, StreamOffset, Message classes (MessageParser.h) and SusbscribeResponse class.
Relates-to: OLPEDGE-1385
> Add unit tests for MessagesParser and SubscribeResponseParser

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/StreamLayerClient.h
- olp-cpp-sdk-dataservice-read/src/StreamLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.h
GetData will be used for download the data for the messages that does
not include the data embedded, but includes a data handle and the data
size greater than 1 MB.
Resolves: OLPEDGE-1354
> Add StreamLayerClient GetData method

- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
Fix the DefaultCache::Put behavior when the value does not fit in-memory cache
When the value does not fit the in-memory cache, it still cached on disk.
Resolves: OLPSUP-9206
> Fix the DefaultCache::Put behavior

- olp-cpp-sdk-dataservice-write/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-write/src/generated/PlatformApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/PlatformApi.h
- olp-cpp-sdk-dataservice-write/src/generated/ResourcesApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/ResourcesApi.h
- olp-cpp-sdk-dataservice-write/tests/StreamLayerClientImplTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientCacheTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientTest.cpp
1. Adds the synchronous version of the ResourcesApi and PlatformApi.
2. Refactor the ApiClientLookup::LookupApiClient to use sync ResourceApi and PlatformApi. This will ease supporting of the API lookup code and will eventually get rid of static network in the tests.
3. Add assertion on leaked network and task scheduler in DataserviceWriteStreamLayerClientTest.
Relates-to: OLPEDGE-1331, OLPEDGE-1424
> Refactor the ApiClientLookup::LookupApiClient to use synchronous API

- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.h
- olp-cpp-sdk-core/include/olp/core/client/Condition.h
- olp-cpp-sdk-core/include/olp/core/client/HRN.h
- olp-cpp-sdk-core/src/client/HRN.cpp
- olp-cpp-sdk-core/src/client/Tokenizer.h
This commit adapt the above mentioned classes the the coding style,
also marks the public members of HRN as deprecated and to be
scoped to private by 05.2020 as it is not recommended by HERE Platform
to interpret the HRN in any way. Users should only use the public methods
available and not care about the composition of the HRN string.
Relates-to: OLPEDGE-567
> Adapts HRN, CancellationContext and Condition to coding style.

- olp-cpp-sdk-dataservice-read/tests/SerializerTest.cpp
Add units tests for StreamOffsetsSerializer and ConsumerPropertiesSerialzer.
Relates-to: OLPEDGE-1385
> Add unit tests for StreamOffsets and ConsumerProperties serializers

- olp-cpp-sdk-authentication/include/olp/authentication/TokenResult.h
- olp-cpp-sdk-authentication/src/SignInResultImpl.cpp
- olp-cpp-sdk-authentication/src/TokenResult.cpp
* Change copy constructor to default in TokenResult because it
was the same.
* Fixed functional tests for AutoRefreshingToken.
Resolves: OLPEDGE-1494, OLPEDGE-837
> Change copy constructor to default in TokenResult

- olp-cpp-sdk-authentication/include/olp/authentication/SignInResult.h
- olp-cpp-sdk-authentication/src/SignInResult.cpp
- olp-cpp-sdk-authentication/src/SignInResultImpl.cpp
- olp-cpp-sdk-authentication/src/SignInResultImpl.h
- olp-cpp-sdk-authentication/tests/CMakeLists.txt
- scripts/linux/fv/olp-common.variables
This reverts commit 7dc665f.
* Due to new proper method of getting client id this change is
removed. New public api call to get client id will be
introduced
> Revert "Added parsing of Client Id from Access Token"

- olp-cpp-sdk-core/src/client/OlpClientSettings.cpp
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
The error code 500 Internal Error indicates that a server is unable
to handle the request at that time. The error code 503 Slow Down
typically means that the request rate to the server bucket is
too high. Hence, it makes sense to resolve such errors by retrying
the request.
Related-To: OLPEDGE-1398
> Retry unsuccessful HTTP requests on 500 and 503 errors by default.

- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
* Use system clock time as a fallback in AuthenticationClient::SignInClient()
request when GetTimeFromServer() call fails.
Resolves: OLPEDGE-1499
> Use system clock time as a fallback

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/client/BackdownStrategy.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/src/client/OlpClientSettings.cpp
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
- Add new backdown strategy for RetrySettings (backdown_strategy filed in RetrySettings);
- Implement default implementation of `backdown_strategy`  - ExponentialBackdownStrategy;
- fix minor bug with retry attempt without any backdown policy.
Relates-to: OLPEDGE-1419
> Add new backdown strategy to RetrySettings

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/StreamLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/src/StreamLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.h
Reads messages from a stream layer and commits successfully consumed messages before handing them over to user.
Create OlpClient on subscription, an use later in StreamApi calls.
Resolves: OLPEDGE-1353
> Add poll method to stream layer client.

- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
* Added curl_global_init() and curl_global_cleanup()
function calls to linux network implementation which
uses curl to do proper initialization/deinitialization
in network.
Resolves: OLPEDGE-1536
> Add curl_global_init/cleanup to NetworkCurl

- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
- olp-cpp-sdk-dataservice-read/src/generated/api/BlobApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/VolatileBlobApi.cpp
Remove conversion from vector of chars to string.
Remove byte-to-byte copy when retrieving data from disk cache.
Remove byte-to-byte copy in BlobApi, VolatileBlobApi
Relates-To: OLPEDGE-1517
> Performance improvements.

- examples/ProtectedCacheExample.cpp
- olp-cpp-sdk-core/src/cache/DiskCacheSizeLimitEnv.cpp
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
- olp-cpp-sdk-core/tests/thread/SyncQueueTest.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- scripts/linux/psv/travis_build_psv.sh
- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/performance/MemoryTest.cpp
- tests/performance/NetworkWrapper.h
Additionally disable deprecate warnings
Relates-To: OLPEDGE-1083
> Enable clang/gcc warnings on CI

- scripts/linux/psv/travis_build_psv.sh
Disable unused function warning, attribute warning (bug in old gcc)
Relates-To: OLPEDGE-1083
> Enable -Werror (treat warnings as errors)

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/SeekRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/StreamLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/src/StreamLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/tests/StreamLayerClientImplTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/HttpResponses.h
- tests/integration/olp-cpp-sdk-dataservice-read/StreamLayerClientTest.cpp
It's now possible to start reading messages from specified offset.
SeekRequest can be used to specify desired offsets.
Some unit tests are added to cover new methods.
Resolves: OLPEDGE-1352
> Add seek method for StreamLayerClient.

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- tests/common/matchers/NetworkUrlMatchers.h
- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-authentication/FederatedAuthenticationTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
This API designed to authenticate OLP in situations when AAA service implements
a custom logic for special needs.
Resolves: OLPEDGE-1261
> Added a new API to authenticate OLP with a custom request body.

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
Trailing whitespaces evil.
Don't commit evil into your repo.
Trailing whitespace issues can cause a lot of problems when they get into your repository.
It leads to false diffs which claim lines have been changed when in fact the only
the thing that changed was spacing.
This can make finding what actually changed in a file later on in the development cycle
next to impossible.
Relates-To: OLPEDGE-1595
> Remove trailing whitespaces 👹

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Now version of request will be locked on first
call to any of VersionedLayerClient methods that
accept version field in request. Any further
requests with version specified will be ignored.
In case if first request will not contain version
parameter, SDK will request latest and lock to it.
Resolves: OLPEDGE-1515, OLPEDGE-1513
> Add version lock to VersionedLayerClient

- .clang-format
Due to some difference in clang-format versions, some
sorting and breaking is off.
To avoid this, fix default values in .clang-format file
so that we do not have any surprises.
Relates-To: OLPEDGE-1465
> Fix some code style rules checked by clang-format

- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkRequest.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkTypes.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/src/http/NetworkRequest.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/StreamApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/StreamApi.h
- olp-cpp-sdk-dataservice-read/tests/StreamApiTest.cpp
- tests/common/mocks/NetworkMock.cpp
- tests/common/mocks/NetworkMock.h
Get x-corelation-id from http responce  headers.
Modify mock network to return headers.
Relates-To: OLPEDGE-1355
> Add support for X-Correlation-Id

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
VersionedLayerClient needs to serve consistent data for all requests
which are triggered on a particular instance. If user do not know the
catalog version up front and always use boost::none for version, the
risk of returning different catalog versions data is high. Therefore
we lock the catalog version in the constructor of the VersionLayerClient
instance and all requests are therefore served with that particular catalog
version. Hence we do not need the WithVersion() methods in the requests
structures anymore and they will be ignore during requests and the constructor
passed catalog version will be taken instead.
Relates-To: OLPEDGE-1514
> Deprecate WithVersion methods in request classes.

- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
- tests/common/mocks/NetworkMock.cpp
- tests/common/mocks/NetworkMock.h
Using deleted stack headers variable.
Add checking atomic interest_flag to indicate if request was canceled.
Relates-To: OLPEDGE-1605
> Fix crash in OlpClient.

- .gitlab-ci.yml
This Gitlab feature was enabled on Gitlab Server recently.
https://docs.gitlab.com/12.7/ee/ci/junit_test_reports.html#viewing-junit-test-reports-on-gitlab
Relates-To: OLPEDGE-1467
> Add pretty Gitlab reports for FV tests

- scripts/linux/nv/gitlab_test_performance.sh
After the mock server recieves a termination signal it might take
some time before all its child processes are terminated. So the job
bash script must wait for all background processes to finish their work.
Relates-To: OLPEDGE-1576
> Wait for background process termination before exiting

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationSettings.h
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
This is a part of authentication refactoring. Added new
AuthenticationClient constructor using AuthenticationSewttings to
setup network and task scheduler.
Our goal is to remove setters, users should switch to this
constructor, we aim for decoupling this from the TokenEndpoint in
the near future.
Resolves: OLPEDGE-1262
> New AuthenticationClient constructor.

- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
Fix the condition when to print the warning about memory cache cant fit a value.
Resolves: OLPEDGE-1616
> Fix the warning message

- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
Temporary disable functional versioned layer publish tests due
to bug in OLP.
Resolves: OLPEDGE-1614
> Temporary disable functional versioned layer publish tests

- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
There was a possible scenario when the function object was empty.
Resolves: OLPEDGE-1621
> Fix the race condition in the CancelBeforeResponseAndCallHeadersCb test.

- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
This reverts commit 2aace88ddf801a6957abfcbd7029cca70a480cc7.
Resolves: OLPEDGE-1614
> Revert "Temporary disable functional versioned layer publish tests 

- tests/utils/mock_server/server.js
It was removed accidentaly.
Relates-To: OLPEDGE-1252
> Add back the legacy mock server

- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-core/src/geo/tiling/TileTreeTraverse.cpp
gcc 5.4 to 7.0 update.
Resolves: OLPEDGE-1638, OLPEDGE-1620.
> Fix compiler warnings

- .travis.yml
- README.md
- azure-pipelines.yml
- scripts/linux/psv/build_psv.sh
Azure is much more stable platform. Will decrease queues
on Travis in peak time. Travis image update from old
xenial to new bionic. Travis claims some faster image
loading and improvements in bionic. Also removed not
needed packages. Fix 2 minor errors in geo/tiling and Auth.
> Migrate PSV Linux Clang build Travis>Azure

- tests/utils/mock-server-client/Client.h
- tests/utils/mock-server-client/Expectation.h
- tests/utils/mock-server-client/Status.h
With the client, we'll be able to mock HTTP responses of various OLP services.
The MockServer CPP client helps to mock such responses directly from `gtest` code
Relates-To: OLPEDGE-1252
> Add a cpp client for MockServer

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
When the user specifies the list of partitions the query API is used instead of
metadata API. This brings the user functionality to access partitions
metadata of individual partitions.
The implementation checks the cache if the number of requested partitions is
less then the number of partitions found in the cache, the check fails and SDK
performs the online request.
Resolves: OLPEDGE-1017
> Add support for a list of partitions to GetPartition API

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Add overloaded functions with parameter TileRequest to VersionedLayerClient interface.
Implement GetData with TileRequest functions in VersionedLayerClientImpl class.
Relates-To: OLPEDGE-1452
> Add GetData with TileRequest functionality to VersionedLayerClient.

- tests/utils/mock-server-client/Client.h
- tests/utils/mock-server-client/Expectation.h
The method can be used for mocking binary responses.
Fix "ambiguous call" compialtion errors.
Relates-To: OAM-188
> Add MockBinaryResponse method.

- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/HttpResponses.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Add tests for PrefetchTiles with different min/max levels. 
Fix infinite recursion by adding checks for valid TileKey value. 
Reduce min/max level to current level, current level+depth(depth is 4).
Relates-To: OLPEDGE-1624
> Fix iifinite loop in PrefetchTiles. Add tests with wrong levels for PrefetchTiles.

- codecov.yml
Due to unstable work on CodeCov tool and precission
issues we need to exclude more folders from scanner:
- scripts
- examples
- docs
- external
Relates-TO: OLPEDGE-1657
> Fix codecoverage precision,exclude examples

- examples/Options.h
- examples/ReadExample.cpp
- examples/ReadExample.h
- examples/main.cpp
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
VersionedLayerClient API is changed, version is specified in constructor
instead of DataRequest now. So the goal of this change is to adapt
example and doxygen to the new API. Added new argument for catalog
version.
Resolves: OLPEDGE-1566
> Update VersionedLayerClient example and doxygen.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/Partitions.h
- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.h
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.h
- olp-cpp-sdk-dataservice-read/src/generated/parser/PartitionsParser.cpp
- olp-cpp-sdk-dataservice-read/src/generated/serializer/PartitionsSerializer.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/ParserTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
Add CRC field support to partition model.
This gives to user functionality to access partition metadata fields:
* data size
* compressed data size
* checksum
* crc
Resolves: OLPEDGE-1019
> Add additional fields support

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/include/olp/authentication/IntrospectAppResult.h
- olp-cpp-sdk-authentication/include/olp/authentication/Types.h
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-authentication/src/Constants.cpp
- olp-cpp-sdk-authentication/src/Constants.h
- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationMockedResponses.h
Added new IntrospectApp method for AuthenticationClient. Now it's
possible to obtain application info like name, description, realm etc.
using access token.
Functional and integration tests added also.
Resolves: OLPEDGE-1489
Signed-off-by: Kostiantyn Zvieriev ext-kostiantyn.zvieriev@here.com
> Expose introspect app API

- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
Fix the flaky condition in DataserviceWriteVersionedLayerClientTest.StartBatch test.
Resolves: OLPEDGE-1653
> Fix the flaky condition.

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Crash happens when the curl handle is duplicated in different request handles,
and then used concurrently with curl_slist_append/curl_slist_free_all.
Keep the mutex lock longer.
Add missing handle release.
OLPEDGE-1687
> Fix a crash in the NetworkCurl

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/FetchOptions.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Return InvalidArgument for CacheWithUpdate option.
Update tests.
Relates-To: OLPEDGE-1658
> Make CacheWithUpdate option unsuported for VersionedLayerClient.

- olp-cpp-sdk-core/include/olp/core/client/OlpClientFactory.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
- olp-cpp-sdk-core/src/client/OlpClientFactory.cpp
- olp-cpp-sdk-core/src/client/OlpClientSettings.cpp
- olp-cpp-sdk-core/src/client/PendingRequests.cpp
- olp-cpp-sdk-core/src/client/Tokenizer.h
Last classes and structures are now adapted to the coding style.
This also changes include headers in public headers to global scope
so that it can support better the pre-installed SDK.
Relates-to: OLPEDGE-567
> Adapts last of the core/client classes to coding style.

- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClient.h
- olp-cpp-sdk-dataservice-write/src/StreamLayerClient.cpp
Additionally makes constructor explicit. It is not a good practice
to take hide move oportunities from API users. Making the DefaultCache
constructor and the OlpClientSettingsFactory::CreateDefaultCache() method
take-in the CacheSettings by copy will allow user to pass-move and save
possible copies on the strings.
This also deprecates the olp::dataservice::write::StreamLayerClient
CreateDefaultCache() function as it is a duplicate to the
OlpClientSettingsFactory::CreateDefaultCache() method. Will be removed
by 06.2020. Until then this free function will use OlpClientSettingsFactory
internally to create the default cache instance.
Resolves: OLPEDGE-1509
> Change DefaultCache constructor to take settings by value.

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
Pass the user provided CheckCrc open option, to the leveldb::ReadOptions.
Resolves: OLPEDGE-1660
> Enable checksum verification during reading data from leveldb.

- olp-cpp-sdk-authentication/include/olp/authentication/TokenEndpoint.h
- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
TokenEndpoint impl is now a class, not a struct anymore as this is
against the coding style. Some minor variables renamed. This also
moves the impl methods definition from inlined to ouside the class
to align all methods.
TokenEndpoint, as it is currently public, should also include its
dependency headers via global scope.
Relates-to: OLPEDGE-1028
> Adapts TokenEndpoint to coding style.

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/Common.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/ApiClientLookupTest.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
Add Check if fetch_option is not OnlineOnly, and cache only in that case.
Resolves:OLPEDGE-1659
> SDK should not cache data with FetchOption::OnlineOnly requests.

- tests/utils/mock-server-client/Client.h
- tests/utils/mock-server-client/Expectation.h
- tests/utils/mock-server-client/Status.h
**Split declarations and definitions.**
This fixes the "already defined" compilation error.
Also improves the code readability a bit, as the code
delcaring classes and structs becames slimer.
Relates-To: OAM-188
> Split declarations and definitions.

- olp-cpp-sdk-core/include/olp/core/client/OlpClient.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
Adapts OlpClient to the coding style and simplifies internals.
Two unnecessary moves in ApiClientLookup::LookupApi() removed, as this resulted
together with changing OlpClient::SetSettings() take settings in as copy to crash
as this will move twice the same resource which is not possible.
Added aliases for input parameters on OlpClient::CallApi() to make the footprint
smaller. Internally refactored a little to make better use of the method chaining
from NetworkSettings and NetworkRequest. Moved Bearer header to a free function.
Move constructor and destructor default definition to cpp file.
Relates-to: OLPEDGE-567
> Adapts OlpClient to the coding style and simplifies internals.

- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVolatileLayerClientTest.cpp
Add OnlineIfNotFound case for GetPartitionsDifferentFetchOptions test.
Resolves: OLPEDGE-1709
> Fix VolatileLayerClientTest.GetPartitionsDifferentFetchOptions.

- olp-cpp-sdk-authentication/include/olp/authentication/TokenEndpoint.h
- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
As we deprecated some classes that are public but only to be used
internaly there are a lot of deprecated warnings when building the SDK.
This adds pragma compiler flag disables for the places where we actually
use these classes internaly until we can finaly move these classes to private.
Also this commit removes the version usage from the request key creation and
adds again pragma disables to the repositories which are still using the version
setters/getters internaly. This will be changed in the future but until then
we need to lower the warnings count while building.
Resolves: OLPSUP-9858
> Reduce compiler warnings about deprecated methods/classes.

- .gitlab-ci.yml
- scripts/linux/weekly/build_centos_debug_wv.sh
- scripts/linux/weekly/security_scanner_upload_wv.sh
Job should run weekly on Gitlab by Schedule.
Script doing:
- build on centos7 with debug
- upload archive into Security scanner via API
Relates-to: OLPEDGE-896
> Add job/scripts for security scan

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/http/Network.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkRequest.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkUtils.h
- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
- olp-cpp-sdk-core/src/http/DefaultNetwork.cpp
- olp-cpp-sdk-core/src/http/DefaultNetwork.h
- olp-cpp-sdk-core/src/http/Network.cpp
- olp-cpp-sdk-core/src/http/NetworkRequest.cpp
- olp-cpp-sdk-core/src/http/NetworkUtils.cpp
- olp-cpp-sdk-core/tests/http/NetworkUtils.cpp
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-core/DefaultNetworkTest.cpp
User can set default headers that will be added for each request made by
network. Additionally, it concatenates the user agents set with default headers
and user agents passed with network request.
Relates-To: OLPEDGE-1669
> Add custom headers for network.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Added new RemoveFromCache method. It's now possible to clear all cache
data for specific partition.
Added integration test for the new functionality.
Resolves: OLPEDGE-1567
Signed-off-by: Kostiantyn Zvieriev ext-kostiantyn.zvieriev@here.com
> RemoveFromCache API for VersionedLayerClient.

- .gitlab-ci.yml
- scripts/linux/weekly/build_centos_debug_wv.sh
- scripts/linux/weekly/security_scanner_upload_wv.sh
Add LD_PRELOAD var to centos build.Add missed flags.
Remove not needed flag. Switched from cmake to make.
Make shell using latest curl. Fix archiving.
Relates-TO: OLPEDGE-1725, OLPEDGE-896
> Update centos build for weekly security test

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/HttpResponses.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Split functionality to two categories. With default min/max levels prefetch only requested tiles.
With valid levels, which differs prefetch all tiles in subtre from min to max levels.
Create slicing of subtree using depth equal 4.
Resolves:OLPSUP-9847
> Refactor prefetch functionality.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Overloading RemoveFromCache() method with TileKey input. Its reusing
previous method implementation, so added integration and unit tests are
similar.
Resolves: OLPEDGE-1567
> RemoveFromCache by TileKey for VersionedLayerClient

- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/PrefetchRepositoryTest.cpp
Add tests to check splitting subtree on slices with depth 4.
Add tests to calculate subtree with min/max levels default, or specified.
Test with sibling tiles on the same levels and different.
Resolves:OLPSUP-9847
> Unit tests for PrefetchRepository.

- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
Fixed possible stack overflow while copying data
from string in AuthenticationClient::Impl::SignInFederated
Resolves: OLPEDGE-1716
> Security fix in AuthenticationClient

- azure-pipelines.yml
- scripts/misc/commit_checker.sh
- scripts/misc/commit_message_recom.txt
Add script to separate Azure job which verify
correctness of agreed commit message.
Title is less than 50 chars.
Next to title must be clear line.
After that all lines length is less than 80chars.
At the end should be Jira reference.
Resolves: OLPEDGE-1573
> Add commit message checker on PSV

- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
- olp-cpp-sdk-core/src/thread/ThreadPoolTaskScheduler.cpp
- olp-cpp-sdk-core/tests/cache/InMemoryCacheTest.cpp
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/tests/ApiClientLookupTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientTest.cpp
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/generated/model/Index.h
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/tests/ApiClientLookupTest.cpp
- olp-cpp-sdk-dataservice-write/tests/StreamLayerClientImplTest.cpp
- scripts/linux/psv/build_psv.sh
- scripts/linux/weekly/build_centos_debug_wv.sh
- tests/common/mocks/NetworkMock.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/functional/utils/Utils.h
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/IndexLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/StreamLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/VolatileLayerClientTest.cpp
- tests/performance/MemoryTest.cpp
- tests/performance/NullCache.h
Enable compiler warnings and treat them as errors:
* unused parameters
* unused functions
Updated the psv script to trigger an error on new warnings.
Relates-To: OLPEDGE-1728
> Enable compiler warnings

- scripts/misc/commit_checker.sh
Git log works differently for PR and for
Master build. Trying to fix it by simple condition.
Resolves: OLPEDGE-1753
> Fix git log inconsistency on Azure

- scripts/misc/commit_checker.sh
When it's PR build `git branch` shows like:
`* (HEAD detached at pull/739/merge)`
When it's master build:
`* (HEAD detached at SOME_HASH)`
Conditon will help to solve that.
Relates-To: OLPEDGE-1753
> Fix git log parser on Azure

- olp-cpp-sdk-core/include/olp/core/geo/Types.h
- olp-cpp-sdk-core/include/olp/core/geo/projection/EquirectangularProjection.h
- olp-cpp-sdk-core/include/olp/core/geo/projection/IProjection.h
- olp-cpp-sdk-core/include/olp/core/geo/projection/IdentityProjection.h
- olp-cpp-sdk-core/include/olp/core/geo/projection/SphereProjection.h
- olp-cpp-sdk-core/src/geo/projection/EquirectangularProjection.cpp
- olp-cpp-sdk-core/src/geo/projection/IdentityProjection.cpp
- olp-cpp-sdk-core/src/geo/projection/SphereProjection.cpp
This commit adapts the following files to the coding style:
Types.h, EquirectangularProjection.h, IdentityProjection.h
SphereProjection.h and IProjection.h.
Relates-to: OLPEDGE-569
> Adapts core/geo/projection files to coding style.

- olp-cpp-sdk-authentication/src/AuthenticationCredentials.cpp
- olp-cpp-sdk-authentication/src/BaseResult.cpp
- olp-cpp-sdk-core/include/olp/core/generated/serializer/SerializerWrapper.h
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/generated/serializer/IndexInfoSerializer.cpp
- olp-cpp-sdk-dataservice-write/src/generated/serializer/UpdateIndexRequestSerializer.cpp
Fix various warnings:
* signed/unsigned compare
* variable shadowing
* assignment in conditional expression warning
Small code refactoring.
Relates-To: OLPEDGE-1728
> Fix various warnings on windows

- olp-cpp-sdk-core/include/olp/core/geo/coordinates/GeoCoordinates.h
- olp-cpp-sdk-core/include/olp/core/geo/coordinates/GeoCoordinates3d.h
- olp-cpp-sdk-core/include/olp/core/geo/coordinates/GeoPoint.h
- olp-cpp-sdk-core/include/olp/core/geo/coordinates/GeoRectangle.h
- olp-cpp-sdk-core/src/geo/coordinates/GeoCoordinates.cpp
- olp-cpp-sdk-core/src/geo/coordinates/GeoCoordinates3d.cpp
- olp-cpp-sdk-core/src/geo/coordinates/GeoRectangle.cpp
This commit is the first of a series of coding style adapts
to follow for the olp/geo folder, which is based on a legacy
repository that was merged into this.
This commit adapts GeoCoordinates, GeoCoordinates3d, GeoPoint,
and GeoRectangle to coding style.
Relates-to: OLPEDGE-569
> Adapts core/geo files to coding style.

- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-core/CacheTest.cpp
- tests/integration/olp-cpp-sdk-core/DefaultCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Create mock cache. Run get data for VersionedLayerClient.
Check if lookup api data are stored in cache with expiration time equal
1 hour(3600 seconds). Write core test to check cache expiration. Write 
data with expiration 1 second. Get data from cache to check if data was
stored corectly. Wait 2 seconds and try to get data again. Data should 
be expired.
Relates-To: OLPEDGE-1612
Signed-off-by: Liubov Didkivska ext-liubov.didkivska@here.com
> Add expiration cache test for lookup api.

- olp-cpp-sdk-core/tests/thread/SyncQueueTest.cpp
Fix for flaky test SyncQueueTest.ConcurrentUsage which was failed due
to SyncQueue emptiness check that could be true before all tasks were
actually complete.
Resolves: OLPEDGE-1713
> Fix flaky test SyncQueueTest.ConcurrentUsage

- external/CMakeLists.txt
- external/boost/CMakeLists.txt
- external/boost/CMakeLists.txt.boost.in
Initializing boost from a github is more natural approach.
Resolves: OLPEDGE-1661, OLPEDGE-789
> Replace boost archive with boost github repo

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
Add RemoveFromCache by TileKey function to VolatileLayerClient.
Add integration test to check if partition related to removed
TileKey is not longer avialible in cache after deletion.
Relates-To: OLPEDGE-1663
> Add API to remove single partition/tilekey from cache for VolatileLayerClient

- external/boost/CMakeLists.txt
Let the bootstrap figure out the toolset it needs.
Relates-To: OLPEDGE-1661
> Fix Boost bootstrap during cross compile.

- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.h
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/QueryApiTest.cpp
This is a part of prefetch update of VolatileLayerClient. The method is
loading tile metadata like QueryApi::QuadTreeIndex(), but for volatile
layer.
Resolves: OLPEDGE-794
> QuadTreeIndexVolatile method for QueryApi.

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
Second part of prefetch update of VolatileLayerClient. This change
contains impl update and unit tests. The method loads data for specified
tile and levels.
Resolves: OLPEDGE-794
> PrefetchTiles for VolatileLayerClientImpl.

- olp-cpp-sdk-core/include/olp/core/http/Network.h
- olp-cpp-sdk-core/src/http/Network.cpp
This API should enable users to query network statistics and aggregate
the statistics by buckets (Wifi/Cellular/etc.) when needed.
Resolves: OLPEDGE-1761
> Added API to retrieve network statistics.

- olp-cpp-sdk-authentication/include/olp/authentication/AutoRefreshingToken.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
TokenProvider which is widely used by all OLP SDK users to request tokens
uses internally TokenEndpoint and AutoRefreshingToken which are
marked as deprecated and create compiler warnings. This is now
filtered out by pragmas.
Resolves: OLPEDGE-1768
> Removes internal deprecated compiler warnings.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClient.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/HttpResponses.h
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
The method loads data for specified tile and levels range. This is
third and the last part of prefetch update of VolatileLayerClient.
Change only connects public API with impl and add integration tests
for it.
Resolves: OLPEDGE-794
> VolatileLayerClient PrefetchTiles API.

- external/boost/CMakeLists.txt.boost.in
Skip the build step on windows.
Resolves: OLPEDGE-1778, OLPEDGE-1756
> Fix the boost configuration on windows

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationSettings.h
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
Add use_local_time parameter to AuthenticationSettings to
control if AuthenticationClient will try to get time from server
or use local machine time instead.
Resolves: OLPEDGE-1762
> Add use_local_time parameter to AuthenticationSettings

- azure-pipelines.yml
Job must run only for Pull requests.
Master builds to be avoided.
Relates-TO: OLPEDGE-1573
> Change commit checker job to run only on PR

- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.h
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
Added LRU cache is going to be used to control mutable cache eviction.
This change is only preparation and no eviction strategy implemented
yet. New unit tests check DefaultCache functionality is not broken by
different eviction policies.
Resolves: OLPEDGE-1591
> LRU cache for the mutable disk cache.

- olp-cpp-sdk-core/src/http/DefaultNetwork.cpp
- olp-cpp-sdk-core/src/http/DefaultNetwork.h
- tests/integration/olp-cpp-sdk-core/DefaultNetworkTest.cpp
Track the number of requests and metrics. Users can now track the
network in/out number of bytes. Calculations rely on network impl's
to provide the correct download/upload numbers in network response.
Relates-To: OLPEDGE-1754
> Implement buckets for DefaultNetwork

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.h
Calculations are approximate, number bytes sent is calculated as a
size of body and a size of headers. Number of bytes received is
calculated as size of headers plus content length if available, else
a sum of chunks sizes.
Relates-To: OLPEDGE-1760
> Calculate total bytes sent/received on Windows

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
Use curl_easy_getinfo to get size of headers and data
(CURLINFO_HEADER_SIZE, CURLINFO_SIZE_DOWNLOAD).
Get upload size using CURLINFO_REQUEST_SIZE.
Relates-To: OLPEDGE-1759
> Add measurement of downloaded/uploaded data Linux.

- olp-cpp-sdk-authentication/include/olp/authentication/AutoRefreshingToken.h
Mark AutoRefreshingToken class as deprecated.
Relates-To: OLPEDGE-1737
> Deprecate AutoRefreshingToken class

- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
Remove the usage of deprecated VersionedLayerClient constructor.
Resolves: OLPEDGE-1792
> Fix the failed GetDataFromPartitionSync test

- README.md
Markdown links are not built correctly on the portal(docs.in.here.com).
Links of the HTML format should be used instead.
Relates-To: OLPEDGE-1732
> Modify links

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
Fix warning about uninitialized variable in the default RequestData
constructor.
Resolves: OLPEDGE-1783
> Fix warning about uninitialized variable.

- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-authentication/TokenProviderTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
To be able to share one single instance of TokenProvider with multiple
users a shared pimpl is applied. This is especially helpfull for
multiple layer clients that access the same catalog with the same
credentials and in turn the same token. This will save a huge amount
of token requests.
Relates-to: OLPEDGE-1791
> Apply pimpl patter to TokenProvider.

- examples/ProtectedCacheExample.cpp
- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationCredentials.h
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-authentication/src/AuthenticationCredentials.cpp
- olp-cpp-sdk-authentication/tests/AuthenticationCredentialsTest.cpp
- olp-cpp-sdk-core/include/olp/core/client/ApiResponse.h
- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientTest.cpp
- scripts/linux/psv/build_psv.sh
- scripts/linux/weekly/build_centos_debug_wv.sh
- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationCommonTestFixture.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationProductionTest.cpp
- tests/functional/olp-cpp-sdk-authentication/HereAccountOauth2ProductionTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
- tests/performance/MemoryTest.cpp
Removed AuthenticationCredentials explicit copy ctor.
Removed ApiResponse explicit copy ctor.
Updated many places with new AuthentionClient ctor.
Tests that are still use deprecated API have warnings disabled.
Change make_unique to make_shared since the warning was generated in
make_unique template function.
Relates-To: OLPEDGE-1800
> Enable deprecated-declaration warning as error

- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
- tests/functional/olp-cpp-sdk-authentication/HereAccountOauth2ProductionTest.cpp
TokenProvider considers all responses comming from the oauth2 backend
as valid, regardless if it is and error or an valid token. This small
behaviour was changed during pimpl changes and are now reverted.
Resolves: OLPEDGE-1807
> Fix broken TokenProvider behavior on error.

- tests/integration/olp-cpp-sdk-authentication/TokenProviderTest.cpp
The StrictMock imposes to strict order which due to the async nature
can result in reordering of requests. Replaced the StrictMock with
expects that certain calls should not occur.
Resolves: OLPEDGE-1817
> Removes Network StrictMock in TokenProviderTest

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationSettings.h
- olp-cpp-sdk-authentication/include/olp/authentication/Settings.h
- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
- tests/integration/olp-cpp-sdk-authentication/TokenProviderTest.cpp
Add use_system_time parameter to Settings class.
Convert it to AuthenticationSettings in TokenEndpoint.
Add integratin test to check usage of system/server time.
Relates-To: OLPEDGE-1785
> Add use_system_time to Settings

- .gitlab-ci.yml
Fix CI restriction, when we can't run job from
Gitlab Pipelines Page. Rafactor variables.
Use variables when run pipeline:
- FV=1 for full verification pipe.
- NV=1 for nigthly and performance pipe.
- SECURITY=1 for weekly security pipe.
Resolves: OLPEDGE-1793
> Add trigger for Gitlab jobs from branches

- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
- olp-cpp-sdk-core/include/olp/core/client/Condition.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
- olp-cpp-sdk-core/include/olp/core/http/HttpStatusCode.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkTypes.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkUtils.h
- olp-cpp-sdk-core/include/olp/core/logging/Appender.h
- olp-cpp-sdk-core/include/olp/core/logging/LogMessage.h
- olp-cpp-sdk-core/include/olp/core/math/Math.h
Add missing CORE_API macro to classes and structs
Resolves: OLPEDGE-1693
> Add missing CORE_API export

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- scripts/misc/cpplint_ci.sh
- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
Adapt authentication test with proxy to new client constructor.
Relates-To: OLPEDGE-1855
> Remove deprecated methods from AuthenticationClient

- olp-cpp-sdk-authentication/include/olp/authentication/TokenEndpoint.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenRequest.h
Extend the deprecation period for TokenEndpoint and TokenRequest.
Fix some of the cpplint warnings.
Relates-To: OLPEDGE-1855
> Extend the deprecation period for some classes

- azure-pipelines.yml
Every week ccache will be refreshed on PR and master builds
of 'Linux Clang Build' job.
So build time decrease from 9 to 3 mins.
RestoreKeys are needed for partial cache match.
Azure doc is : https://bit.ly/3bxSHcz
Resolves: OLPEDGE-1731
> Add ccache reset condition for every week

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.h
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
Size of mutable cache limited by DiskCacheSizeLimitEnv. Because of
leveldb implementation, its size increasing even after removing items
from the cache. So env can't be used for cache size limitation and
eviction.
Resolves: olpedge-1592
> Track mutable cache size.

- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
Remove the old unused constructor.
Resolves: OLPEDGE-1859
> Fix the failed test.

- scripts/linux/fv/gitlab-olp-cpp-sdk-authentication-test.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-core-test.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-dataservice-read-test.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-dataservice-write-test.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-integration-test.sh
- scripts/linux/fv/gitlab_test_fv.sh
During development we found that .variables injection may be
failed and skipped as error during FV execution. It's caused
by exit status which we set after FV functinal tests passed.
To fix that I moved variables injection on higher level.
Do the same for all FV test group.This way is already used
in NV tests.
Relates-To: OLPEDGE-1738
> Improvement for FV scripts

- azure-pipelines.yml
Restore key may prevent correct ccache hit.
Relates-To: OLPEDGE-1731
> Remove unused restoreKey in Azure ccache

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.h
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
- tests/common/matchers/NetworkUrlMatchers.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
If mutable cache reached max_disk_storage size, user will not be able
to put new values. Removing least recently used items allows to use the
cache further.
Eviction process strarts after 90% threshold and goes till 85%, so all
values can be removed in one batch and number of disk calls is
minimized.
Resolves: OLPEDGE-1592, OLPEDGE-1822
> Eviction for mutable cache.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/PrefetchTilesRequestTest.cpp
Because of two WithTileKeys overloads using a copy parameter input,
and accordingly rvalue reference input, users were not able to std::move
efficiently any TileKey list as it would result in a compilation error
due to the ambiguous nature of the two overloads. This is now fixed and
user should be able to move efficiently any give vector into the request
structure by using WithTileKeys.
Relates-To: OLPEDGE-1838
> Rvalue issue in PrefetchTilesRequest fixed.

- olp-cpp-sdk-core/src/utils/Base64.cpp
During clang-format the include order in Base64.cpp was reordered which
results in broken build on system with disabled exceptions. This is
now fixed.
Resolves: OLPEDGE-1883
> Fix boost::throw_exception include missing.

- scripts/linux/fv/olp-cpp-sdk-functional-test.variables
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVolatileLayerClientTest.cpp
Functional tests for VolatileLayerClient::PrefetchTiles() method. New
catalog/credentials created for the tests, since Read/Write volatile
layer with HERETile scheme required.
Resolves: OLPEDGE-1738
> VolatileLayerClient::PrefetchTiles fv tests.

- docs/OverallArchitecture.md
- docs/dataservice-cache-example.md
- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationSettings.h
- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
- olp-cpp-sdk-core/src/cache/DiskCache.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientCacheTest.cpp
- tests/performance/MemoryTest.cpp
The in-memory and on-disk is a tautology and seldomly used terms.
Relates-To: OAM-221
> Correct the spelling

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Change VersionedLayerData::GetData(TileRequest)
to request quad tree for parrent tile.
Relates-To:OLPEDGE-1894
> Optimize quad tree index for GetData(TileRequest)

- olp-cpp-sdk-core/src/http/android/HttpClient.java
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.h
Uninitialized variables count and offset could potentially
cause broken response to user.
* Fix Android proxy enum.
* Fix network initialization in concurrent env.
Resolves: OLPSUP-10333
> Fix uninitialized variables count and offset.

- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteIndexLayerClientTest.cpp
Previously: add and remove index in one request, now - two requests.
Resolves: OLPEDGE-1899
> Fix the UpdateIndex functional test.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogVersionRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/ConsumerProperties.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/FetchOptions.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTileResult.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/StreamLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/SubscribeRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/TileRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/Messages.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/Partitions.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/StreamOffsets.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClient.h
- scripts/misc/cpplint_ci.sh
Fix all warnings reported in dataservice-read public headers.
Validate any change in them with a cpplint tool and block psv
in case any issue is found. (except: include order warnings)
Relates-To: OLPEDGE-1909
> Fix cpplint warnings in dataservice-read/include

- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/IndexLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/generated/model/Details.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/generated/model/Index.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/generated/model/VersionDependency.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/CheckDataExistsRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/DeleteIndexDataRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/PublishDataRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/PublishIndexRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/PublishPartitionDataRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/PublishSdiiRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/StartBatchRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/model/UpdateIndexRequest.h
- scripts/misc/cpplint_ci.sh
Check the warning during PSV and block CI make the warning.
Relates-To: OLPEDGE-1909
> Fix cpplint warnings in dataservice-write headers

- olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
- olp-cpp-sdk-core/tests/client/TaskContextTest.cpp
TaskContext should not trigger cancellation after request was
completed. This could happen when the execution function keeps
the last owning reference to the object that cancels task context
in destruction.
Resolves: OLPSUP-10456
> TaskContext should not trigger cancellation.

- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
This value is propagated to cache when something is stored by client.
Resolves: OLPEDGE-1914
> Add default_cache_expiration to OlpClientSettings

- README.md
Change all URLs in README including badges for CI/CD,
due to renaming from olp-sdk to data-sdk
Resolves: OLPEDGE-1845
> Change all URLs in README

- CONTRIBUTING.md
- docs/dataservice-read-catalog-example.md
- docs/dataservice-write-example.md
All old URLs from various md files are now pointing to the
new repository name.
Relates-To: OLPEDGE-1886
> Adapt ULRs after repository name change.

- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/functional/utils/DefaultResponses.h
- tests/functional/utils/MockServerHelper.cpp
- tests/functional/utils/MockServerHelper.h
- tests/utils/mock-server-client/Client.h
Create mock client to set expectation on server.
Add helper class to create server responces structures.
Add sequence verification of requests on server.
Relates-To: OLPEDGE-732
> Add test with usage of mock server

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/PartitionsCacheRepositoryTest.cpp
Default cache items expiration time can be controlled through
OlpClientOptions, so PartitionsCacheRepository should use it instead of
maximum time_t value. Added unit tests.
Resolves: OLPEDGE-1916
> Default expiration in PartitionsCacheRepository

- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
- tests/integration/olp-cpp-sdk-authentication/TokenProviderTest.cpp
When there is no token available, requesting token from different
threads trigger multiple online requests.
Resolves: OLPEDGE-1957
> Merge request in TokenProvider class

- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/DataCacheRepositoryTest.cpp
Default cache items expiration time can be controlled through
OlpClientOptions, so DataCacheRepository should use it instead of
maximum time_t value. Added unit tests.
Resolves: OLPEDGE-1915
> Default expiration in DataCacheRepository

- olp-cpp-sdk-dataservice-read/src/repositories/CatalogCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/CatalogCacheRepositoryTest.cpp
Default cache items expiration time can be controlled through
OlpClientOptions, so CatalogCacheRepository should use it instead of
maximum time_t value. Added unit tests.
Resolves: OLPEDGE-1917
> Default expiration in CatalogCacheRepository

- CMakeLists.txt
- README.md
- olp-cpp-sdk-core/CMakeLists.txt
Users can use it to disable debug/trace log messages. Default is OFF
which mean means that messages are enabled.
Resolves: OLPEDGE-247
> Add CMake option OLP_SDK_DISABLE_DEBUG_LOGGING

- .gitlab-ci.yml
- azure-pipelines.yml
- scripts/android/build-test-emulator.sh
Script do:
- build SDK with needed options for Android
(API=25,ABI=arm64-v8a)
- create AndroidVirtualDevice(AVD)
- start AVD via embeded SDK emulator
- run trivial adb command to check that device is ON.
(.apk installation to be added later)
Everything can run on:
- Gitlab CI by using our Android image
- Azure Pipelines CI by using MacOS image.
Resolves: OLPEDGE-1774
> Android emulator.Add script and manual CI jobs

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/ApiCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- scripts/misc/cpplint_ci.sh
The SDK logs too much and too often especially in the API repositories.
This commit removes some of the duplicated logs, aligns all logs to a
common structure, and adds additional info like HRN and key to all
important logs. All other logs that are not important are now on level
debug. All previous trace logs which are actually printing debug level
information are now raised to debug level.
One very important fix that needs highlight is the capture by copy
which was removed from most of the cache repositories while putting
into the cache. It is not necessary to capture model data by copy as
the KeyValueCache::Put() is pure sync and will not leave the context
so that the model faces deletion. This additional copy is not needed
and might even bring performance decreases. This is now fixed …
> Reduce excesive logging in API repositories.

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.h
- olp-cpp-sdk-dataservice-read/tests/ApiClientLookupTest.cpp
Used to speedup the cold start, when multiple clients concurrently
tries to download the services URLs.
The callers are blocked until the first caller downloads the content.
Relates-To: OLPEDGE-1986
> Merge concurrent lookup API requests.

- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
This commit adds the possible compression settings to the CacheSettings
structure to be passed on to leveldb. Possible values so far are only
no compression or Snappy compression. Nevertheless there are user who
will profit from not applying any compression if the data added to the
cache is already compressed, e.g. protobuf.
Additionally this commit adds filter policy to bloom filter with 10
bits precision which will enhance reading speeds.
Relates-To: OLPEDGE-1984, OLPEDGE-1983
> Add compression to CacheSettings.

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.h
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
When reading data from leveldb::Get() we need to use a string which
is poorly initialized and data is copied slowly and inefficient to it
which then again is memcpy-ied to a shared vector which adds another
layer of memcpy and slow initialization. The overhead for frequent data
reads is more then enough to consider an alternative.
This alternative consist in reading the data directly from the DB into
the resulting shared vector without any intermediate steps by using
iterators. The leveldb iterator gives us the possibility to access the
raw DB data and size without passing it into a inefficient string
before, and gives a huge performance bump.
Relates-To: OLPEDGE-1983
> Optimize reading data from leveldb with iterator.
