heremaps/here-data-sdk-cpp

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
Store and reset FilterPolicy together with database which uses it.
Relates-To: OLPEDGE-1989
> Fix memory leak in DiskCache.

- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.h
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
When eviction happens, first we remove all expired elements, and only
then we remove other elements if still needed.
Change the internal LRU representation, so that we have fast access to
key expiration. Saves extra cache lookup during eviction.
Fix the use case when protected cache contains expired data.
Relates-To: OLPEDGE-1925
> Remove expired elements during cache eviction

- .gitlab-ci.yml
- scripts/android/build-test-emulator.sh
Replace ninja to cmake for MacOS and Ubuntu compatibility.
Add NDK_ROOT path on MacOS, which already exist in docker image.
Use API available in docker: 21.
Change condition for android device readiness check.
Relates-To: OLPEDGE-1774, OLPEDGE-2007
> Android Emulator job:NDK_ROOT,replace ninja to cmake

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
SDK performs retry logic in OlpClient::CallApi method
using advanced backdown strategy by default. It is
recommended to use a backdown strategy instead of plain
retry.
Format the file with clang-format.
Fix the includes, remove unused variables.
Resolves: OLPEDGE-1608
> Remove network curl retry

- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
- olp-cpp-sdk-core/src/http/Network.cpp
The prewarm helper should be used to prewarm the connection
to certain hosts like authentication and lookup API URLs
so that DNS prefetch and TLS preconnect are already done
and keept alive by the Network layer. This will reduce the
subsequent requests latency in the order of 100-200ms.
Relates-To: OLPEDGE-1995
> Add prewarm helper to OlpClientSettingsFactory.

- .gitlab-ci.yml
Split FV test report into 4 groups:
- functional
- integration
- unit
- full
All 4 reports will be pablished as previously on GitLab Pages.
Add names. Pulish index on Pages, others as artifacts.
Resolves: OLPEDGE-660
> FV:Split xml reports on GitLab

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationError.h
Class AuthenticationError duplicates the ApiError class.
Class is removed, but the alias to ApiError is still present and
deprecated.
Relates-To: OLPEDGE-1027
> Replace AuthenticationError class with ApiError

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
It was disabled long time ago, should be enabled by default.
Relates-To: OLPEDGE-2014
> Enable SSL for network curl.

- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
Change sign in functionality from async ExecuteOrCancelled
to OlpClient CallApi. Add task to task sceduler.
Update tests.
Relates-To: OLPEDGE-2012
> Switch SignInClient code to task

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.h
- olp-cpp-sdk-dataservice-read/tests/PartitionsCacheRepositoryTest.cpp
This is a part of GetAggregatedData API update. The method will cache
QuadTreeIndex.
Resolves: OLPEDGE-1932
> Put/Get QuadTreeIndex into cache.

- .gitlab-ci.yml
It's needed because we have different reports on NV and FV.
So scripts should be different. On NV we do not have Functional
testing and have HeapTrack report.
Resolves: OLPEDGE-660
> NV/FV:Split Gitlab test reporting job

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationSettings.h
- olp-cpp-sdk-authentication/include/olp/authentication/Settings.h
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
Until now the default behaviour for oauth trough TokenProvider or
AuthenticationClient was to use the server timestamp and only on user
request or on error use the system time as an alternative.
This behaviour is now reversed so that as a default system time is
used and users need to explicitly change the use_system_time variable
in AuthenticationSettings or TokenProvider Settings to false to use
server time in case they know that the system time is not to be trusted.
Relates-To: OLPEDGE-2009
> Change to using system time by default for oauth.

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test-mock.sh
This is needed to make HTTPS requests to a local server.
Resolves: OLPEDGE-2018
> Install the mock server certificate as trusted.

- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationMockedResponses.h
For case if system time is wrong read time from
headers and send authorization request again with readed timestamp.
Add integration test.
Relates-To: OLPEDGE-1921
> Auth fallback mechanism when system time is wrong

- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
This is a part of GetAggregatedData API update. PartitionRepository
handle loading quad tree and storing it into the cache, so it can be
used by clients further.
Resolves: OLPEDGE-1932
> GetAggregatedPartition for PartitionRepository.

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
lock should be called on unique_lock instead of mutex.
unique_lock itself should be constructed with defer_lock.
Resolves: OLPEDGE-2023
> Fix the incorrect lock() call.

- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
In order not to cause a deadlock when the sign-in happens from another
task within the task scheduler with one thread.
Resolves: OLPEDGE-2032
> Fix the regression after SignInClient changes

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
During testing was found that function InitializeLru could crash
during expiration parsing, the data length was not taken into account
when it was parsed, and std::stol throw an exception.
Resolves: OLPEDGE-2029
> Fix a crash inside InitializeLru

- docs/dataservice-cache-example.md
- docs/dataservice-read-catalog-example.md
Include `default_cache_expiration` in the following instructions:
* Read Example
* Cache Example
Relates-To: OLPEDGE-2004
> Add info on `default_cache_expiration`

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/AggregatedDataResult.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- tests/integration/olp-cpp-sdk-dataservice-read/HttpResponses.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
New API fetches data of a tile or its closest ancestor. It can be useful
when need to load most detailed available data for specified tile. Added
integration tests to cover the API.
Resolves: OLPEDGE-1932
> VersionLayerClient adding GetAggregatedData API

- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.h
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.h
- olp-cpp-sdk-authentication/tests/AuthenticationClientTest.cpp
This is needed to enable testing and enabled new code to reuse it.
Adapt function to coding style, switch from string concatenation to
reusable string stream.
Remove a needless auth namespace.
Resolves: OLPEDGE-2030
> Move the authorization header function to utils

- olp-cpp-sdk-authentication/include/olp/authentication/AuthorizeResult.h
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.h
- olp-cpp-sdk-authentication/src/Constants.cpp
- olp-cpp-sdk-authentication/src/Constants.h
- olp-cpp-sdk-authentication/tests/DecisionApiClientTest.cpp
- tests/functional/olp-cpp-sdk-authentication/DecisionApiTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
Change Permission from pair to a struct and
add missing resource field.
Resolves: OLPSUP-10514
> Refactor Permission structure in Decision API

- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.cpp
Google style dfoes not allow C-style casts
Resolves: OLPEDGE-2033
> Change C-style cast to C++

- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.h
Fix type conversion issue in QuadTreeIndex by changing
DataHeader::depth to unsgined type
Resolves: OLPEDGE-2033
> Fix type conversion issue

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
Move operator= and move constructor of AuthenticationClient class
to cpp file to prevent 'use of undeclared AuthenticationClientImpl'
error.
Resolves: OLPEDGE-2079
> Move some function bodies to cpp

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test-mock.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/functional/utils/DefaultResponses.h
- tests/functional/utils/MockServerHelper.cpp
- tests/functional/utils/MockServerHelper.h
Added GenerateQuadTreeResponse() mock server default response.
Added functional test for GetAggregatedData using mock server.
Resolves: OLPEDGE-1933
> fv test for VersionedLayerClient::GetAggregatedData()

- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteIndexLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
Use defines from HttpStatusCodes.h instead of hard-coded values
in functional tests.
Relates-To: OLPEDGE-686
> Change hard-coded values to HttpStatusCodes

- olp-cpp-sdk-core/include/olp/core/client/HRN.h
- olp-cpp-sdk-core/src/client/HRN.cpp
- olp-cpp-sdk-core/tests/client/HRNTest.cpp
- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/IndexLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-write/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-write/src/IndexLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.cpp
This commit takes care of the deprecated elements which were marked as
to be removed or move to private by 05.2020.
This includes the following changes:
* Moved all members of HRN class to private and adapted to coding style
* Removed dataservice::write::VersionedLayerClient::CancelAll()
* Removed dataservice::write::VolatileLayerClient::CancelAll()
* Removed dataservice::write::IndexLayerClient::CancelAll()
Relates-To: OLPEDGE-1457
> Removed or marked as private deprecated elements.

- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Use GetAggregatedTile functionality to query and cache quad tree.
Remove unnecessary tests
Relates-To: OLPEDGE-2083
> Change usage Index to QuadTreeIndex for GetData(TileRequest)

- README.md
URL was updated due to renaming on Azure project
from github to here-data-sdk.
Resolves: OLPEDGE-2082
> Update job status badges on Azure CI

- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.h
- olp-cpp-sdk-dataservice-read/tests/QuadTreeIndexTest.cpp
Add converting QuadTreeIndex to IndexData.
Needed for bypass QuadTreeIndex.
Add unit tests.
Relates-To: OLPEDGE-2084
> Add QuadTreeIndex GetIndexData

- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
DefaultCache storing expiry time with 1sec accuracy. These tests using
expiry equal to 1sec and that cause different behaviour from run to run.
Resolves: OLPEDGE-2022
> Increase test expiry time.

- azure-pipelines.yml
Switched to ubuntu 20.04 image for 1 psv build job.
Nothing should change, because isseu  was on Axure side with
installing packages for 18.04.
Resolves: OLPEDGE-AZURE
> Switch to ubuntu 20.04 due to Azure 18.04 issue

- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
std::iota used to generate QuadTreeIndex response. Its require <numeric>
include for build.
Resolves: OLPEDGE-2120
> Missing <numeric> include.

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationMockedResponses.h
Sign with Google token is not supported anymore and so marked as
deprecated.
Resolves: OLPEDGE-2087
> Mark SignInGoogle as deprecated.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PrefetchRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTestBase.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/HttpResponses.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
Change caching to QuadTreeIndex.
Always query depth 4. Update tests.
Relates-To: OLPEDGE-2084
> Implement Prefetch caching with QuadTreeIndex

- docs/GettingStartedGuide.md
The link to the API reference is broken.
Relates-to: OLPEDGE-2146
> Fix a link

- .ort.yml
Mitigating incorrect license detected by OSS Review Toolkit
Resolves: OLPEDGE-2013
> OSS Incorret License detection mitigation

- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
Test executing synchronously because task_scheduler is nullptr and
expects to cancel StartBatch() call. This is not correct.
Resolves: OLPEDGE-2167
> Fix CancelAllBatch test.

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/client/ApiLookupClient.h
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/client/DefaultLookupEndpointProviderTest.cpp
DefaultLookupEndpointProvider used if user didn't provide any custom
lookup_endpoint_provider. This is preparation before adding
ApiLookupClient.
Resolves: OLPEDGE-1695
> Default lookup api provider.

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/DataCacheRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsCacheRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
Add implementation to VersionLayerClientImpl
if partition/tile cached. Added check to
DataCacheRepository if data handle cached.
Add tests for PartitionCacheRepository to check
if partition is cached.
Relates-To: OLPEDGE-2111
> Add check if partition/tile cached

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/client/FetchOptions.h
- olp-cpp-sdk-core/include/olp/core/client/model/Api.h
- olp-cpp-sdk-core/src/client/parser/ApiParser.cpp
- olp-cpp-sdk-core/src/client/parser/ApiParser.h
This is preparation for ApiLookupClient update. Classes taken from
dataservice::read. They are required for lookup request and parsing its
result.
> Adding model::Api and FetchOptions to core.

- olp-cpp-sdk-core/include/olp/core/client/OlpClient.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
In the scope of merging same requests, to avoid multiple downloads of
same data, OlpClient with its URL based API and used by all repositories
for request will play a major role in merging this requests, i.e.
keeping an own list of pending requests. For this a more effective way
of sharing it is needed, except wrapping it in std::shared_ptr. Thus
turing OlpClient into a shared pimpl class is an easy way to achieve
the desired level of shareability.
Relates-To: OLPEDGE-1805
> Make OlpClient a shared pimpl class.

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.h
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Search for tile in quadtree. If data handle was found,
remove data. Check if at least one data for tile exist,
if not remove quad tree. Fix tests to work with quadtree.
Relates-To: OLPEDGE-2124
> RemoveFromCache with TileKey and QuadTree

- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/include/olp/core/cache/KeyValueCache.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- tests/integration/olp-cpp-sdk-core/DefaultCacheTest.cpp
Add interface functions Protect/Release.
Protect used mark keys as  non-evictable that they should stay in cache,
till their state will be changed back after calling Release with that keys.
Calling Protect function with some keys and prefixes
adds them to protected list, which guarantee that keys
will never be evicted or expired, even if LRU eviction is used,
and expiration is set. Keys could be protected before,
or after they were added to cache. If key was protected before,
and expiration is set, it will be written to cache with expiration, but 
never removed from cache after time elapsed. If key was protected
after, and still in cache, after expiration it will be returned to user, without
considering expiration. In both cases protected keys are not added to lru, 
so they will never be …
> Add Protect/Release functionality

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Add functionality to check if certain tile/partition is cached.
For partition we are checking if data handle is found in cache,
if  data handle exist, check if data for corresponding partition 
in cache. 
For tile key search corresponding QuadTreeIndex,
considering that depth for all cached QuadTreeIndex is 4.
If quad tree is found, which should contain our tile, read 
data handle for that tile. If data handle exist, check if data 
for corresponding tile is cached. 
Add integration tests for to check if partition and tile is cached.
Get partition and tile. Check if it is in cache using IsCached
function. Remove partition/tile with RemoveFromCache function and
check again that it is no longer cached.
Relates-To: OLPEDGE-2111
> Add api to check if partition/tile cached

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/src/client/api/PlatformApi.cpp
- olp-cpp-sdk-core/src/client/api/PlatformApi.h
- olp-cpp-sdk-core/src/client/api/ResourcesApi.cpp
- olp-cpp-sdk-core/src/client/api/ResourcesApi.h
- olp-cpp-sdk-core/src/client/repository/ApiCacheRepository.cpp
- olp-cpp-sdk-core/src/client/repository/ApiCacheRepository.h
This is preparation before ApiLookupClient update. ApiCacheRepository
needed to handle cache, PartitionApi and PlatformApi for apis
requests.
> Support classes for ApiLookupClient

- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
Add ApiKey support to OlpClient. ApiKey has
higher priority than OAuth2 token provider.
Resolves: OLPEDGE-2157
> Add ApiKey support to OlpClient

- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
Tiles in PrefetchRequest have levels, which is greater than min
level and sibiling tiles skiped.
Test requests tiles on levels 10 and 12, but root tile on
level 11. Result should be one tiles on levels 10 and 12,
and 4 child tiles.
Relates-To: OLPEDGE-2193
> Fix PrefetchWithCancellableFuture test

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/client/ApiLookupClient.h
- olp-cpp-sdk-core/src/client/ApiLookupClientImpl.cpp
- olp-cpp-sdk-core/src/client/ApiLookupClientImpl.h
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/client/ApiLookupClientImplTest.cpp
Pimpl part of ApiLookupClient. Also added unit tests similar to
dataservice::read::ApiClientLookup.
> Adding ApiLookupClientImpl

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/client/ApiLookupClient.h
- olp-cpp-sdk-core/src/client/ApiLookupClient.cpp
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-core/ApiLookupClientTest.cpp
Connect public and pimpl parts. After that ApiLookupClient can be
used by dataservice libs instead of internal functionality.
> Adding ApiLookupClient

- external/boost/CMakeLists.txt
Fix boost build on windows by placing CMAKE_COMMAND in quotas
to prevent wrong interpretation of spaces in path.
Resolves: OLPSUP-11126
> Fix boost windows build

- scripts/linux/nv/gitlab_cppcheck_and_upload_sonar.sh
When add below variables cppcheck is able to detect correct macros.
Then we have report without "cppcheck:syntax errors".
Also add minor comment to define purpose of this script.
Resolves: OLPEDGE-2090
> Fix syntax error in cppcheck code analysis

- olp-cpp-sdk-authentication/include/olp/authentication/AuthorizeResult.h
- tests/integration/olp-cpp-sdk-authentication/AuthenticationMockedResponses.h
* Fix olp::authentication::Permission class which was missing
default initializer for decision field.
* Change kAuthorizeResponseValid to contain 'decision' field
in Permission array instead of 'effect' field that was causing
integration test AuthenticationClientTest.Authorize to fail.
Resolves: OLPEDGE-2190
> Fix failed integration test

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
Protect tile keys from eviction and expiration.
If some tile key was marked as protected, it is
expected to stay in cache, that its data can be
accessible.
For protecting tile keys we should protect some
keys in cache. This means find quad tree which
contains data hanle for our key, protect this
quad tree and protect data with found data handle.
At least one tile key needs to be protected to
protect entire quad tree.
Added unit test with changed default expiration,
which requests 2 tiles within one quad tree and
caches it. After calls protect on tile keys,
3 keys should be protected, this means they do
not expire after timeout.
Relates-To: OLPEDGE-2126
> Add Protect tile keys functionality

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
Remove the atomic bool flag.
When the task is canceled, the callback is called with a cancel
error, so there is no need to create it manually.
Add the IsCached check to VolatileLayerClient prefetch.
> Simplify the prefetch task.

- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
CatalogRepository contains only static methods and they all are taking
HRN and OlpClientSettings as args. Moving these args to constructor
will simplify further extending, e.g. with ApiClientLookup.
Resolves: OLPEDGE-2200
> Remove static from CatalogRepository methods.

- olp-cpp-sdk-dataservice-read/src/PrefetchJob.cpp
- olp-cpp-sdk-dataservice-read/src/PrefetchJob.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
Add a PrefetchJob class to help track the prefetch progress
Remove the usage of std::future and additional task that wait for
them.
> Remove the futures from prefetch

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VolatileLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/PrefetchRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVolatileLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientPrefetchTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
Prefetch works with input parameters min and max levels. Defaults 
levels should indicate that user wants to get only tiles in request. 
As level 0 is valid, min and max values for request is initialized as 
invalid, that during reques we can distinguish if levels was set by 
user. Fix tests to run with default initialized levels instead of 0/0.
Relates-To: OLPEDGE-2198
> Change Prefetch default levels

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
PartitionsRepository contains only static methods and they all are taking
HRN and OlpClientSettings as args. Moving these args to constructor
will simplify further extending, e.g. with ApiClientLookup.
Resolves: OLPEDGE-2200
> Remove static from PartitionsRepository methods.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Remove deprecated constructor from VersionedLayerClient.
Now user must use constructor wich has catalog version
parameter
Resolves: OLPEDGE-2189
> Remove deprecated constructor

- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVolatileLayerClientTest.cpp
When requesting tiles we should get tiles
only on input levels, if default levels not set.
Filter quads to be on requested levels, and
have relation parent/child with root tiles from
request.
Relates-To: OLPEDGE-2204
> Fix Prefetch volatile test

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
DataRepository contains only static methods and they all are taking HRN
and OlpClientSettings as args. Moving these args to the constructor
will simplify further extending, e.g. with ApiClientLookup.
Resolves: OLPEDGE-2200
> Remove static from DataRepository methods.

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- olp-cpp-sdk-dataservice-read/tests/PrefetchRepositoryTest.cpp
PrefetchTilesRepository contains only static methods and they all are
taking HRN and OlpClientSettings as args. Moving these args to the
constructor will simplify further extending, e.g. with ApiClientLookup.
Resolves: OLPEDGE-2200
> Remove static from PrefetchTilesRepository methods.

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
When requesting tiles we should get success
even with empty vector of tiles result .
If default levels set return tile not found
for each tile from request.
Add tests to check empty tiles result.
Relates-To: OLPEDGE-2204
> Fix Prefetch empty responce

- olp-cpp-sdk-core/include/olp/core/client/ApiLookupClient.h
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PrefetchRepositoryTest.cpp
We have new ApiLookupClient class in the core for Api requests. It
should replace internal ApiClientLookup for both read and write libs.
New lookup shared between repositories, so only one OlpClient used for
api requests, this will help to merge requests for same client.
> Adapt dataservice::read to ApiLookupClient.

- tests/functional/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVolatileLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientPrefetchTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Clients API designed to be used async, so tests should use same
approach too. Adding task scheduler to such tests will do the job.
Resolves: OLPEDGE-2176
> Make integration and funcitonal tests async.

- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.h
Repositories already use new ApiLookupClient, but StreamLayerClient
request API directly calling LookupApi. Updating it separately from
other clients.
Resolves: OLPEDGE-1698
> Adapt read::StreamLayerClient to ApiLookupClient.

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/client/ApiLookupClient.h
- olp-cpp-sdk-core/include/olp/core/client/DefaultLookupEndpointProvider.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/src/client/ApiLookupClientImpl.cpp
- olp-cpp-sdk-core/tests/client/ApiLookupClientImplTest.cpp
User can specify own endpoint provider through OlpClientSettings. The
provider help to specify custom urls for catalog partition.
OlpClientSettings.h needs ApiLookupClient.h for default provider. That
cause include loop. Moving the default provide to sepparate file will
fix the issue and make OlpClientSettings not dependent on clients.
Resolves: OLPEDGE-1696
> Add lookup API endpoint provider settings.

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Protect adds tile keys to protected list.
If some tile key was marked as protected, it is expected to stay in
cache, that its data can be accessible.
Release keys, which was marked before as protected. After releasing tile
keys associated data in cache could expire or be evicted.
Protect and Release functionality searches for quad tree in cache to get
data handle for each tile. When protecting tiles, at least one tile is
needed to be protected to also add quad to protected list. When
releasing all tiles should be not protected to release quad.
Added integration test with protecting and releasing tiles
keys under common quad tree.
Relates-To: OLPEDGE-2127
> Add Protect/Release tile keys

- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/generated/IngestApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/IngestApi.h
Automatically add Content-Encoding header to StreamLayerClient,
needed for gzip streams (when the Stream layer is configured as
compressed on the platform). Without this header the server responds
with status 400 Bad Request. Currently user have to manually compress
the payload that he wants to send, however when downloading, the
content is unziped automatically by network libraries.
Resolves: OLPEDGE-11219
> Add Content-Encoding header to StreamLayerClient

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test-mock.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientProtectTest.cpp
Prefetch tiles and store in cache, so that maximum treshhold before
eviction is reached. Protect saved keys. Prefetch some other keys.
As treshold is reached an keys is protected, during prefetch previous
tile data is evicted, so in cache stays all protected keys and last
prefetched. Release protected keys and request some tile. Tile, which
was previously released was evicted.
Relates-To: OLPEDGE-2128
> Add Protect/Release functional test

- olp-cpp-sdk-core/include/olp/core/client/ApiLookupClient.h
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/src/client/ApiLookupClientImpl.cpp
- olp-cpp-sdk-core/tests/client/ApiLookupClientImplTest.cpp
- tests/integration/olp-cpp-sdk-core/ApiLookupClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Api url can be static. In such cases we can avoid lookup request and
save some time. For that purpose we are adding CatalogEndpointProvider
to ApiLookupSettings.
ApiLookupClient will try to get url using the provider from settings
instead of making api lookup request. If it can't be done, behavior
of the client is unchanged.
Also adding unit and integration test for ApiLookupClient.
Resolves: OLPEDGE-2187
> Adding CatalogEndpointProvider.

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
- olp-cpp-sdk-core/src/cache/DiskCacheSizeLimitEnv.cpp
- olp-cpp-sdk-core/src/cache/ReadOnlyEnv.cpp
- olp-cpp-sdk-core/src/cache/ReadOnlyEnv.h
- olp-cpp-sdk-core/src/cache/SizeCountingEnv.h
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
- olp-cpp-sdk-core/tests/cache/Helpers.cpp
- olp-cpp-sdk-core/tests/cache/Helpers.h
It should be possible to use protected cache from a read-only partition. Level DB writes some metadata when opening existing DB. Add environment overload that does not write anything to disk but reports success.
> Allow using immutable cache from a read only partition

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/ProtectedKeyList.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
- olp-cpp-sdk-dataservice-read/src/ProtectDependencyResolver.cpp
- olp-cpp-sdk-dataservice-read/src/ProtectDependencyResolver.h
- olp-cpp-sdk-dataservice-read/src/ReleaseDependencyResolver.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientProtectTest.cpp
pubsetbuf is dependent on the library implementation,
so setting buffer for istream changed.
Move Protect implementation from VersionedLayerClient
to ProtectDependencyResolver.
Add tests for cache to check that Protect/Release works
only with mutable cache.
Relates-To: OLPEDGE-2034
> Fix reading protected list from cache

- olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
- olp-cpp-sdk-core/tests/client/TaskContextTest.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
This allows us to use different types of return types, for example to
use ExtendedApiResponse as the output of task Exec function.
Adapt prefetch code to use task result, instead of multiple returns.
> Adapt TaskContext to other types of response

- olp-cpp-sdk-core/tests/cache/Helpers.cpp
- scripts/windows/build.sh
Fix broken windows build for Core unittests.
Enable test build on windows.
Resolves: OLPEDGE-2228
> Fix windows build

- olp-cpp-sdk-dataservice-read/src/ReleaseDependencyResolver.cpp
- olp-cpp-sdk-dataservice-read/src/ReleaseDependencyResolver.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/PrefetchRepositoryTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientProtectTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
While prefetching quad trees we need to slice
tiles for requests from max level to min level
with predefined depth 4. In case if min level
allows to go up, we will request quad tree on
minimum possible level with depth 4. When min
level is to low we will start from 0 level, but
should continue slicing considering max level
and go up.
Changes related to not changing max level,
that we always have minimum requests, even if
some quads overlap.
Relates-To: OLPEDGE-2225
> Minimize quad trees requests for prefetch

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.h
- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- olp-cpp-sdk-core/src/client/PendingUrlRequests.cpp
- olp-cpp-sdk-core/src/client/PendingUrlRequests.h
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/client/PendingUrlRequestsTest.cpp
Both classes will be used by OlpClient to merge same URL requests and
thus avoid requesting the same data multiple times. For this a change
is needed in HttpResponse to handle the std::stringstream copy on
copy constructor and copy assignment operator. Without this it is not
possible to copy an existing HttpResponse and return it to multiple
waiting callbacks. At the same time we deprecate the public members
of HttpResponse and prepare it to be changed by 01.2020 into a shared
pimpl class so that we do not need to deep copy the responses.
The PendingUrlRequest class manages one Network request, for which it
remebers the request id and is able to cancel it, and is able to hold
one or multiple response callback. It also handles correctly one, more
or all callbacks cancellation scenarios, …
> Adds PendingUrlRequests and PendingUrlRequest.

- olp-cpp-sdk-dataservice-read/src/PrefetchJob.cpp
- olp-cpp-sdk-dataservice-read/src/PrefetchJob.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
For prefetch method we accumulate bytes uploaded/downloaded during
query tree requests so the users receive a bit more precise numbers.
Relates-To: OLPEDGE-2217
> Add metadata network stats to prefetch status.

- CMakeLists.txt
- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-network-test.sh
- tests/functional/network/CMakeLists.txt
- tests/functional/network/NetworkTestBase.cpp
- tests/functional/network/NetworkTestBase.h
We are going to add bunch of functional network tests. Mock server
will help to simulate corner test cases. Added script will be used to
launch test and server separately from other fv tests.
Resolves: OLPEDGE-2211
> Setup for network fv tests.

- tests/functional/network/CMakeLists.txt
- tests/functional/network/DestructionTest.cpp
- tests/functional/network/NetworkTestBase.cpp
- tests/functional/network/NetworkTestBase.h
- tests/utils/mock-server-client/Client.h
- tests/utils/mock-server-client/Expectation.h
Adding fv network test. Goal of the test is to check callback is
called if network destroyed. Also added possibility to set response
delay to be sure the requests are not finished before the destruction.
Resolves: OLPEDGE-2061
> Destruction network test.

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
Additionally remove the deprecated usage guards.
Resolves: OLPEDGE-2203
> Fix the gcc warn on maybe uninitialized variable

- olp-cpp-sdk-dataservice-read/src/PrefetchJob.cpp
- olp-cpp-sdk-dataservice-read/src/PrefetchJob.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/VolatileBlobApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/VolatileBlobApi.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- olp-cpp-sdk-dataservice-read/tests/PrefetchRepositoryTest.cpp
Improve prefetch by splitting the quadtree requests to tasks, so
all the query requests are performed in parallel.
Remove layer and request from PrefetchTilesRepository methods, move
them to the constructor, request substituted with billing tag.
Prefetch job class takes control over prefetching, clients must
provide functions used to download metadata, filter the tiles to
download (optional), and download method.
Relates-To: OLPEDGE-2217
> Prefetch improvement, split the requests to tasks

- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/src/client/OlpClientSettings.cpp
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClient.h
- olp-cpp-sdk-dataservice-write/src/StreamLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/tests/StreamLayerClientImplTest.cpp
Remove deprecated WithVersion/GetVersion from PrefetchTilesRequest.h
Remove deprecated CreateDefaultCache method from StreamLayerClient.h
Remove deprecated backdown_policy from OlpClientSettings.
Resolves: OLPEDGE-1945, OLPEDGE-2241, OLPEDGE-2242
> Remove deprecated methods

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- tests/functional/network/CMakeLists.txt
- tests/functional/network/TimeoutTest.cpp
Adding fv network test. Test goal is to check request is failed after
specified timeout and callback is called. According to docs,
CURLOPT_TIMEOUT is a timeout for transfer part, so fixing this value.
Resolves: OLPEDGE-2066
> Timeout network test.

- tests/functional/network/CMakeLists.txt
- tests/functional/network/ConcurrencyTest.cpp
Adding fv network test. Test goal is to check network requests are
concurrent. We make several requests, first and last one are delayed,
so their responses received in the end of the test.
Resolves: OLPEDGE-2060
> Concurrency network test

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Enable the user to prefetch a list of aggregated tiles.
When the tile does not exists, the prefetch algorithm scans the tree
to find the nearest parent.
Resolves: OLPEDGE-2245
> Enable the prefetching of aggregated tiles

- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
Test error fixed some time ago by commit 0332b0d5d. This is small
update to make the test fail instead of throwing boost exception.
Resolves: OLPEDGE-2102
> Update MutableCacheExpired test.

- azure-pipelines.yml
20.04 and 18.04 have both the same issues.
Due to issues detected on Azure CI we need to switch
back to 18.04 urgently. Issue is related to some temporary
IP reachability error on cloud:
404  Not Found [IP: 51.104.174.161 80]
Add --fix-missing and apt-get update
I found a fix for this https://github.com/actions/virtual-environments/issues/675#issuecomment-671057659
Relates-To: OLPEDGE-2119
> [CI]Switch back to 18.04 Ubuntu

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
Protect, Release and RemoveFromCache are sync and offline methods. If
versioned client created with boost::none version and no online calls
made yet, version is not initialized. In that case, the methods should
fail.
Resolves: OLPEDGE-2255
> Correct Protect, Release and RemoveFromCache.

- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientGetDataTest.cpp
Move following read versioned layer client tests to
use mock server instead of real server to make tests
more reliable.
Moved tests:
* GetDataWithHandle
* GetDataWithInvalidLayerId
* GetDataWithPartitionIdVersion2
Resolves: OLPEDGE-1972, OLPEDGE-1973, OLPEDGE-1974
> Move tests to mock server

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- tests/common/ReadDefaultResponses.h
- tests/functional/network/CMakeLists.txt
- tests/functional/network/DataCallbackTest.cpp
Add new DataCallbackTest network test. Test goal is to download some
big data in chunks and check data_callback works correctly.
For windows, data_callback offset is always 0, so fixing the bug too.
Resolves: OLPEDGE-2065
> DataCallbackTest fv network test.

- olp-cpp-sdk-dataservice-write/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/src/CatalogSettings.cpp
- olp-cpp-sdk-dataservice-write/src/CatalogSettings.h
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/generated/BlobApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/BlobApi.h
- tests/integration/olp-cpp-sdk-dataservice-write/IndexLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/VolatileLayerClientTest.cpp
Add Content-Encoding header to requests in olp::dataservice::write
module. Content-Encoding added based on layer settings received from
OLP Platform.
Resolves: OLPSUP-11354
> Add Content-Encoding header to requests

- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/JsonResultParserTest.cpp
Json parser returns error if parse
fail. Add test to check parsing success
with valid responce and fails with
invalid json.
Relates-To: OLPEDGE-2147
> Tests for parse_result

- olp-cpp-sdk-core/src/logging/MessageFormatter.cpp
- olp-cpp-sdk-core/tests/logging/FileAppenderTest.cpp
- olp-cpp-sdk-core/tests/logging/LogTest.cpp
Add timestamp to default logging including miliseconds.
Minor code style changes in MessageFormatter.cpp
Resolves: OLPEDGE-2239
> Add timestamp to default logging

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- tests/common/CMakeLists.txt
- tests/common/ReadDefaultResponses.cpp
- tests/common/ReadDefaultResponses.h
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerGetAggregatedDataTest.cpp
Fix the GetAggregatedData behavior when the aggregated
tile root is too far away, for example, the tile on level 14 is
aggregated in tile on level 1, it means that the tile could be found
on levels 10-14, and tiles on levels 1-9 can't be found anymore.
In such a case we iterate up and fetch quadtrees until the aggregated
tile root is found in tree subquads. So it could be found later by
other APIs, ex. Protect, Release, Remove, etc.
Resolves: OLPSUP-11651
> Fix the GetAggregatedData behavior

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
DefaultCache::Put value is ValueTypePtr. If the value is nullptr the
crash will occur. Adding check for the value and unit test.
Resolves: OLPEDGE-2295
> Fix crash in DefaultCache::Put with nullptr value

- tests/common/ReadDefaultResponses.cpp
Fix the incorrect datahandle in mock tests, should be a unique name
Relates-To: OLPEDGE-2299
> Fix the incorrect datahandle in mock tests

- olp-cpp-sdk-core/tests/cache/Helpers.cpp
Helpers.cpp contains overloaded MakeDirectoryContentReadonly function.
1st one translates std::string into TCHAR* and call 2nd one, but at
least on windows compiler translates TCHAR* into std::string again and
infinite recursion occur.
Resolves: OLPEDGE-2270
> Fix MakeDirectoryContentReadonly recursion loop.

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.h
When network destroyed, all pending requests callbacks should receive
OFFLINE_ERROR. To process them correctly, we need to stop
CompletionThread before closing WinHttp handles. Otherwise, it will
treat all pending requests as cancelled.
Resolves: OLPEDGE-2247
> Fix NetworkWinHttp error for pending requests.

- olp-cpp-sdk-dataservice-write/src/CatalogSettings.cpp
- olp-cpp-sdk-dataservice-write/src/CatalogSettings.h
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/tests/VersionedLayerClientImplPublishToBatchTest.cpp
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-dataservice-write/VersionedLayerClientPublishToBatchTest.cpp
write::VersionedLayerClient::PublishToBatch use async approach. We
need to make it similar to dataservice::read clients. Making it sync
will simplify the code. Also added unit and integration tests to
improve coverage.
Resolves: OLPEDGE-1404
> Change PublishToBatch() to use sync repo.

- tests/functional/utils/MockServerHelper.cpp
There are two issues cause authentication errors. Auth response was
mocked with "true" as http_status argument. Also response json was
incorrect and incomplete.
MockTimestamp has same problem with http_status, so updating it too.
Resolves: OLPEDGE-2259
> Fix auth with mock server.

- scripts/misc/api_compliance.sh
Add cmake -fvisibility=hidden to API Backward compatibility job.
Disable building tests as not needed there.
Build type also changed to RelWithDebInfo.
Needed for better report. Many internal changes
will be hidden now. Only public changes needed in report.
Relates-To: OLPEDGE-2256
> Add cmake -fvisibility=hidden for API BC job

- README.md
We support armhf as we have CI jobs for it.
Relates-To: OLPEDGE-654
> Fix supported platforms in README

- .travis.yml
- scripts/misc/cpplint_ci.sh
Now cpplint job will run in a parallel instead of consecutively.
Relates-To: OLPEDGE-1853
> Move cpplint to separate Travis job

- scripts/misc/cpplint_ci.sh
Cpplint job was done unblocked without previous research.
Due to many warnings we need to keep cpplint unblocking.
Relates-To: OLPEDGE-1853
> Make cpplint job unblocking again

- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/generated/PublishApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/PublishApi.h
- tests/integration/olp-cpp-sdk-dataservice-write/VersionedLayerClientTest.cpp
Change write::VersionedLayerClient::CancelBatch()
to use sync approach instead of async. This
simplifies code and improves code stability.
Resolves: OLPEDGE-1405
> Change CancelBatch() to be sync.

- olp-cpp-sdk-dataservice-read/src/ProtectDependencyResolver.cpp
- olp-cpp-sdk-dataservice-read/src/ReleaseDependencyResolver.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- olp-cpp-sdk-dataservice-read/tests/PartitionsCacheRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
Change the PartitionsCacheRepository, PartitionsRepository.
Move layer_id from member function to constructor since it never
changes.
Reorder the arguments to following template: request, version, etc.
Relates-To: OLPEDGE-2312
> Minor: Modify the repositories

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/src/thread/PriorityQueueExtended.h
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/thread/PriorityQueueExtendedTest.cpp
Priority queue is needed for requests priority feature. It will be
used by ThreadPoolTaskScheduler. We could use std::priority_queue
instead, but it's not respect order of requests with same priority.
The class has same complexity and similar API as the stl one and also
values with equal priority follow FIFO logic.
PriorityQueueExtended has API like std::queue, because it should be
used as SyncQueue container. Its conflicting with our code style. Impl
class added to split conflicting part from implementation.
Resolves: OLPEDGE-2305
> Add priority queue class.

- olp-cpp-sdk-core/include/olp/core/thread/TaskScheduler.h
- olp-cpp-sdk-core/include/olp/core/thread/ThreadPoolTaskScheduler.h
- olp-cpp-sdk-core/src/thread/ThreadPoolTaskScheduler.cpp
- olp-cpp-sdk-core/tests/thread/ThreadPoolTaskSchedulerTest.cpp
- olp-cpp-sdk-dataservice-read/src/Common.h
- olp-cpp-sdk-dataservice-read/src/repositories/ExecuteOrSchedule.inl
Overloading EnqueueTask() method with priority input. Now enqueued
requests will be executed in priority order. Request with same
priority follow FIFO approach. thread::Priority is a helper enum,
NORMAL=500 is a default priority for tasks.
Resolves: OLPEDGE-2306
> Make TashScheduler support requests priority.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
- olp-cpp-sdk-dataservice-read/src/PrefetchHelper.h
- olp-cpp-sdk-dataservice-read/src/QueryMetadataJob.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
In previous commits we added priority to ScheduleTask(). Adding option
for user to set prefetch priority. Default value is Priority::LOW=100.
Resolves: OLPEDGE-2307
> Add priority to PrefetchTilesRequest

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/TileRequest.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Adding an option for user to set GetData() and GetAggregatedData()
requests priority. Default value is Priority::NORMAL=500.
Resolves: OLPEDGE-2308
> Add priority to TileRequest

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataRequest.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
Adding an option for user to set GetData(DataRequest) requests
priority. Default value is Priority::NORMAL=500.
Resolves: OLPEDGE-2309
> Add priority to DataRequest

- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/generated/IndexApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/IndexApi.h
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteIndexLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/IndexLayerClientTest.cpp
Change write::IndexLayerClient::PublishIndex() to use sync
method approach. We need to make it similar to
dataservice::read. Making it sync will simplify the code.
Resolves: OLPEDGE-2301
> Change PublishIndex() to be sync

- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.h
- olp-cpp-sdk-dataservice-write/src/generated/QueryApi.cpp
- olp-cpp-sdk-dataservice-write/src/generated/QueryApi.h
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/VolatileLayerClientTest.cpp
Make write VolatileLayerClient::PublishPartitionData()
method use new sync approach
Resolves: OLPEDGE-2301
> Make PublishPartitionData sync

- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteIndexLayerClientTest.cpp
Change expected message in
DataserviceWriteIndexLayerClientTest.PublishNoLayer test to
proper one.
Resolves: OLPEDGE-2322
> Fix functional test

- olp-cpp-sdk-dataservice-read/src/PrefetchHelper.h
- olp-cpp-sdk-dataservice-read/src/QueryMetadataJob.h
- olp-cpp-sdk-dataservice-read/src/TaskSink.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.h
Add a new TaskSink class to handle the tasks creation and enqueuing.
Fix a scenario when the task could be enqueued during destruction.
Relates-To: OAM-695
> Add a TaskSink internal class.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchPartitionsResult.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/PrefetchedPartitions.h
Add PrefetchPartitions result types
Add PrefetchedPartitions class, which
contains all downloaded partitions.
Add alias for PrefetchPartitionsResponse
and PrefetchPartitionsResponseCallback.
Relates-To: OLPEDGE-1902
> Add PrefetchPartitions result types

- olp-cpp-sdk-dataservice-write/src/generated/model/Catalog.h
Set uninitialized member in
write::model::Notifications to false
Resolves: OLPEDGE-2310
> Fix uninitialized member

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.h
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
Change the logic of GetLatestVersion, so in the case of fetch option is
OnlineIfNotFound, we check the online first, then in case of an error,
the cache is checked. It is needed in the use case when you need to get
the latest data from online, and be able to use the data from cache.
Remove the five minutes expiration of the latest version, this enables
the users to work with data offline with ease.
Relates-To: OLPEDGE-2325, OLPEDGE-2326
> Inverse the GetLatestVersion logic.

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchPartitionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchStatus.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.h
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
Add MetadataApi and QueryApi metods wich returns
extended responce. Add GetPartitionsExtendedResponse to
PartitionsRepository, which returns extended response.
Add PrefetchPartitionsRequest and PrefetchPartitionsStatus. 
Relates-To: OLPEDGE-1902
> Add GetPartitions extended response

- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerGetAggregatedDataTest.cpp
Fix test
VersionedLayerGetAggregatedDataTest.ParentTileFarAway
which was failing on second run due to directory leftovers.
Resolves: OLPEDGE-2335
> Fix test second run

- codecov.yml
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
In case if we do not request version
online CatalogVersionResponse variable
stays initialized bu default with
error code unknown. If getting from cache
also fails we do not exchange result,
so it should be NotFound.
Relates-To: OLPEDGE-2339
> Init get version response.

- olp-cpp-sdk-dataservice-read/src/DownloadItemsJob.h
- olp-cpp-sdk-dataservice-read/src/PrefetchPartitionsHelper.h
- olp-cpp-sdk-dataservice-read/src/PrefetchTilesHelper.h
- olp-cpp-sdk-dataservice-read/src/QueryMetadataJob.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
- tests/common/ReadDefaultResponses.h
- tests/common/UrlGenerators.h
Add implementation to prefetch partitions.
Split partitions requests for blocks by 100.
Query data handles for partitions and
download data. Add unit test
to check if after prefetched data is available
in cache.
Relates-To: OLPEDGE-1902
> Add PrefetchPartitions implementation

- README.md
Travic CI and Gitlab images which we use for compile
verification alrady use GCC 7.5 for month or more after
Ubuntu bionic added it as supported version.
So we started compiling for it, but missed updating README.md.
It was detected that README.md need to be updated during
job logs checking.
See example of travis job:
https://travis-ci.com/github/heremaps/here-data-sdk-cpp
or any linux FV build job in Gitlab.
Armhf image will use 7.5 too after updates soon.
Relates-To: OAM-700
> Update compiler versions in readme

- olp-cpp-sdk-dataservice-read/src/ProtectDependencyResolver.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerPrefetch.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerTestBase.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerTestBase.h
Fix the prefetch API behavior for the aggregated tiles when the
aggregated tile is too far away. A new approach is to download and
store quadtrees of lower levels until the needed aggregated tile is
placed in sub quads (which means that we can find it later).
Relates-To: OLPEDGE-2312
> Fix the prefetch for the aggregated tiles.

- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
- tests/common/ApiDefaultResponses.h
- tests/common/CMakeLists.txt
- tests/common/PathGenerator.cpp
- tests/common/PathGenerator.h
- tests/common/PlatformUrlsGenerator.cpp
- tests/common/PlatformUrlsGenerator.h
- tests/common/ResponseGenerator.cpp
- tests/common/ResponseGenerator.h
Integration tests should have dependency only
from public dataservice api. Move generating
urls and responses to test-common lib.
Relates-To: OLPEDGE-1901
> Add responses generator to test-common lib.

- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
- tests/common/ApiDefaultResponses.h
- tests/common/PlatformUrlsGenerator.cpp
- tests/common/PlatformUrlsGenerator.h
- tests/common/ResponseGenerator.cpp
- tests/common/ResponseGenerator.h
- tests/functional/utils/MockServerHelper.cpp
- tests/functional/utils/MockServerHelper.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerGetAggregatedDataTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerPrefetch.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerTestBase.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerTestBase.h
Change VersionedLayerTestBase to use PlatformUrlsGenerator.
Change ApiDefaultResponses to use Apis from olp::client namespace.
Relates-To: OLPEDGE-2312
> Minor changes in VersionedLayerTestBase

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/PrefetchPartitionsHelper.h
- olp-cpp-sdk-dataservice-read/src/QueryMetadataJob.h
- olp-cpp-sdk-dataservice-read/src/QueryPartitionsJob.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientPrefetchPartitionsTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerTestBase.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerTestBase.h
Add public api to prefetch partitions
for versioned layer client. Add integration
tests to check prefetching, handling errors,
canceling, request prioritization, request
progress. Change query to return error only if all query
partitions fail. Add test to check
if all possible partitions prefetched,
even if some queries fail, check if
error returned if all queries fails.
Relates-To: OLPEDGE-1901
> Add api to prefetch partitions.

- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
The published partiton Id must be equal to the trace Id of the respective request.
Resolves: OLPSUP-12034
> Fix published partition Id for streamed partitions of size bigger than 20MB

- olp-cpp-sdk-dataservice-read/src/repositories/CatalogCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
The user provided default expiration is passed to the
CatalogCacheRepository.
Resolves: OLPEDGE-2360
> Fix the expiration of the latest version.

- olp-cpp-sdk-core/src/http/ios/OLPHttpTask.mm
Add missing HTTP status code to IOS build
on task completion
Resolves: OLPEDGE-2340
> Add HTTP Status log to IOS

- olp-cpp-sdk-core/src/http/android/HttpClient.java
"Unsupported proxy version (0). Falling back to HTTP(0)."
This warning may occur when we selected to not use a proxy
Relates-To: OLPEDGE-2356
> Fixed the unexpected warning on Android

- olp-cpp-sdk-core/include/olp/core/porting/shared_mutex.h
Clang doesn't provide __addressof, instead using addressof
Relates-To: OAM-756
> Fixed shared_mutex for work with clang

- docs/GettingStartedGuide.md
- docs/authenticate.md
- docs/dataservice-cache-example.md
- docs/dataservice-read-catalog-example.md
- docs/dataservice-read-from-stream-layer-example.md
- docs/dataservice-write-example.md
* Modify the instruction on project authentication.
* As the Teams and Permissions guide will be deleted, and
the Identity & Access Management Developer Guide will be used instead,
update the links.
Relates-To: OLPEDGE-2364, OLPEDGE-2366
> Change the instruction on auth and update links

- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.h
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
Adding new Open/Close API for DefaultCache. Now it's possible to
disable protected or mutable cache, modify and enable it again. This
can be useful if for some reason we want to update individual cache
while DefaultCache is still in use.
Changed DiskCache behavior when try to open not existing folder for
read-only. Now it's creating folder and an empty leveldb DB.
Removed CreadteDir() function, since it's not used anymore and also
we have alternative util for that purpose(olp::utils::Dir::create()).
Resolves: OAM-731, OLPSUP-12312
Signed-off-by: Kostiantyn Zvieriev ext-kostiantyn.zvieriev@here.com
> DefaultCache Open()/Close() individual caches.

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
Now db and folder creation is independent for protected cache. Also
added a simple test for the case.
Resolves: OLPSUP-12312
> Make DiskCache create db if folder is an empty.

- olp-cpp-sdk-core/src/client/PendingUrlRequests.cpp
- olp-cpp-sdk-core/src/client/PendingUrlRequests.h
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Adapt PendingUrlRequest to be used by OlpClient.
This commit prepares the PendingUrlRequest class
to be used by the async OlpClient::CallApi() method.
This means we allow calling ExecuteOrCancel()
multiple times to cover the use case where you need
to retry the request when 429/5xx HTTP status was
returned and we allow the recycling of a pending
request instance so that we can accommodate the
retry which results in a new Network request id.
Additionally, this commit enhances logging in
PendingUrlRequest classes and NetworkCurl.
Relates-To: OLPEDGE-1805
> Adapt PendingUrlRequest to be used by OlpClient.

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/client/OlpClient.h
- olp-cpp-sdk-core/src/client/ApiLookupClientImpl.cpp
- olp-cpp-sdk-core/src/client/ApiLookupClientImpl.h
- olp-cpp-sdk-core/src/client/DefaultLookupEndpointProvider.cpp
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/tests/client/ApiLookupClientImplTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
This enables SDK to route user requests to the same OlpClient instances.
Needed to implement a proper request merging. Another benefit
for users is fewer cache lookups. The client is cached for a max-age time
provided by the server or one hour. When the URL is resolved from the
cache, we assume it will expire in five minutes.
Move DefaultLookupEndpointProvider source code to the cpp file.
Resolves: OLPEDGE-2230
> Enable OlpClient caching inside ApiLookupClient

- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test-mock.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
After renaming both testcases of VersionedLayerClientPrefetchTest
were running against real server, which is wrong.
Resolves: OLPEDGE-2380
> Switch VersionedLayerClientPrefetchTest to Mock

- tests/common/mocks/NetworkMock.cpp
- tests/common/mocks/NetworkMock.h
To integrate properly the merging of same url requests in OlpClient
NetworkMock needs to support injection of request_id from outside
so that we can simulate proper Network workflow.
Additionally we add full async to NetworkMock which now triggers all
responses on a separate thread.
Relates-To: OLPEDGE-1805
> Add proper request_id handling in NetworkMock.

- olp-cpp-sdk-core/include/olp/core/client/PendingRequests.h
- olp-cpp-sdk-core/src/client/ApiLookupClientImpl.cpp
- olp-cpp-sdk-core/src/client/PendingRequests.cpp
- olp-cpp-sdk-dataservice-read/src/TaskSink.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
The order of partition ids in the request matters. Worst case - two
parallel downloads. This is a temporary workaround.
Change the log in TaskSink to print the number of tasks pending.
Add a new method to PendingRequests to query a number of task
pending.
Fix a typo.
Resolves: OLPEDGE-2395
> Merge the parallel query partitions requests.

- olp-cpp-sdk-core/include/olp/core/client/OlpClient.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/src/client/PendingUrlRequests.cpp
- olp-cpp-sdk-core/src/client/PendingUrlRequests.h
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
This commit implements merging of same URL requests
for the async OlpClient::CallApi() method by using
the previously created PendingUrlRequest(s) classes.
The merging is only performed in case the request
does not have any body as this could alter the
response.
Additionaly this commit adds support for HEAD and
PATCH requests, already supported by the Network
layer.
OlpClientTests adapted and extended accordingly
with additional test cases. All other tests using
mocked networked changed to returning the callback
asynchronously.
Relates-To: OLPEDGE-1805
> Implements merging of same requests in OlpClient.

- olp-cpp-sdk-authentication/include/olp/authentication/UserAccountInfoResponse.h
Part of exposing user information. UserAccountInfoResponse is created
to store information about user account. It contains email, firstname,
lastname, phone number, etc.
Relates-To: OLPEDGE-2384
> Added UserAccountInfoResponse class

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
These two logs are triggered very often and produce a lot of output with
no extra information gain for production releases.
Moving it to debug level will lighten the output. Next step is to
enhance overall logging to consider more error cases and leave the good
results noise free.
Resolves: OLPSUP-12666
> Lower log levels for high frequency logs.

- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientPrefetchTest.cpp
Fix PrefetchPartitions FV test
by increasing timeout.
Resolves: OLPEDGE-2380
> Fix PrefetchPartitions test

- external/CMakeLists.txt
- external/boost/CMakeLists.txt.boost.in
- external/googletest/CMakeLists.txt.googletest.in
- external/leveldb/CMakeLists.txt.leveldb.in
- external/rapidjson/CMakeLists.txt.rapidjson.in
Adding the GIT_SHALLOW flag to ExternalProject_Add will speed up our
external dependencies cloning and avoids timeouts due to stucked
or slow connections.
Relates-To: OLPEDGE-2410
> Add shallow clone flag to ExternalProject_Add.

- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/src/client/PendingUrlRequests.cpp
- olp-cpp-sdk-core/src/client/PendingUrlRequests.h
- tests/common/mocks/NetworkMock.cpp
- tests/common/mocks/NetworkMock.h
- tests/integration/olp-cpp-sdk-core/ApiLookupClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientPrefetchPartitionsTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerTestBase.cpp
This commit fixes a wrong usage of the NetworkMock::ReturnHttpResponse
which does not have any sleep time by default and resulted in optimal
cases in callback trigger prior to the Network::Send mock call returning
which caught the OlpClient PendingUrlRequest with no valid request id
set and thus resulted in a lock in waiting for the callback which never
came.
Additionaly this adds some more debug logs to PendingUrlRequests class
to see what callback is added or cancelled and changes the
ApiLookupClientTest.LookupApiAsync to really use the async API as this
did not happen due to copy-paste code from LookupApi test.
Resolves: OLPEDGE-2409
> Fix NetworkMock issue resulting in OlpClient lock.

- docs/create-platform-client-settings.md
Users should create `RetrySettings` to configure the handling of
failed requests.
Relates-To: OLPEDGE-2394
> Add info on `RetrySettings`

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
Dangling pointer was wrapped with std::unique_ptr
Relates-To: OLPEDGE-2381
> Fixed Sonar issue in the DiscCache.cpp

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.h
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
Using Size() method users will be able to check current size of the data stored
in the mutable cache. Note that the returned size is approximate and
may not match cache folder size. It is the size of real data and
does not include levelDB overhead.
Using SetMaxSize() method users will be able to change maximum alowed size
of the mutable cache on a fly. If size increases, no side actions happen.
If size decreases, the data that doesn't fit into new size (taking into account
data eviction thresholds) will be exicted from the cache. If a lot of data
must be evicted, it will be splitted to chunks that fits into
CacheSettings::max_eviction_portion.
Note that implementation is done into DefaultCacheImpl and not exposed to
DefaultCache public API. New APIs will be exposed in a separate commit …
> Add method to get current size and set max size of the mutable cache

- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
Exposed new methods for cache size management:
- Size(CacheType) will evaluate cache size of
the given type;
- Size(uint64_t) could be used to reduce/enlarge
mutable cache size;
Relates-To: OLPEDGE-2392, OLPEDGE-2393
> Expose methods related to cache size

- olp-cpp-sdk-core/src/thread/PriorityQueueExtended.h
- olp-cpp-sdk-core/src/thread/ThreadPoolTaskScheduler.cpp
- olp-cpp-sdk-core/tests/thread/PriorityQueueExtendedTest.cpp
- olp-cpp-sdk-core/tests/thread/ThreadPoolTaskSchedulerTest.cpp
For correct template deduction of rvalue references std::forward should
be used. Otherwise, scheduler task will be copied. Also added simple
test to check the issue.
Resolves: OLPEDGE-2418
Signed-off-by: Kostiantyn Zvieriev ext-kostiantyn.zvieriev@here.com
> Make ThreadedTaskScheduler to move tasks.

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
When we using Open with cache type to
open specific disk cache we do not reset memory
cache. In this case if disk cache was chenged, we
still could return keys from memory which is not
longer cached. Reseting memory cache was added to
avoid this problem.
Relates-To: OAM-735
> Reset memory cache on reopen disk cache

- olp-cpp-sdk-core/src/utils/Dir.cpp
- olp-cpp-sdk-core/tests/cache/Helpers.cpp
Modify Dir::Size to use only non unicode paths.
Repair the missing function in Helpers.cpp
Relates-To: OLPEDGE-2393
> Fix compilation on windows with UNICODE enabled

- olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
- olp-cpp-sdk-core/tests/client/TaskContextTest.cpp
- olp-cpp-sdk-dataservice-read/src/PrefetchPartitionsHelper.h
- olp-cpp-sdk-dataservice-read/src/PrefetchTilesHelper.h
- olp-cpp-sdk-dataservice-read/src/TaskSink.cpp
- olp-cpp-sdk-dataservice-read/src/TaskSink.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
The CancellationContext was incorrectly reset. The user could store the
cancellation token for the operation that is already finished and call
the Cancel method. Change the prefetch methods to share the same
context for all operations.
Relates-To: OAM-870
> Fix the cancellation function incorrectly called

- azure-pipelines.yml
- examples/android/build.gradle
- examples/android/gradle/wrapper/gradle-wrapper.properties
- scripts/android/build.sh
Azure updated their pre-installed NDK from 21 to 22.
Also NDK 22 don't include `platforms` directory.
Examples were not compiling due to error:
"NDK is missing a "platforms" directory"
Fixed by installing NDK 21 in job and using it for
further compilations.
Discussed in:
https://github.com/actions/virtual-environments/issues/2420
Also gradle and android-gradle-plugin were updated.
Relates-To: OLPEDGE-2443
> Android job fixes due to changes in Azure images

- olp-cpp-sdk-core/src/cache/DiskCache.h
- olp-cpp-sdk-core/src/client/repository/ApiCacheRepository.h
- olp-cpp-sdk-core/src/utils/Dir.cpp
- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-core/DirTest.cpp
Dir::Size() method switched from using fstatat64() to lstat64() due
to absence of dirfd() function on QNX.
Fixed broken traversal of subdirectories in Dir::Size().
New suite DirTest added to functional tests with tests for Dir::Size().
Fixed missing includes.
Relates-To: OCMAMQNX-2, OCMAMQNX-9
Signed-off-by: Jakub Mirek <ext-jakub.mirek@here.com>
> Fix compilation on QNX7

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
The parameter max_file_size needs to be increased to cover the use
case when the cache is too big and leveldb manifest file exceeds the
max_file_size, as the result leveldb consider the cache is broken and
starts the cache repair operation.
Relates-To: OLPEDGE-2448
> Modify the protected cache settings

- olp-cpp-sdk-dataservice-read/src/PrefetchPartitionsHelper.cpp
- olp-cpp-sdk-dataservice-read/src/PrefetchPartitionsHelper.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
Remove the query_max_size parameter, use constant directly instead.
Optimize the PrefetchPartitionsHelper to produce less copies.
Relates-To: OLPEDGE-2444
> Fix the veracode warning.

- scripts/linux/nv/gitlab_test_performance.sh
The script refers to the old "short_test_null_cache" test flavor and
fails.
Resolves: OLPEDGE-2479
> Fix performance script reporting.

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerPrefetch.cpp
In case of sparse data we load additional quads, but current algorithm
looks on slice root instead of requested tiles when decides to load
extra metadata. In some cases that is not correct because for all
requested tiles bundles are not that far away.
Volatile client doesn't load extra quads, thus, only versioned client
changed.
Also added the test to cover the issue.
Resolves: OLPEDGE-2454
> Reduce extra quads count for prefetch.

- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.h
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.h
- olp-cpp-sdk-core/include/olp/core/client/ApiError.h
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
The retry functionality moved from OlpClient to the 
AuthenticationClientImpl. This enables the client to generate a new
Authentication header with a new nonce for each retry request.
Adapt SignIn methods to use sync API.
Add a fallback for a wrong timestamp for user sign-in methods.
Added static methods to ApiError class, used to create common
ApiError instances.
Relates-To: OLPSUP-13370
> Fix the issue when the nonce is reused for retry

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
Set WriteOptions::sync flag to CacheSettings::enforce_immidiate_flush.
This fixes the issue when some data is lost when mutable cache is
closed and then open a protected.
Relates-To: OLPSUP-13397
> Apply flush flag to leveldb operations

- scripts/misc/commit_checker.sh
Current implementation takes newline symbols (\n, \r) into account
during evaluation of the line length
Relates-To: OLPEDGE-2411
> Fixing commit checker script to exclude newline

- olp-cpp-sdk-authentication/src/ResponseFromJsonBuilder.h
This check allows to verify that the response contains all (required and
optional) fields - prints all missing fields.
It's required to use ResponseFromJsonBuilder to able to verify responses.
Pretty useful when analyzing logs
Relates-To: OLPEDGE-2477
> Add check about absent response fields

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.h
- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationMockedResponses.h
This is the next step in the Apple Sign-In support.
Using 'AppleSignInProperties' user could sign-in in the HERE services.
Apple id_token will be used as a bearer. For acceptance T&C user still
required to have app_id and app_secret.
Work on this API still in progress thus it may be changed in the future.
Relates-To: OLPEDGE-2483
> Add SignInApple to Authentication API

- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/src/client/PendingUrlRequests.h
- olp-cpp-sdk-core/tests/client/ApiLookupClientImplTest.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/ApiClientLookupTest.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- olp-cpp-sdk-dataservice-write/tests/StreamLayerClientImplTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-core/ApiLookupClientTest.cpp
Merges same requests in sync OlpClient:CallApi
Originally sync & async CallApi implementations were different:
-async merged same requests (added callbacks to the PendingUrlTasks);
-sync simply sent a request as is. To prevent concurrent sync
requests the workaround with the NamedMutex was used.
This commit improves the sync CallApi. Now it triggers internally
async implementation.
So same requests will add callbacks to the PendingUrlTasks for
any CallApi calls, and NamedMutex workaround does not need in
most cases (the only exception is ApiClientLookup::LookupApi).
> Add merging of same requests in sync OlpClient:CallApi()

- docs/create-platform-client-settings.md
- docs/work-with-data-apis.md
- Document how to work with generic Data APIs that are currently
not supported by the Data SDK.
- Add an example on how to download the difference between two versions
of a catalog.
Relates-To: OLPEDGE-2488
> Instruction on how to work with unsupported APIs

- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
Merging same requests inside OlpClient::CallApi
does not prevent running a new request
between end of the previous call & putting its
result into a cache.
For concurrent cases it leads to multiple parallel
requests and network mock issues in tests.
As a quick fix NamedMutexes are reverted for
methods where they had been used before.
> Revert NamedMutex removal

- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
Adds additional checks to prevent crash and does not
resize an output buffer in case of an empty HttpResponse
with HttpStatusCode::OK
> Does not resize output for an empty response

- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
This is needed to correctly handle the full flight mode.
Resolves: OLPSUP-13674
> Map NSURLErrorDataNotAllowed to OFFLINE_ERROR

- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
This reverts commit d9198f31e8006724bfd176a18ff3a1b9ef583154.
All changes related to CallApi have to be reworked
> Revert "Revert NamedMutex removal (#1174)"

- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/src/client/PendingUrlRequests.h
- olp-cpp-sdk-core/tests/client/ApiLookupClientImplTest.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/ApiClientLookupTest.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- olp-cpp-sdk-dataservice-write/tests/StreamLayerClientImplTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-core/ApiLookupClientTest.cpp
This reverts commit 0d9351d8c4cbc4365bdcaca4aa1a156c80d1fb93.
Changes have to be reworked. Now they cause a sleep in network thread
on retry and have some issues on merge
> Revert "Merges same requests in sync CallApi (#1166)"

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCacheEnv.cpp
- olp-cpp-sdk-core/src/cache/DiskCacheEnv.h
The usage of mmap causes crashes on memory constrained environment.
By overriding the default leveldb environment we can avoid it's usage.
Resolves: OLPSUP-13838
> Disable mmap usage for leveldb storage

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCacheEnv.cpp
When the max cache size is not set, SDK use the leveldb default env,
SDK needs to replace it with its own in order to disable mmap usage.
Fix the Limiter class constructor warning.
Relates-To: OLPSUP-13838
> Use SDK leveldb environment

- olp-cpp-sdk-core/include/olp/core/geo/coordinates/GeoCoordinates.h
- olp-cpp-sdk-core/include/olp/core/geo/coordinates/GeoCoordinates3d.h
- olp-cpp-sdk-core/include/olp/core/geo/coordinates/GeoPoint.h
- olp-cpp-sdk-core/include/olp/core/geo/coordinates/GeoRectangle.h
- olp-cpp-sdk-core/include/olp/core/geo/projection/EarthConstants.h
- olp-cpp-sdk-core/include/olp/core/geo/projection/EquirectangularProjection.h
- olp-cpp-sdk-core/include/olp/core/geo/projection/IProjection.h
- olp-cpp-sdk-core/include/olp/core/geo/projection/IdentityProjection.h
- olp-cpp-sdk-core/include/olp/core/geo/projection/SphereProjection.h
- olp-cpp-sdk-core/include/olp/core/geo/projection/WebMercatorProjection.h
In  olp-cpp-sdk-core/include/olp/core/geo/coordinates&projection,
review and modify the existing documentation and add missing
descriptions so that we have fewer errors when building the API ref.
Relates-To: OLPEDGE-1444
> Review/add the API doc (`geo` folder - part 1)

- .gitlab-ci.yml
- scripts/macos/psv/azure_macos_build_psv.sh
Add exclude dirs for Security jobs, so only
sdk code is being scanned.
Relates-To: OLPEDGE-2506
> Disable flawfinder analyser as it doesn't support C++11 syntax

- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
- olp-cpp-sdk-core/src/cache/InMemoryCache.cpp
- olp-cpp-sdk-core/src/cache/InMemoryCache.h
- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
When user calls DefaultCache::Remove() and
DefaultCache::RemoveKeysWithPrefix() we should not remove protected
keys. This is now implemented and tested.
Relates-To: OLPEDGE-2521
> Do not remove protected keys in DefaultCache.

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
If DiskCache has been closed already but compaction is called explicitly
the SIGSEGV would occur
Relates-To: OAM-1016
> Fix crash during compaction on closed DiskCache

- olp-cpp-sdk-core/include/olp/core/geo/tiling/HalfQuadTreeSubdivisionScheme.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/ISubdivisionScheme.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/ITilingScheme.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/QuadTreeSubdivisionScheme.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/SubTiles.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/TileKey.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/TileKeyUtils.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/TileTreeTraverse.h
- olp-cpp-sdk-core/include/olp/core/geo/tiling/TilingScheme.h
In olp-cpp-sdk-core/include/olp/core/geo/coordinates&projection,
review and modify the existing documentation and add missing
descriptions so that we have fewer errors when building the API ref.
Relates-To: OLPEDGE-1444
> Review/add the API doc (geo folder - part 2)

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
Merge the same quadtree requests during concurrent GetTile and
PrefetchTiles API requests. Later this approach will be replaced
with merging inside OlpClient.
Resolves: OLPSUP-13676
> Merge the same QuadTree requests

- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.mm
Make sure that access to urlSessions variable is synchronized.
Resolves-To: OLPSUP-14072
> Fix the iOS network race when accessing sessions

- olp-cpp-sdk-core/include/olp/core/logging/Appender.h
- olp-cpp-sdk-core/include/olp/core/logging/Configuration.h
- olp-cpp-sdk-core/include/olp/core/logging/ConsoleAppender.h
- olp-cpp-sdk-core/include/olp/core/logging/DebugAppender.h
- olp-cpp-sdk-core/include/olp/core/logging/FileAppender.h
- olp-cpp-sdk-core/include/olp/core/logging/FilterGroup.h
- olp-cpp-sdk-core/include/olp/core/logging/Format.h
- olp-cpp-sdk-core/include/olp/core/logging/Log.h
- olp-cpp-sdk-core/include/olp/core/logging/LogMessage.h
- olp-cpp-sdk-core/include/olp/core/logging/MessageFormatter.h
In olp-cpp-sdk-core/include/olp/core/logging,
review and modify the existing documentation and add missing
descriptions so that we have fewer errors when building the API ref.
Relates-To: OLPEDGE-1446
> Review/add the API doc (`logging`)

- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
Cache could become inoperable due to several reasons:
- interrupted compaction leads to files on level-0, and this leads to
excessive memory usage during read operations;
- different IO errors for protected cache couldn't be solved with RepairDb
due to read-only nature of this cache (for mutable cache there will be
an attempt to repair it);
Do not remove corrupted cache and just notify a user about it.
Relates-To: OLPSUP-14088
> Mark inoperable cache as corrupted

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
leveldb do not manage DB objects lifetime by itself. So in case of error
or early return from the Open routine leveldb::DB object should be
removed explicitly
Relates-To: OLPSUP-14088
> Delete leveldb::DB object on error

- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
- olp-cpp-sdk-core/tests/client/PendingUrlRequestsTest.cpp
- olp-cpp-sdk-core/tests/thread/SyncQueueTest.cpp
- olp-cpp-sdk-core/tests/thread/ThreadPoolTaskSchedulerTest.cpp
- olp-cpp-sdk-dataservice-read/tests/StreamLayerClientImplTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/functional/olp-cpp-sdk-authentication/AuthenticationCommonTestFixture.cpp
- tests/functional/olp-cpp-sdk-authentication/DecisionApiTest.cpp
- tests/functional/olp-cpp-sdk-authentication/FacebookAuthenticationTest.cpp
- tests/functional/olp-cpp-sdk-authentication/HereAccountOauth2ProductionTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVolatileLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientCacheTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteStreamLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVersionedLayerClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-write/DataserviceWriteVolatileLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
- tests/integration/olp-cpp-sdk-core/ApiLookupClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientTest.cpp
- tests/performance/MemoryTest.cpp
Mutable cache always created with OpenOptions::Default instead of one
provided by CacheSettings. This makes impossible to enable leveldb crc
check for the cache.
Added somehow missed include needed for std::this_thread::sleep_for.
Relates-To: OAM-1088
> Fix CacheSettings::openOptions not used by cache.

- examples/main.cpp
Fixes a tiny type noticed when running the example code.
Relates-To: OLPEDGE-342
Signed-off-by: Åke Forslund <ake.forslund@scania.com>
> Fix tiny typo, usuage -> usage

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- olp-cpp-sdk-dataservice-read/tests/ApiClientLookupTest.cpp
Refactor the NamedMutex class to avoid using the static global mutex
and storage. Instead, introduce a NamedMutexStorage class as a
temporary solution to avoid crashes and secure the API requests merge
functionality, until the proper implementation is enabled. The storage
is initialized per VersionedLayerClient and VolatileLayerClient.
Resolves: OLPSUP-14327
> Refactor the NamedMutex class

- olp-cpp-sdk-core/include/olp/core/client/ApiError.h
- olp-cpp-sdk-core/include/olp/core/client/ApiNoResult.h
- olp-cpp-sdk-core/include/olp/core/client/ErrorCode.h
- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchPartitionsRequest.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- tests/common/CMakeLists.txt
- tests/common/KeyValueCacheTestable.h
All prefetch operations are required to have properly working cache.
Thus any cache related issue should led to the failed request
Relates-To: OLPEDGE-2552
> Abort PrefetchTiles/Data with error on cache issue

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
Currently failed cache open leads to removing cache path what interfere
with the idea of cache repair process (either removal or proper fixing)
since we're using the same cache setting during whole cache lifetime
Relates-To: OAM-1088
> Do not clear cache path on error

- examples/ProtectedCacheExample.cpp
If protected cache contains level 0 files leveldb will consume to
much RAM while trying to compact in read env. To prevent such
situations level 0 files treatened as error. Thus, protected cache
example must be updated.
Relates-To: OLPSUP-14367
> Add cache compaction to protected cache example.

- olp-cpp-sdk-core/src/client/OlpClientSettings.cpp
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
Default retry condition func must also consider http::ErrorCodes. Unit
test tuned accordingly.
Relates-To: OLPEDGE-2567
> Add http::ErrorCodes to DefaultRetryCondition()

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
Result of opening protected cache rewrites result of openning mutable
cache. We will miss error if protected cache is ok.
Relates-To: OAM-1088
> Respect mutable cache open error.

- .github/workflows/psv_pipelines.yml
- scripts/linux/psv/test_psv.sh
Needed for securing this workflow.
On PR we also change approach to load data to codecov.
Updates are based on CodeCov docs.
Relates-To: OLPEDGE-2553
> Add codecov bash script as artifact

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.h
It seems that in NetworkWinHttp, the previous code only sets the "complete" flag on the Request when all data has been received (line 786). And only with the "completed" flag, the Request gets closed (line 962). So after an error, the request is never completed and thus blocked forever.
Trying to fix this by replacing the unused "cancelling" flag by an "error" flag and then harvesting requests in error state as well.
This has been tested manually up to now only for the case of connecting to an unused port of an existing server (where we get positive information that connection is not possible).
> Free an WinHttp request after an error.

- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
- olp-cpp-sdk-core/include/olp/core/utils/Dir.h
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/utils/Dir.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
- olp-cpp-sdk-core/tests/cache/Helpers.cpp
- olp-cpp-sdk-core/tests/cache/Helpers.h
- tests/functional/olp-cpp-sdk-core/DirTest.cpp
* Change protected cache behavior such that it tries to open
in ReadWrite mode in case when user passed default open options
to cache settings. If path can be opened as ReadWrite protected
cache will be opened as ReadWrite otherwise it wil lbe opened in
ReadOnly mode. This is done to reduce compaction times for leveldb.
* Additional logic was added that will return corruption error
in case that there is more than 4 L0 leveldb files in protected
cache.
Resolves: OAM-1116
> Change protected cache behavior

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.h
The mutax_storage instances must be destroyed after task sink, since
the currently running parallel tasks may access it.
Resolves: OLPEDGE-2585
> Change the clients destruction sequence

- olp-cpp-sdk-core/include/olp/core/client/BackdownStrategy.h
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/client/BackdownStrategyTest.cpp
To avoid requests sent after 0 (or close to 0) milliseconds, backdown
strategy changed to support the Equal Jitter, as described in
https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
Resolves: OLPEDGE-2574
> Add the Equal Jitter backdown strategy

- olp-cpp-sdk-core/src/utils/Dir.cpp
Fix compilaiton of Dir.cpp file on windows
while compiling with Unicode Character Set
Resolves: OLPEDGE-2586
> Fix Unicode compilation on windows

- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.h
On devices with slow internet connections this previously introduced a delay of up to two seconds on shutdown. In pathological cases, this could have added up with other Android Activity shutdown operations delays and led to an ANR error.
> Remove arbitrary 2s delay on shutdown

- .gitlab-ci.yml
- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-network-test.sh
- scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test-mock.sh
From now we need docker image with standard user instead of root.
Update fv functional and network test scripts accordingly.
Resolves: OLPEDGE-2683
> Update docker image for fv job, update scripts

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
Now protected cache is opened with rw permissions by default. Repair
must be prohibited, so the user could know the data is corrupted.
Relates-To: OAM-1088
> Disable db repair for protected cache.

- olp-cpp-sdk-core/include/olp/core/client/BackdownStrategy.h
This file uses std::min() and thus should include the <algorithm> header with provices this function.
Relates-To: OLPEDGE-2597
Signed-off-by: Johannes Stille <johannes.stille@here.com>
> Include <algorithm> in BackdownStrategy.h since it is used there.

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/src/AuthenticationClient.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.h
- olp-cpp-sdk-authentication/tests/AuthenticationClientTest.cpp
- olp-cpp-sdk-authentication/tests/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/client/ApiResponse.h
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
Fix the various APIs in authentication component to use the server
time when the `use_system_time` option is false.
Server time is now incremented on retry.
Add a bool operator to ApiResponse class, a shortcut to IsSuccessful.
Relates-To: OLPSUP-14833
> Use the server time correctly

- olp-cpp-sdk-core/src/utils/Dir.cpp
WinApi GetFileAttributes() returns INVALID_FILE_ATTRIBUTES if file not
found. We must use the constant to decide is file exist or not.
Relates-To: OAM-1154
> Correct Dir::FileExist() method for windows.

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
- olp-cpp-sdk-core/src/cache/DiskCacheEnv.cpp
- olp-cpp-sdk-core/src/cache/DiskCacheEnv.h
Change the static EnvWrapper instance to a wrapped with a smart
pointer, so that we can guaranty that the instance will be alive while
it is needed, even when the `env` was deinitialized at exit.
By this we fix the scenario when the environment is destroyed before
DiskCache in certain use cases.
Resolves: OLPSUP-14933
> Wrap the leveldb::Env to shared_ptr

- .gitignore
- .gitlab-ci.yml
- scripts/linux/weekly/gitlab_build_perf_tests.sh
- scripts/linux/weekly/performance_tests.json
- scripts/linux/weekly/reports/index.html
- scripts/linux/weekly/run_performance_test_metrics.py
Job runs build & performance test with cpu/ram usage reporting
collected by python script. It measure max and avg values for
CPU and RAM during execution of
MemoryTest.ReadNPartitionsFromVersionedLayer/15m_test.
Job is proposed to run weekly or on-demand for release.
Report with collected data feom csv to be showed as
index.html on Gitlab Pages.
Relates-To: OLPEDGE-2459
> Add perf test job with cpu/ram usage report

- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientGetDataTest.cpp
If during authorization error happened, token will be empty. We don't
propagate error, but at least request should not be sent in this case.
Relates-To: OLPEDGE-2607
> Don't send request if bearer token is empty.

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-dataservice-read/src/PrefetchTilesHelper.h
- olp-cpp-sdk-dataservice-read/src/QueryMetadataJob.h
- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- tests/common/ResponseGenerator.cpp
Some files that use for_each and transform have missed <algorithm>
in includes.
Relates-To: OLPEDGE-2614
> Add missed includes.

- .gitlab-ci.yml
- scripts/linux/weekly/gitlab_run_perf_test_metrics.sh
- scripts/linux/weekly/performance_tests.json
- scripts/linux/weekly/run_performance_test_metrics.py
Add new bash script which:
- start olp mock server
- verify it's started
- start performance test execution.
Currently test is running without olp server,
but errors are as warnings
Relates-To: OLPEDGE-1771
> Add OLP server start before running perf test

- olp-cpp-sdk-authentication/src/TokenResult.cpp
Fix possible underflow in TokenResult
Resolves: OLPEDGE-2628
> Fix possible underflow in TokenResult

- olp-cpp-sdk-core/src/client/DefaultLookupEndpointProvider.cpp
- olp-cpp-sdk-core/tests/client/DefaultLookupEndpointProviderTest.cpp
This allows developers to be able to visually inspect
locally compiled test catalog of a small region
during feature development or bugfixing.
Resolves: HARP-16305
Signed-off-by: Ostap <ostapkl@gmail.com>
> Possibility to read the local catalogs added

- olp-cpp-sdk-core/include/olp/core/http/Network.h
The current Doxygen description for the API Network::Cancel() did not
state clearly how the cancelled NetworkResponse will look like.
This commit adds the missing description with an example code snippet
to illustrate how the response will look like so that the user can
check the appropriate parameters properly.
Resolves: #1246
> Extend Network.h abstract API Doxygen for Cancel.

- README.md
In the Use the SDK section, add a link to the API ref.
Relates-To: OLPEDGE-2643
> Add a link to the API ref

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationSettings.h
- olp-cpp-sdk-authentication/include/olp/authentication/Settings.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.cpp
- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-core/include/olp/core/client/RetrySettings.h
- olp-cpp-sdk-core/src/client/RetrySettings.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/TokenProviderTest.cpp
olp::authentication::AuthenticationSettings and olp::authentication::Settings
structs are extended with RetrySettings.
AuthentificationClientImpl now uses user defined retry settings instead of hardcoded values.
Fixed double token request bug in TokenProvider.
Relates-To: OLPEDGE-2634, OLPSUP-15460
> Add RetrySettings for authentication

- olp-cpp-sdk-authentication/include/olp/authentication/AutoRefreshingToken.h
- olp-cpp-sdk-authentication/include/olp/authentication/SignInResult.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenEndpoint.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
- olp-cpp-sdk-authentication/src/AutoRefreshingToken.cpp
- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
- olp-cpp-sdk-authentication/src/TokenEndpointImpl.cpp
- olp-cpp-sdk-authentication/src/TokenEndpointImpl.h
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-authentication/TokenEndpointTest.cpp
- tests/integration/olp-cpp-sdk-authentication/TokenProviderTest.cpp
The inner class TokenEndpoint::Impl is extructed from TokenEndpoint.cpp
to separate files TokenEndpointImpl.h and TokenEndpointImpl.cpp.
TokenEndpointImpl is extended with mostly copy-pasted code from
AuthenticationClientImpl, which is supposed to be refactored in
the future to use TokenProvider, and not in the opposite direction,
as it is now. TokenEndpointImpl code is adapted in a way to give an
abilty to pass cancellation context from the new token profider to
OlpClient::CallApi().
A new test class TokenEndpointTest contains adapted tests
copy-pasted from AuthenticationClientTest.
Integration tests for cancellation and timeout are added.
Relates-To: OLPEDGE-2651
> Add proper cancellation for the new token provider

- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.h
- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
If a timeout occurred, the cancellation is done through the context.
So this case needs to be handled independently of context state,
instead of blindely return Cancelled error if context is cancelled.
Relates-To: OLPEDGE-2656
> Make sign in timeout error distinguishable

- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
- Removed retry logic from Android network code because it is not necessary
due to better retry logic that already exists for all platforms inside
OlpClient.
- Now log message on connection timeout in OlpClient is more informative
and prints url, timeout and retry_count of the request.
Resolves: OLPSUP-16639
> Remove retry logic from Android.

- scripts/linux/nv/sonar-project.propertiesValgrind
Sometimes our cppcheck or valgrind reports issues in
include directories, but can't report it to SonarQube due
to missing inlude dirs as source code.
Relates-To: OAM-1302
> Add include dirs to SonarQube scanner

- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
- olp-cpp-sdk-authentication/src/AutoRefreshingToken.cpp
- olp-cpp-sdk-authentication/src/AutoRefreshingToken.h
- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
- olp-cpp-sdk-authentication/src/TokenEndpoint.h
- olp-cpp-sdk-authentication/src/TokenEndpointImpl.cpp
- olp-cpp-sdk-authentication/src/TokenEndpointImpl.h
- olp-cpp-sdk-authentication/src/TokenProvider.cpp
- olp-cpp-sdk-authentication/src/TokenRequest.cpp
- olp-cpp-sdk-authentication/src/TokenRequest.h
- tests/functional/CMakeLists.txt
- tests/functional/olp-cpp-sdk-authentication/HereAccountOauth2ProductionTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
- tests/integration/olp-cpp-sdk-authentication/TokenEndpointTest.cpp
- tests/integration/olp-cpp-sdk-authentication/TokenProviderTest.cpp
Move AutoRefreshingToken, TokenEndpoint, and TokenRequest
files to src folder.
Remove deprecated warnings
Move kDefaultMinimumValidity, kDefaultMinimumValiditySeconds, and
kForceRefresh constants from AutoRefreshingToken to TokenProvider
Move internal implementation of TokenProvider(TokenProviderImpl class) to
"internal" namespace.
Relates-To: OLPEDGE-1880
> Move AutoRefreshingToken, TokenEndpoint, and TokenRequest

- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
- olp-cpp-sdk-authentication/src/TokenEndpoint.h
- olp-cpp-sdk-authentication/src/TokenProvider.cpp
- tests/functional/olp-cpp-sdk-authentication/HereAccountOauth2ProductionTest.cpp
- tests/integration/olp-cpp-sdk-authentication/HereAccountOauth2Test.cpp
Break dependency between TokenEndpoint and AutoRefreshingToken
Remove RequestAutoRefreshingToken method from TokenEndpoint.
Resolves: OLPEDGE-1030
> Break circular dependency between classes

- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.h
- olp-cpp-sdk-authentication/tests/AuthenticationClientTest.cpp
- olp-cpp-sdk-core/include/olp/core/thread/TaskScheduler.h
- olp-cpp-sdk-core/tests/thread/ThreadPoolTaskSchedulerTest.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- tests/common/CMakeLists.txt
- tests/common/mocks/TaskSchedulerMock.h
Move ExecuteOrSchedule function to TaskScheduler
Remove ExecuteOrSchedule in other places
Resolves: OLPEDGE-1171
> Move ExecuteOrSchedule function to TaskScheduler

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationCredentials.h
- olp-cpp-sdk-authentication/src/AuthenticationCredentials.cpp
- olp-cpp-sdk-authentication/src/AutoRefreshingToken.cpp
- olp-cpp-sdk-authentication/src/TokenEndpoint.cpp
- olp-cpp-sdk-authentication/src/TokenEndpointImpl.cpp
- olp-cpp-sdk-authentication/tests/AuthenticationCredentialsTest.cpp
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/tests/client/OlpClientTest.cpp
Move removing url handling from TokenEndpoint to TokenEndpointImpl
Added reading token_endpoint_url from 	credentials.properties
Resolves: OLPEDGE-1029
Signed-off-by: Yevhenii Dudnyk ext-yevhenii.dudnyk@here.com
> Change handling token_endpoint_url

- olp-cpp-sdk-core/src/logging/ConsoleAppender.cpp
- olp-cpp-sdk-core/tests/logging/LogTest.cpp
In POSIX systems, logging should always go to stderr.
Logging to stdout will cause problems for applications that
write data to stdout.
Signed-off-by: Christian Ocker <christian.ocker@here.com>
> Log to stderr instead of stdout

- olp-cpp-sdk-dataservice-read/src/TaskSink.cpp
- olp-cpp-sdk-dataservice-read/src/TaskSink.h
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.h
- olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/generated/model/Index.h
- olp-cpp-sdk-dataservice-write/src/CatalogSettings.h
- olp-cpp-sdk-dataservice-write/src/IndexLayerClient.cpp
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/VolatileLayerClientImpl.cpp
This commit fixes some of SonarCube reported issues with major and
minor levels including:
- Effective move of passed by value parameters.
- Moved ougth to be static methods to anonymous namespace.
- Initialize variables and members before usage.
Relates-To: OAM-1366
> Second batch of SonarCube reported issues fixed.

- .gitlab-ci.yml
Minor updates to job condition (use `web`) to avoid
issues when triggers many variables at once.
Remove `always` condition from jobs which require 
default on_success condition.
Relates-To: OLPEDGE-2507
> Remove deprecated security job

- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-authentication/tests/AuthenticationClientTest.cpp
Change using Network object directly to using
OlpClient's CallApi method to make requests.
Additionally added a check for a valid network_request_handler
variable. Move the request to a lambda function wich is
executed by TaskScheduler.
Add a test for checking SignUpHereUser method
with default credentials and properties parameters.
Remove a test which checks Network class(send method)
as these calls aren't a part of AuthenticationClientImpl now.
Relates-To: OLPEDGE-2020
> Change SignUpHereUser method to a sync task

- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-authentication/tests/AuthenticationClientTest.cpp
Change using Network object directly to using
OlpClient's CallApi method to make requests.
Additionally added a check for a network_request_handler
variable. Move the request to a lambda function wich is
executed by TaskScheduler.
Mark credentials object as unused.
Add a test for checking SignOut method
with an empty access_token as a parameter.
Remove a test which checks Network class(send method)
as it isn't a part of AuthenticationClientImpl now.
Relates-To: OLPEDGE-2021
>  Change SignOut method to a sync task

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
When user is using fixed catalog versions it is possible that request
GetLatestVersion won't return actual version from the cache since it
hadn't been written to the cache. Use StartVersion as a new latest
version in the cache-only requests when previous version is absent or
less than the user-set version
Relates-To: OAM-1387
> Save latest version with GetLatestVersion request

- scripts/linux/nv/sonar-project.propertiesValgrind
By default branch will be master, nevertheless.
Resolves: OAM-1420
> Remove unsupported SonarQube property

- olp-cpp-sdk-authentication/include/olp/authentication/TokenProvider.h
Despite TokenProviderImpl is for internal use only, its declared in
public TokeProvider.h header. Thus, its symbols must be exported to be
able to use shared authentication lib.
Relates-To: OAM-1387
> Export TokenProviderImpl class.

- azure-pipelines.yml
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogClient.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/src/CatalogClient.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.h
- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.h
- olp-cpp-sdk-dataservice-read/src/generated/parser/VersionsResponseParser.cpp
- olp-cpp-sdk-dataservice-read/src/generated/parser/VersionsResponseParser.h
- olp-cpp-sdk-dataservice-read/src/generated/serializer/CatalogVersionsSerializer.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.h
- scripts/ios/azure_ios_build_psv.sh
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientTest.cpp
- Add functionality to allow to query compatible
versions for the given catalog.
- Update Azure Pipelines to use new macOS-10.15 version
Resolves: OAM-1338
> Add functionality for GetCompatibleVersions

- olp-cpp-sdk-authentication/src/TokenEndpointImpl.cpp
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/thread/ExecutionContext.h
- olp-cpp-sdk-core/src/thread/ExecutionContext.cpp
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/thread/ExecutionContextTest.cpp
Add execution context classes which provides
functionality to cancel operation, setting errors,
and execute tasks.
Relates-To: OLPEDGE-2077
Signed-off-by: Yevhenii Dudnyk ext-yevhenii.dudnyk@here.com
> Add execution context functionality

- azure-pipelines.yml
- scripts/windows/build.sh
Due to Microsoft deprecation notice.
Relates-To: OLPEDGE-2728
> Replace win-2016 to 2019

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/thread/Continuation.h
- olp-cpp-sdk-core/include/olp/core/thread/Continuation.inl
- olp-cpp-sdk-core/include/olp/core/thread/ExecutionContext.h
- olp-cpp-sdk-core/include/olp/core/thread/TypeHelpers.h
- olp-cpp-sdk-core/src/thread/Continuation.cpp
- olp-cpp-sdk-core/src/thread/ExecutionContext.cpp
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/thread/ContinuationTest.cpp
Add Continuation template classes and implementation
which provide functionality to create a chain of tasks,
and execute tasks.
Add continuation unit tests.
Relates-To: OLPEDGE-2077
> Add continuation functionality

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/thread/Continuation.h
- olp-cpp-sdk-core/include/olp/core/thread/Continuation.inl
- olp-cpp-sdk-core/include/olp/core/thread/TaskContinuation.h
- olp-cpp-sdk-core/include/olp/core/thread/TaskContinuation.inl
- olp-cpp-sdk-core/src/thread/Continuation.cpp
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/thread/TaskContinuationTest.cpp
Add task continuation classes which provides
possibility to create and run multiple asynchronous tasks.
Add unit tests for task continuation.
Relates-To: OLPEDGE-2077
> Add task continuation implementation

- olp-cpp-sdk-core/include/olp/core/utils/Base64.h
- olp-cpp-sdk-core/src/utils/Base64.cpp
As described in https://datatracker.ietf.org/doc/html/rfc4648#section-5
the padding at the end for URIs can be omitted, therefore the three
available Base64Encode() methods are now extended with an extra
bool parameter which indicates that this is a URI encoding and thus
will omit to pad the output with "=" characters.
Relates-To: OLPEDGE-2680
> Extend olp::utils::Base64Encode() for URIs.

- olp-cpp-sdk-core/include/olp/core/thread/Continuation.h
- olp-cpp-sdk-core/include/olp/core/thread/Continuation.inl
- olp-cpp-sdk-core/src/thread/Continuation.cpp
- olp-cpp-sdk-core/tests/thread/ContinuationTest.cpp
- olp-cpp-sdk-core/tests/thread/ExecutionContextTest.cpp
- olp-cpp-sdk-core/tests/thread/TaskContinuationTest.cpp
Add TaskContinuation unit tests/change cancellation
Add unit tests that check asynchronous behaviour of
TaskContinuation.
Add clearing a callback and tasks on cancellation.
Fix calling SetError in case a continuation is cancelled.
Change the mechanism to cover cancellation cases(cancel before/
after run) in case of calling SetError.
Simplify usage of promise/future.
Relates-To: OLPEDGE-2721
> Add TaskContinuation unit tests/change cancellation

- olp-cpp-sdk-core/cmake/curl.cmake
A new option OLP_SDK_USE_LIBCRYPTO is used to conditionally enable or
disable the libcrypto dependency when needed.
Resolves: OLPEDGE-2735
> Add a new cmake option OLP_SDK_USE_LIBCRYPTO

- CMakeLists.txt
- README.md
- examples/CMakeLists.txt
- examples/android/app/CMakeLists.txt.in
- examples/android/app/build.gradle.in
- examples/cmake/gen_android_example.cmake.in
- external/CMakeLists.txt
- external/curl/CMakeLists.txt
- external/curl/CMakeLists.txt.curl.in
- external/curl/CurlAndroidCrossCompile.cmake
- external/curl/openssl/CMakeLists.txt
- external/curl/openssl/cmake/Config.cmake.in
- external/curl/openssl/crypto/CMakeLists.txt
- external/curl/openssl/crypto/buildinf.h.cmake
- external/curl/openssl/ssl/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/cmake/android.cmake
- olp-cpp-sdk-core/cmake/curl.cmake
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
In some rare cases HttpUrlConnection can cause issue with downloading
bundles. As alternative, we can use libcurl also for Android. The
change provides a way to download and build curl.
OLP_SDK_ENABLE_ANDROID_CURL=ON will enable and use it instead of
android http client.
Resolves: OLPEDGE-2717
> Add libcurl support for android.

- olp-cpp-sdk-core/src/client/OlpClient.cpp
The token_provider could return an ErrorCode, and it should be passed
to the outside.
Relates-To: OLPSUP-17954
> Handle the ErrorCode returned by token_provider

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
Use std::stoll which returns 8-bit value to save as time_t, which is
also 8-bit.
Related-To: OAM-1510
Signed-off-by: Yevhen Krasilnyk <ext-yevhen.krasilnyk@here.com>
> Replace stol with stoll for LRU time expiration.

- olp-cpp-sdk-core/include/olp/core/http/NetworkProxySettings.h
- olp-cpp-sdk-core/src/http/android/HttpClient.java
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
Added new HTTPS value for proxy settings, added support in Curl.
Added log messages for Android and Windows, that feature is not
supported for that platforms. Curl implementation was tested on
Ubuntu using mock-server.
Resolves: OLPEDGE-1099
Signed-off-by: Yevhen Krasilnyk <ext-yevhen.krasilnyk@here.com>
> Add HTTPS proxy support for Curl

- olp-cpp-sdk-core/src/utils/Dir.cpp
- Add error handling to detect if dir checked for access rights is
absent. Thus in case when access() method returns error, and
errno variable is set to ENOENT (no such entry), false returned
to indicate that directory with proper access rights could be
created
Relates-To: OAM-1168
Signed-off-by: Viacheslav Marusyk <ext-viacheslav.marusyk@here.com>
> Change readonly result in case of absent target

- olp-cpp-sdk-core/src/utils/Dir.cpp
- Create a new directories with r/o permission for other users
Relates-To: OAM-1535
Signed-off-by: Viacheslav Marusyk <ext-viacheslav.marusyk@here.com>
> Change access permissions for newly created dirs

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.h
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
A new API VersionedLayerClient::QuadTreeIndex has been introduced
to get partitions including additional fields.
PartitionsRepository::GetTile and
PartitionsRepository::GetQuadTreeIndexForTile APIs have been extended
with additional_fields argument.
QuadTreeIndex class has been extended with crc.
New tests have been added to cover source code changes.
Touched test files have been slightly refactored.
Relates-To: OAM-1496
> Add API for getting Partition with TileRequest

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
Change the order of getting data from cache based on
level: previously the first check started from the highest
value, currently	from the lowest.
Relates-To: OLPSUP-18351
> Change the order of getting data from cache

- external/curl/CMakeLists.txt.curl.in
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
Android certificates are stored using MD5 hash function,
but OpenSSL is using SHA-1 for certificates lookup.
So add custom lookup method for Android to use MD5.
Relates-To: OAM-1458
> Add custom lookup method for cURL

- olp-cpp-sdk-dataservice-read/src/generated/api/ConfigApi.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientCacheTest.cpp
Fix path duplication when using catalog endpoint provider:
as it's base url being set in GetStaticUrl method of OlpClient
there is no need to add path later in GetCatalog.
Relates-To: OLPEDGE-2730
> Fix path duplication with catalog endpoint provider

- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.h
- olp-cpp-sdk-dataservice-read/tests/QuadTreeIndexTest.cpp
The recently introduced CRC field breaks the binary compatibility with
old data, the read method should check for CRC existence before reading
it.
Relates-To: OAM-1496
> Fix the QuadTreeIndex CRC binary compatibility

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
Add device_id property to the SignInProperties for implementing
rate limiting by device functionality.
Relates-To: OLPEDGE-2745
> Add device_id field to SignInProperties

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/InMemoryCache.cpp
- olp-cpp-sdk-core/src/cache/ProtectedKeyList.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
- olp-cpp-sdk-core/tests/cache/ProtectedKeyListTest.cpp
Add cache optimizations
Replace substr to memcmp to avoid additional allocations
and put it to the IsPrefix function.
Put checking memory cache from the first cache in the order
for checking Contains to the last one as it usually small
in size and and not sufficient to store the entire cache.
Add checks expiry validity in case of LRU cache as there is no
need for additional checks if the expiry is not valid
Check protected_data size in IsProtected if there are elements
in ProtectedKeyList.
Relates-To: OLPSUP-18424
> Add cache optimizations

- olp-cpp-sdk-dataservice-read/src/DownloadItemsJob.h
- olp-cpp-sdk-dataservice-read/src/QueryMetadataJob.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientPrefetchPartitionsTest.cpp
Add checking if the download operation was cancelled
after getting a result and not wait for all operations
to be done.
Relates-To: OLPEDGE-2746
> Add check if an operation was cancelled

- olp-cpp-sdk-core/include/olp/core/client/ApiError.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
This helps speed-up cancelling of the operation as chain of contexts
doesn't break. Previously to this the execution_context was not used
internally in the PrefetchTilesHelper::Prefetch() method which
resulted in a break of the cancellation context chain and thus
it was not able to cancell all subsequently triggered prefetch
jobs from the one master context which was handed over to the caller
of the VersionedLayerClient::PrefetchTiles() API.
Relates-To: OLPSUP-17825
> Wrap PrefetchTiles call into CancellationContext

- olp-cpp-sdk-core/include/olp/core/client/ApiError.h
- olp-cpp-sdk-core/include/olp/core/client/ApiResponse.h
- olp-cpp-sdk-core/include/olp/core/client/BackdownStrategy.h
- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/client/ApiResponseTest.cpp
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/src/ExtendedApiResponse.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/BlobApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/VolatileBlobApi.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- tests/common/mocks/NetworkMock.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Added `ExtendedResponse` and `ExtendedCallback` types that uses
`olp::client::NetworkStatistics` as a payload.
Enable the GetAggregatedData and QuadTreeIndex APIs to return the
extended responses.
Added NotFound, Unknown helper methods to `ApiError` class.
Fixed a warning in `BackdownStrategy` class.
Relates-To: OLPEDGE-2753
> Extend the ApiResponse type with optional payload

- olp-cpp-sdk-authentication/src/AuthenticationCredentials.cpp
Because it leads to std::bad_cast exception on certain GCC versions,
including GCC 7.5. This is a known GCC bug.
Relates-To: OAM-1620
> Do not use std::regex during static initialization

- README.md
- docs/GettingStartedGuide.md
Update documentation due to technical writing standards.
Moved the "Install the SDK" and "Build the SDK" sections from README.md to GettingStartedGuide.md.
Moved the "Why Use" topic to Introduction. 
Changed outdated platform URLs to actual ones.
Relates-To: TECHDOCS-1227
Signed-off-by: Nataliia Plakhtii <ext-nataliia.plakhtii@here.com>
> Update HERE SDK for C++ documentation

- olp-cpp-sdk-authentication/tests/AuthenticationClientTest.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/tests/thread/ContinuationTest.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/TokenEndpointTest.cpp
- tests/integration/olp-cpp-sdk-authentication/TokenProviderTest.cpp
Introduce a fast-path for 'mutable-cache-only' scenarios and go to the
microseconds' territory: for the applicable cases release time become
<1ms (original time depends on the `keys` size, e.g. 200 keys ~ 60ms).
This commit switches milliseconds to microseconds for the elapsed timer
Relates-To: OAM-1629, OAM-1563
> Speed-up DefaultCache::Release

- tests/functional/olp-cpp-sdk-dataservice-read/DataserviceReadVersionedLayerClientTest.cpp
Platform now reports `(404) Not Found` error instead of expected
`(400) Bad Request` for non-existent layers. Update tests accordingly.
Relates-To: OLPEDGE-2764
> Change BadRequest to NotFound error in tests

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
Not found messages for partition and quad tree index are quite noisy
and besides of that affect performance in certain scenarios.
Decrease them to DEBUG level as they do not bring much on current level
Relates-To: OAM-1686
> Decrease log level for some messages

- olp-cpp-sdk-core/src/geo/tiling/TileKey.cpp
Not the most efficient way of converting number to string. Replace
with dedicated std::to_string.
`ToHereTile` is being used a lot in the logs so any performance gains
are welcomed.
Relates-To: OAM-1686
> Remove std::ostringstream from TileKey::ToHereTile

- README.md
- docs/GettingStartedGuide.md
Update documentation due to technical writing standards.
Moved the Installation instructions from README.md to GettingStartedGuide.md.
Moved the "Build the SDK" section from README.md to GettingStartedGuide.md.
Moved the "Why Use" topic to Introduction (in GitLab).
Added Table of Contents.
Added the reference link in README.
Changed outdated platform URLs to actual ones.
Relates-To: TECHDOCS-1227
Signed-off-by: Nataliia Plakhtii ext-nataliia.plakhtii@here.com
> Update Data SDK for C++ documentation

- olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
Pass CancellationContext to NamedMutex. Check IsCancelled before locking mutex. Add GetBlobDataCancelParralellRequest test.
Resolves: OLPSUP-20250
Signed-off-by: Yevhen Krasilnyk <ext-yevhen.krasilnyk@here.com>
> Add check for IsCancelled in NamedMutex

- olp-cpp-sdk-core/cmake/curl.cmake
Unconditional search may break the build in some cases when OpenSSL was already found in some parent projects
Relates-To: OAM-1768
> Look for OpenSSL only when needed

- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.h
Spinlock loads the CPU quite substantially, reduce it by using condition_variable
Relates-To: OAM-1784
> Replace spinlock with condition_variable

- .github/workflows/psv_pipelines.yml
- azure-pipelines.yml
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/NamedMutex.h
Change the IsCanceled call to the atomic_bool variable. Upon cancellation the variable is set to true, means we don't lock the mutex inside CancellationContext. Which eliminates the lock ordering problem. Move the token reset code out of lock_mutex_.
Relates-To: OAM-1807
> Change the NamedMutex

- olp-cpp-sdk-core/src/client/ApiLookupClientImpl.cpp
- olp-cpp-sdk-core/tests/client/ApiLookupClientImplTest.cpp
- tests/common/PlatformUrlsGenerator.cpp
- tests/integration/olp-cpp-sdk-core/ApiLookupClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientCacheTest.cpp
Required for usage with DSP in order to not confuse different endpoints. 
This is an ugly hack.
Relates-To: OAM-1783
> Use service name for client's base URL

- olp-cpp-sdk-core/include/olp/core/utils/Dir.h
- olp-cpp-sdk-core/src/utils/Dir.cpp
This commit fixes the recursive behaviour of the olp::utils::Dir::Size() method to go all the way deep and find all not filtered out files to consider for calculating the dir size.
This is done by using a queue to push every found dir inside the currently scanned dir onto it for further dept scanning.
Relates-To: OLPEDGE-2700
> Fix olp::utils::Dir::Size() recursive behaviour.

- azure-pipelines.yml
The current one is being deprecated on December 1st.
Relates-To: OLPEDGE-2779
> Update macOS image version

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Updated CHANGELOG and CMakeLists files for the release v1.15.2
Relates-To: OLPEDGE-2777
> Release v1.15.2

- tests/functional/olp-cpp-sdk-core/DirTest.cpp
This commit fixes the warning treated as an error. It was a blocker.
Relates-To: OLPEDGE-2780
> Suppress ignoring return value warning

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
Since protected cache could be used as a static cache it is expected to be able to use it even when there is no available space on device. But when protected cache is being open in R/W mode levelDb may try to create some files and this failure would be treated later as a corrupted cache.
Instead, on `no space left` errors we will try to open the cache again but in read-only mode to enforce static behavior.
Relates-To: OLPSUP-21193
> Open cache in r/o mode on `no space left` errors

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
Do not interfere with CURL lookup management, since we need to only
allocate and setup lookup.
Relates-To: OLPSUP-21143
> Use CURL to handle lookups

- olp-cpp-sdk-core/src/utils/Dir.cpp
- tests/functional/olp-cpp-sdk-core/DirTest.cpp
Filtering should be applied for files only.
Relates-To: OLPEDGE-2733
> Fix the Dir::Size API for Windows

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
Run compaction for a limited number of attempts since leveldb does not signal in any way that it failed to compact, and we may try to compact indefinitely.
Relates-To: OLPSUP-22147
> Limit number of compactions

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
Log appears too often when the DEBUG level is disabled.
Relates-To: OAM-1945
> Reduce the logging level in PartitionsRepository

- .github/workflows/psv_pipelines.yml
- codecov.yml
- scripts/linux/psv/test_psv.sh
- tests/common/PlatformUrlsGenerator.cpp
Corrected BUILD_TYPE to COVERAGE.
Add extra ubuntu 18.04 job which now passes Codecov.
Previously, switch to 20.04 caused failure on Codecov.
Also add extra 22.04 job on gcc-9.
Fix test to adapt to gcc-9.
Relates-TO: OLPEDGE-2799
> Fix CodeCov job

- .github/workflows/psv_pipelines.yml
- scripts/linux/psv/test_psv.sh
CodeCov required 18.04 in the past,
but now Github Actions stopped running 18-04
image at all.
CodeCov works on 22.04 properly.
Relates-To: OLPEDGE-2799
> Switch Ubuntu 18.04 job to 22.04

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
TLS 1.2 is considered as recommended minimum to be on the safe side
Relates-To: OAM-1898
> Require TLS 1.2 or later

- olp-cpp-sdk-dataservice-write/tests/VersionedLayerClientImplTest.cpp
Compiler found that pointer to temp object was used. The behaviour of such code is unpredictable.
Relates-To: OLPSUP-23470
> Fixes another warning about dangling pointer

- olp-cpp-sdk-core/include/olp/core/http/NetworkSettings.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-core/tests/http/NetworkSettingsTest.cpp
NetworkSettings::GetRetries() is not used in any of network implementations so it can be freely deprecated and removed. Related method NetworkSettings::WithRetries(...) can aslo be deprecated and removed.
Relates-To: OLPSUP-23500
> Deprecates unused methods in network settings

- docs/authenticate.md
Documentation-vs-code sync. `provider` member was deprecated for a long time and it has been removed recently.
Relates-To: OAM-2009
> Replace `provider` with `token_provider` in docs

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/cache/CacheSettings.h
- olp-cpp-sdk-core/include/olp/core/utils/Dir.h
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
- olp-cpp-sdk-core/src/cache/DiskCacheEnv.cpp
- olp-cpp-sdk-core/src/cache/DiskCacheEnv.h
- olp-cpp-sdk-core/src/utils/Dir.cpp
- tests/integration/CMakeLists.txt
- tests/integration/olp-cpp-sdk-core/DefaultCacheTest.cpp
When enabled it overrides the creation permissions for files and directories to enable access for all user in the system. This enables different users in the system to access the cache.
Relates-To: OAM-2037
> Add a new extend_permissions cache option.

- olp-cpp-sdk-core/src/cache/DiskCacheEnv.cpp
DEFFILEMODE and ACCESSPERMS may be not accessible on some platforms
Relates-To: OAM-2037
> Use own constants for permissions

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
- olp-cpp-sdk-core/include/olp/core/http/CertificateSettings.h
- olp-cpp-sdk-core/include/olp/core/http/Network.h
- olp-cpp-sdk-core/include/olp/core/http/NetworkInitializationSettings.h
- olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
- olp-cpp-sdk-core/src/http/Network.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
- tests/performance/NetworkWrapper.h
Certificate settings for setting up SSL for CURL by using blobs
Relates-To: OLPEDGE-1750
> Custom certificate settings

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
Fixes an issue when SDK was initialised during Flight Mode enabled. DNS was stuck and after switching off Flight Mode SDL couldn't resolve DNS.
Relates-To: IOTSDK-18403
> Cleanups DNS cache on error in CURL (Android)

- olp-cpp-sdk-core/CMakeLists.txt
Fix the olp-cpp-sdk-core/CMakeLists.txt to include the externals include directory.
Relates-To: OLPEDGE-2828
> Fix cmake scripts

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
Change the GetPartitions API, now it supports requests with more than 100 partitions which is an backend API limit.
Relates-To: OLPSUP-25510
> Change the GetPartitions API

- olp-cpp-sdk-core/src/client/PendingUrlRequests.cpp
Do not post messages to log for CancelAll and CancelAllAndWait if there is no pending or cancelled requests.
Resolves: OLPEDGE-2822
> Improve logging in PendingUrlRequests.

- olp-cpp-sdk-core/include/olp/core/client/OlpClient.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/VersionedLayerClient.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClient.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/MetadataApi.h
- olp-cpp-sdk-dataservice-read/src/repositories/AsyncJsonStream.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/AsyncJsonStream.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsSaxHandler.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsSaxHandler.h
- olp-cpp-sdk-dataservice-read/tests/AsyncJsonStreamTest.cpp
- olp-cpp-sdk-dataservice-read/tests/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/tests/PartitionsSaxHandlerTest.cpp
The new API uses a SAX parser and a JSON byte stream to parse the
layer partitions while they are downloading. Using this approach we
can process large responses without any memory impact, since we do not
wait for the full response, and parse it afterward.
Relates-To: OLPEDGE-2832
> Add StreamLayerPartitions API 

- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
In case of error we must close the stream.
Relates-To: OAM-2174
> Fix the stream is not closed issue

- olp-cpp-sdk-authentication/include/olp/authentication/Settings.h
- olp-cpp-sdk-authentication/src/Settings.cpp
- tests/integration/olp-cpp-sdk-authentication/TokenProviderTest.cpp
The token provider read from a credentials file in the method `AuthenticationCredentials::ReadFromStream()` was not used for the authentication request.
Relates-To: OLPEDGE-2834
> Use custom token endpoint url from AuthenticationCredentials

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/utils/Credentials.h
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/utils/Credentials.cpp
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/utils/UtilsTest.cpp
Censoring of credentials was added to debug log messages for Windows, Android and curl implementation.
Resolves: OAM-2216
> Censor credentials in debug log messages.

- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.mm
- olp-cpp-sdk-core/src/http/ios/OLPHttpTask+Internal.h
- olp-cpp-sdk-core/src/http/ios/OLPHttpTask.mm
Currently task ID is used as a key in the map. This is OK while there is only one session because task ID is unique inside the session. We are creating separate session for requests with proxy so task ID is not unique anymore. Request ID is unique across the Network instance and task description is available same a the task ID.
Relates-To: OLPEDGE-2846
> Use request ID as task description

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/cmake/ios.cmake
- olp-cpp-sdk-core/include/olp/core/context/Context.h
- olp-cpp-sdk-core/include/olp/core/context/EnterBackgroundSubscriber.h
- olp-cpp-sdk-core/src/context/Context.cpp
- olp-cpp-sdk-core/src/context/ContextInternal.cpp
- olp-cpp-sdk-core/src/context/ContextInternal.h
- olp-cpp-sdk-core/src/context/ios/ContextInternal.mm
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/context/ContextTest.cpp
Context allows to inform iOS network implementation that the app is going to switch background-foreground. And it allows to store background session completion handlers.
Relates-To: OLPEDGE-2847
> Add iOS background downloading harness to Context

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
This MR fixes compilation on Rocky Linux 9 (and thus likely also on
RHEL9), which uses curl-7.76 and thus - as noted on
https://curl.se/libcurl/c/CURLOPT_CAINFO_BLOB.html - does not yet have
support for CURLOPT_CAINFO_BLOB.
Relates-To: OLPSUP-27800
Signed-off-by: Robert Buchholz <robert.buchholz@here.com>
> Fix minimum curl version for CURLOPT_CAINFO_BLOB

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
A previous commit correctly raised the CURL version that's necessary to support SSL info with blobs to 7.77, but the corresponding log message still stayed at the old value of 7.71.
Relates-To: OLPSUP-27800
> Sync info message with actual behavior.

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
Fixes data race between Open/Close and Size.
Relates-To: OLPSUP-27831
> Syncronize DefaultCacheImpl::Size

- olp-cpp-sdk-dataservice-read/tests/MetadataApiTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
Remove the has_value usage, since it's not available in old boost
Relates-To: OLPEDGE-2853
> Fix the boost::optional usage

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsSaxHandler.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
PartitionsSaxHandler::Abort() was useless. And it is not enough to Abort() when we are waiting for characters in the stream.
Relates-To: OLPEDGE-2859
> Allow to cancel partitions stream on parsing

- scripts/android/build.sh
Looks like latest Android studios changed that. Trying to follow.
Adapted to latest Ubuntu20-04 image updates in 
https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20240107.1
Relates-To: OLPEDGE-2855
> Change Android sdkmanager location

- scripts/ios/azure_ios_build_psv.sh
An attempt to pass CI
Relates-To: OLPEDGE-2852
> Getting rid of boost installed in the CI image

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsCacheRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
Skipped as not related to the offline map data:
StreamLayerClient, ApiCacheRepository, CatalogSettings
Relates-To: OLPEDGE-2852
> Check result of cache related operations

- scripts/ios/azure_ios_build_psv.sh
It appeared not all images has boost installed from brew so we don't want to fail in that case
Relates-To: OLPEDGE-2861
> Ignore brew boost uninstall error for iOS CI nodes

- CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/cmake/offline.cmake
- olp-cpp-sdk-core/src/http/Network.cpp
- olp-cpp-sdk-core/src/http/offline/NetworkOffline.cpp
- olp-cpp-sdk-core/src/http/offline/NetworkOffline.h
There are cases where device want to rely on the offline data only or even want to completely avoid network related libs like libcurl and libssl.
Relates-To: OLPEDGE-2861
> Add NetworkOffline for offline environment

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
This allows read-only protected cache location at start. Later when there is a need to write to the protected cache it can be opened as mutable and it is going to be an error if we have no write permission at that time.
Relates-To: OLPEDGE-2858
> Return Postponed if protected cache failed to open

- .github/workflows/psv_pipelines.yml
- README.md
- external/CMakeLists.txt
- scripts/ios/azure_ios_build_psv.sh
Add all possible builds for iOS/MacOS.
Correct tools versions in README.md.
Relates-To: MINOR-IMPROVE-CI
> CI: Add iOS/MacOS new parralel builds

- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-core/src/client/OlpClient.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/StreamApi.cpp
- olp-cpp-sdk-dataservice-write/src/IndexLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-write/src/generated/BlobApi.cpp
- olp-cpp-sdk-dataservice-write/tests/VersionedLayerClientImplPublishToBatchTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-write/VersionedLayerClientPublishToBatchTest.cpp
The argument is constant reference
Fixing gcc13 warning
> Avoid redundant move. gcc13

- olp-cpp-sdk-dataservice-read/src/ReleaseDependencyResolver.cpp
- olp-cpp-sdk-dataservice-read/src/ReleaseDependencyResolver.h
Release logic should consider what was requested to be released and make assumption that requested tiles are already released
Relates-To: OLPSUP-28891
> Take into account what is planned to be released

- .github/workflows/psv_pipelines.yml
Exclude commit checker job on master
as it's failing due to GitHub feature
which adds PR# to every title afterwards.
This will make post submit workflow green.
Resolves: MINOR-IMPROVEMENT
> Exclude commit checker job on master

- olp-cpp-sdk-core/include/olp/core/utils/Dir.h
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/utils/Dir.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheTest.cpp
Scan cache folder for the unexpected directories as their presence means that the cache was changed outside of Data SDK, or the wrong cache was used in a first place.
Relates-To: OLPEDGE-2857
> Detect unexpected directories in the cache

- external/CMakeLists.txt
1.2.11 we are using is quite old
It is used indirectly when OLP_SDK_ENABLE_ANDROID_CURL is true.
Resolves: CI-MAINTENANCE
> Update zlib CI version

- CHANGELOG.md
- CMakeLists.txt
- README.md
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Updated changelog, CMake versions, readme
Relates-To: OLPEDGE-2868
> Release v1.18.0

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Changed name argument to const in Md5LookupGetBySubject to support OpenSSL v3.1.4
Relates-To: OLPEDGE-2876
> Changed name argument to const

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Make Md5LookupGetBySubject function compatible with openssl 1.x
Relates-To:  OLPEDGE-2876
> Add openssl backwards compatibility

- olp-cpp-sdk-dataservice-read/src/QueryMetadataJob.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Adds dedicated filtering for cases when only tile keys are required by the caller.
> Decrease number of memory reallocations

- .gitignore
- external/boost/CMakeLists.txt
- external/leveldb/CMakeLists-leveldb.txt
Fix the leveldb cmake script
Fix boost build on msvc
Add Clion default build folders to .gitignore
Relates-To: OLPEDGE-2887
> Fix the windows build

- .github/workflows/psv_pipelines.yml
- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/include/olp/core/cache/KeyValueCache.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.h
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
- tests/common/mocks/CacheMock.h
Change the PrefetchTiles behavior to promote existing data when it is requested but available in cache.
Relates-To: OAM-2436
> Add a new Promote API to KeyValueCache

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Wrong order of conditions was used
Relates-To: OLPEDGE-2879
> Fix condition for certificate logs

- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
When transient network error occurs,
eg timeout or network overload, use
retry settings in order to determine
if retry auth request, instead of
returning an error.
RelatesTo: IOTSDK-24136
> Retry Auth on network error

- README.md
- external/CMakeLists.txt
- minor OpenSSL recommended version update from 1.1.1g to 1.1.1w as latest security patch
- minor Xcode version adjust
- fix Health Check status badges: remove Azure CI, add Github Actions pipelines only as job badges are not supported directly.
- add Zlib to the dependencies list as SDK is indirectly dependant on it
Relates-To: DATASDK-3
> Minor Readme updates

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/logging/Log.h
- olp-cpp-sdk-core/include/olp/core/logging/LogContext.h
- olp-cpp-sdk-core/include/olp/core/logging/MessageFormatter.h
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
- olp-cpp-sdk-core/src/logging/Log.cpp
- olp-cpp-sdk-core/src/logging/LogContext.cpp
- olp-cpp-sdk-core/src/logging/MessageFormatter.cpp
- olp-cpp-sdk-core/src/thread/ThreadPoolTaskScheduler.cpp
- olp-cpp-sdk-core/tests/logging/MessageFormatterTest.cpp
- tests/common/ResponseGenerator.h
This change adds a per-thread logging context to the logging system, which can be set by the user and will then be logged from all threads and tasks created with that context.
This is useful to correlate requests from the client to any network requests made based on that request.
The logging formatter must be set up by including a `MessageFormatter::ElementType::ContextValue` with the 'format' set to the context key to use:
```c++
using ElementT = olp::logging::MessageFormatter::ElementType;
std::vector<ElementT> elements = {
ElementT(ElementType::Time, "%F %T"),
ElementT(ElementType::TimeMs, ".%03u "),
ElementT(ElementType::Level, "%s ["),
ElementT(ElementType::ContextValue, X_CORRELATION_ID),
ElementT(ElementType::Tag, "] %s: "),
ElementT(ElementType::Message, "%s")
};
```
The log …
> Add logging of per-context variables to logging system and network stack

- docs/get-started.md
Rename file to facilitate ToC updates on here.com/docs.
> TECHDOCS-2847: rename file to facilitate toc updates on here.com/docs

- olp-cpp-sdk-core/include/olp/core/client/ErrorCode.h
This error code may be used to signal shortage of available space on the target device.
Relates-To: OCMAM-3, OAM-2431
> New error code "NoSpaceLeft"

- olp-cpp-sdk-core/include/olp/core/cache/DefaultCache.h
- olp-cpp-sdk-core/include/olp/core/cache/KeyValueCache.h
- olp-cpp-sdk-core/src/cache/DefaultCache.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.h
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/cache/DiskCache.h
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
- olp-cpp-sdk-dataservice-read/tests/CatalogCacheRepositoryTest.cpp
Added main operations like Read, Write, Remove.
The difference with the old one is that new API may return actual error instead of cryptic `false`.
DefaultCache implementation was extended as well
to cover new methods.
Relates-To: OCMAM-3, OAM-2431
> Extension of KeyValueCache interface

- olp-cpp-sdk-dataservice-read/src/StreamLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/BlobApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/BlobApi.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.h
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/MetadataApiTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- tests/common/mocks/NetworkMock.cpp
- tests/common/mocks/NetworkMock.h
- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
Optimize allocations in QuadTreeIndex
Use a stream call API to download blobs to eliminate unnecessary copy
Relates-To: OLPEDGE-2444
> Optimizing hot code allocations

- .github/workflows/psv_pipelines.yml
Similar to the PSV.Linux.22.04.gcc13.OLP_SDK_ENABLE_DEFAULT_CACHE=OFF
Relates-To: CI
> Install gcc13 to PSV.Linux.22.04.gcc13

- olp-cpp-sdk-core/src/client/OlpClient.cpp
Take into account that we may detach request and
the fact that data callback may be missing in some cases.
Relates-To: OLPEDGE-2444
> Update logic around DataCallback

- olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/VolatileLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.h
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
Previously, some client APIs may ignore cache errors as they were not critical for the API to operate correctly. New option allows to enforce errors propagation in all cases when cache consistency is a key.
Relates-To: DATASDK-10
> New client option to propagate cache errors

- olp-cpp-sdk-dataservice-read/tests/NamedMutexTest.cpp
An attempt to make the test stable in the coverage test build
Relates-To: TESTS
> Increase NamedMutexTest.Cancel timeout

- olp-cpp-sdk-core/include/olp/core/client/ApiError.h
- olp-cpp-sdk-core/include/olp/core/generated/parser/JsonParser.h
- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-dataservice-read/src/generated/serializer/ByteVectorBuffer.h
- olp-cpp-sdk-dataservice-read/src/generated/serializer/JsonSerializer.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsCacheRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
- tests/common/KeyValueCacheTestable.h
- tests/common/mocks/CacheMock.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
This is necessary to move forward with advanced cache error handling.
This commit also includes new way of serializing to bytes vector.
Relates-To: OCMAM-61
> Adapt PartitionsCacheRepository to use Write

- .github/workflows/psv_pipelines.yml
Runners are deprecated and removed at this point.
Relates-To: DATASDK-17
> Remove MacOS 11 jobs

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VolatileLayerClientImplTest.cpp
This is an old behavior that was changed in the previous commit. Returning it as it breaks API expectations.
Relates-To: OCMAM-61
> Ignore `NotFound` error for partitions removal

- .gitlab-ci.yml
License scanning is deprecated.
Relates-To: OCMAM-75
> Fixed deprecations in Gitlab

- .github/workflows/psv_pipelines.yml
- .gitlab-ci.yml
- scripts/ios/azure_ios_build_psv.sh
After PR#1523 we are using only Xcode14 and 15 for builds
as they are default on macos-12, macos-13, macos-14.
However, macos-12 still contains Xcode13.1 which could be used.
Relates-To: MINOR-UPDATES-CI
> Add Xcode13 job

- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.cpp
- olp-cpp-sdk-authentication/tests/AuthenticationClientTest.cpp
When iOS device locale is set to location
which uses different timezeons depending on
daylight saving time (eg PST and PDT for
Los Angeles), then different `gmtoff` applied
by `strptime` for 'summer' and 'winter'
timestamps.
This results in the wrong translation of
datetime string into epoch.
Adapt code to iOS/MacOS behaviour, where
`timegm` updates an input parameter and
erases `gmtoff` value:
- remove logic to infer the offset using epoch datetime;
- store `gmtoff` value before calling `timegm`;
- offset result returned from `timegm` by saved `gmtoff`.
Relates-To: HERESDK-2568
> Adapt Datetime parser to DST timezones

- olp-cpp-sdk-authentication/src/AuthenticationCredentials.cpp
Some Windows distributions have no HOMEDRIVE or/and HOMEPATH vars set by default. They have USERPROFILE variable instead.
Relates-To: OCMAM-115
> Use USERPROFILE env variable to get home path on Windows

- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.mm
Session ID should be unique across the application. This is not the case when there are several network layers instances. Not the best but fast and easy way is to generate the ID using existing mechanism.
Relates-To: OCMAM-97
> Use generated ID for the background session.

- olp-cpp-sdk-core/include/olp/core/context/Context.h
- olp-cpp-sdk-core/src/context/Context.cpp
- olp-cpp-sdk-core/src/context/ContextInternal.h
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.h
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
Such environment is set up when one wants to run unit tests in Android Studio. Unit tests are run on host (not in emulator), but JNI and even many Android's core API like Context are still provided by Robolectric. On the other hand typical Android C++ headers like <android/log.h> are not accessible.
This patch adds checks for macro ANDROID_HOST which is defined on such enviroment.
Relates-To: HERESDK-1085
> Supports Android-like build on desktop

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/utils/Thread.h
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/thread/ThreadPoolTaskScheduler.cpp
- olp-cpp-sdk-core/src/utils/Thread.cpp
Extract Thread helper into separate
file, and use it to name spawned
threads.
Relates-To: HERESDK-3466
> Add missing thread names

- external/boost/CMakeLists.txt.boost.in
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.cpp
- olp-cpp-sdk-dataservice-read/src/generated/api/QueryApi.h
- olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.h
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
- olp-cpp-sdk-dataservice-read/tests/DataRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
- olp-cpp-sdk-dataservice-read/tests/VersionedLayerClientImplTest.cpp
- tests/common/PlatformUrlsGenerator.cpp
- tests/common/ReadDefaultResponses.cpp
- tests/common/ReadDefaultResponses.h
- tests/functional/olp-cpp-sdk-dataservice-read/ApiTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/HttpResponses.h
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Change the clint to perform query requests with default additional fields.
Fix the boost configuration error on Windows.
Fix various clang-tidy warnings.
Relates-To: OCMAM-179
> Change the VersionedLayerClient code

- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientProtectTest.cpp
- tests/functional/utils/MockServerHelper.cpp
- tests/utils/mock-server-client/Client.h
- tests/utils/mock-server-client/Expectation.h
Mock server required support for additional fields, and cache size should be tuned to accommodate increased data size
Relates-To: DATASDK-38
> Fix VersionedLayerClientProtectTest test

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
Now, all fields could be setup independently.
For example, only CA info, or client certificate.
Relates-To: HERESUP-978
> Allow flexible certificate configuration

- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.mm
- olp-cpp-sdk-core/src/http/ios/OLPHttpTask.mm
To prevent triggering handlers several times in a row. Currently
this should not harm the app because NSURLSessionDownloadTask tasks
are skipped in restartCurrentTasks.
Testing on iOS-13 simulator it was possible to get two same states
in a row using notifications. Maybe a simulator issue or iOS-13 case
which is the first where background mode delegates are in the Scene
delegate instead of Application delegate.
Relates-To: DATASDK-39
> Background subscriber to check current value

- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
Mapped to ErrorCode::IO_ERROR
- NSURLErrorSecureConnectionFailed
- NSURLErrorCannotFindHost
- NSURLErrorDNSLookupFailed
- NSURLErrorResourceUnavailable
NSURLErrorSecureConnectionFailed is visible as SSL handshake timeout on slow network with high delays. The rest are more to be on a safe side as their descriptions are not stating are further tries useless.
Relates-To: DATASDK-40
> Add several iOS network errors to retry list

- olp-cpp-sdk-core/cmake/curl.cmake
In general, we don't need to link against OpenSSL. Link is needed only for cURL enabled network for Android.
Relates-To: HERESUP-1431
> Rework OpenSSL link requirements

- olp-cpp-sdk-core/include/olp/core/math/AlignedBox.h
Not all template functions were actually compiling, and no test ever instantiated the classes fully.
> Fix compilation of AlignedBox

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
The crash happened on a call to Size method on a closed cache.
Relates-To: OCMAM-106
> Fix a crash in DiskCache::Size method

- olp-cpp-sdk-core/cmake/curl.cmake
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.h
- scripts/linux/nv/cppcheck_and_upload_sonar.sh
OpenSSL now required, and should be always present
hence `OLP_SDK_NETWORK_HAS_OPENSSL` could be removed
Relates-To: HERESUP-1440
> Always require OpenSSL

- olp-cpp-sdk-core/include/olp/core/client/OlpClient.h
- olp-cpp-sdk-core/src/client/OlpClient.cpp
Required for extensions that take an OlpClient instance to do some additional work.
> Add getter for OlpClientSettings

- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.mm
Foreground tasks are deleted in didCompleteWithError. Background tasks are getting both didFinishDownloadingToURL and didCompleteWithError events but the downloaded content is in the didFinishDownloadingToURL only
Relates-To: DATASDK-45
> Delete cancelled and not valid background tasks

- olp-cpp-sdk-core/include/olp/core/utils/Dir.h
- olp-cpp-sdk-core/src/cache/DiskCache.cpp
- olp-cpp-sdk-core/src/utils/Dir.cpp
- tests/functional/olp-cpp-sdk-dataservice-read/VersionedLayerClientProtectTest.cpp
- tests/integration/olp-cpp-sdk-core/DefaultCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/CatalogClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientCacheTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerTestBase.cpp
- tests/integration/olp-cpp-sdk-dataservice-read/VolatileLayerClientCacheTest.cpp
Use correct one instead
Relates-To: OCMAM-212
> Remove deprecated `Dir` functions

- olp-cpp-sdk-core/include/olp/core/http/NetworkSettings.h
- olp-cpp-sdk-core/src/http/NetworkSettings.cpp
- olp-cpp-sdk-core/tests/http/NetworkSettingsTest.cpp
Deprecated ones were used only in tests
Relates-To: OCMAM-212
> Remove deprecated `NetworkSettings` functions

- olp-cpp-sdk-core/src/http/ios/OLPHttpTask.mm
It is 'synchronized' in the didCompleteWithError callback so it's better to add 'synchronized' in the restarting as well
Relates-To: DATASDK-45
> OLPHttpTask to lock toIgnoreResponse before usage

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Update CHANGELOG.md and CMakeLists.txt files for the v1.21.0 release.
Relates-To: DATASDK-48
> Release v1.21.0

- olp-cpp-sdk-core/include/olp/core/client/HttpResponse.h
- olp-cpp-sdk-core/tests/client/PendingUrlRequestsTest.cpp
Copy constructor and copy assignment should take network statistics into account for precise calculation.
Relates-To: OCMAM-308
> HttpResponse to copy network statistics

- .github/workflows/psv_pipelines.yml
- scripts/ios/azure_ios_build_psv.sh
- scripts/macos/psv/azure_macos_build_psv.sh
According to updates on images: macos-12 deprecation we should use macos-13 and Xcode 14.3 as the lowest versions in CI validation.
Also, add х86_64 macos-13 image with job separately, while other images 
are by default on ARM.
Additional compiler options are related boost internal warnings 
on newer xcodes.
Add more MacOS jobs to cover more combinations: MacOS-Xcode.
Relates-TO: DATASDK-47
> Update Apple CI jobs, skip boost compile warning

- README.md
- external/CMakeLists.txt
- external/boost/CMakeLists.txt.boost.in
- scripts/macos/psv/azure_macos_build_psv.sh
Update boost dependency.
Use newer boost v 1.82.0
Remove workaround in compilation.
Relates-To: DATASDK-52
> Boost update on CI

- .github/workflows/psv_pipelines.yml
- scripts/windows/build.sh
Add Win build job to have minimal verification on
Windows. Use the image with VC 2019.
Minor updates in jobs to remove temporary tips.
Relates-To: OLPEDGE-2873, DATASDK-53
> Add Win build job

- olp-cpp-sdk-authentication/include/olp/authentication/Settings.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenResult.h
- olp-cpp-sdk-authentication/src/TokenEndpointImpl.cpp
- olp-cpp-sdk-authentication/src/TokenEndpointImpl.h
- olp-cpp-sdk-authentication/src/TokenResult.cpp
- tests/common/matchers/NetworkUrlMatchers.h
- tests/integration/olp-cpp-sdk-authentication/AuthenticationClientTest.cpp
- tests/integration/olp-cpp-sdk-authentication/TokenEndpointTest.cpp
It is attached to the token request and can be used on server side in the authentication process.
Relates-To: DATASDK-8
> Add project scope to the settings

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.h
Make sure that context values are transferred to network thread.
Relates-To: HERESUP-4906
> Add LogContext to NetworkWinHttp

- olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
Reverts heremaps/here-data-sdk-cpp#1573
> Revert "Add a version additional field value"

- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsSaxHandler.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsSaxHandler.h
- olp-cpp-sdk-dataservice-read/tests/PartitionsSaxHandlerTest.cpp
Parser was not expecting compressedDataSize field and failed to parse the JSON.
Relates-To: OCMAM-223
> Enable SAX parser to handle compressedDataSize

- olp-cpp-sdk-dataservice-read/src/repositories/AsyncJsonStream.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/AsyncJsonStream.h
- olp-cpp-sdk-dataservice-read/tests/AsyncJsonStreamTest.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
Decreases time needed to process single JSON, and
reduces memory footprint size.
Relates-To: DATASDK-57
> Double-buffering for JSON async stream

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.h
Required to cover the completion callback
Relates-To: HERESUP-4906
> Move log_context to ResultData

- olp-cpp-sdk-dataservice-read/src/repositories/AsyncJsonStream.cpp
- olp-cpp-sdk-dataservice-read/tests/PartitionsRepositoryTest.cpp
Helps to avoid "empty JSON" errors when stream is being reset
Relates-To: DATASDK-57
> Check write buffer on stream closed check

- olp-cpp-sdk-core/src/http/android/HttpClient.java
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
- olp-cpp-sdk-core/src/http/android/NetworkAndroid.h
Network retries are implemented in the application layer
Relates-To: OCMAM-396
> Remove Android network retries

- external/leveldb/CMakeLists-leveldb.txt
Setting -Werror as PUBLIC flag means that all targets that link to leveldb will stop compiling on the first warning. An intermediate library must never propagate that flag to parent projects.
> Do not propagate -Werror from leveldb

- .github/workflows/psv_pipelines.yml
- README.md
- scripts/android/build-test-emulator.sh
- scripts/ios/fv/gh-actions-functional-network-test.sh
- update and fix FV pipes
- updatecopyright in readme
- update CI due to recent macOS runner changes
> Minor copyright and CI update

- olp-cpp-sdk-core/include/olp/core/client/ApiError.h
- olp-cpp-sdk-core/include/olp/core/client/ErrorCode.h
- olp-cpp-sdk-core/include/olp/core/http/HttpStatusCode.h
Used to indicate absence of network connectivity
Relates-To: OCMAM-420
> New error code: Offline

- olp-cpp-sdk-core/include/olp/core/http/NetworkResponse.h
- olp-cpp-sdk-core/src/http/NetworkResponse.cpp
- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Implement request diagnostics for NetworkCurl.
Add response timings for a request, it includes timings for:
* queue time
* dns resolution time
* connect + ssl handshake time
* send, wait, receive time
* total time taken
Relates-To: OCMAM-418
> Extend network response with diagnostics

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Disable timings for CURL versions before 7.61
Relates-To: OCMAM-418
> Disable CURL diagnostics for old versions

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/http/adapters/HarCaptureAdapter.h
- olp-cpp-sdk-core/src/http/adapters/HarCaptureAdapter.cpp
Implement HarCaptureAdapter to capture network requests and generate HAR files. It is capable to capture network requests along with headers, status codes, transfer sizes and timings.
Relates-To: OCMAM-418
> Add HarCaptureAdapter class

- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-core/include/olp/core/geo/tiling/PathTiling.h
- olp-cpp-sdk-core/tests/CMakeLists.txt
- olp-cpp-sdk-core/tests/geo/tiling/PathTilingTest.cpp
Introduce the iterator types used to traverse and slice a 
GeoCoordinates sequence to tiles:
* Add TilingIterator to convert the GeoCoordinates to a TileKeys
* Add AdjacentPairIterator to iterate over the adjacent pairs
* Add LineSliceIterator type to slice the path from point A to point B
* Add various helper functions to ease the iterators creation
Add a Bresenham's line algorithm used to generate tiles over a grid
Relates-To: OCMAM-461
> Add path tiling utilities

- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.mm
Default number of parallel connection per host
is 6 for hardware iOS device. This limits the
speed of network stages of map download
and map update.
Increase this limit to 32 connections.
Relates-To: HERESDK-5947
> Increase parallel connection limit for iOS

- external/leveldb/CMakeLists.txt.leveldb.in
CMake 4.0 doesn't support cases when required version is too low
> Force CMake 3.5 for Snappy

- olp-cpp-sdk-dataservice-read/src/repositories/CatalogCacheRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
The messages are just information about the action and not the outcome
Relates-To: DATASDK-70
> Lower the log level for some messages

- olp-cpp-sdk-dataservice-read/src/BlobDataReader.h
- olp-cpp-sdk-dataservice-read/src/BlobDataWriter.h
- olp-cpp-sdk-dataservice-read/src/ReleaseDependencyResolver.cpp
- olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.cpp
- olp-cpp-sdk-dataservice-read/src/repositories/QuadTreeIndex.h
Added a `fields` parameter to GetIndexData method.
Change GetIndexData method to skip string fields which are not needed.
Relates-To: DATASDK-64
> Decrease allocations in QuadTreeIndex

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Make sure we are using http2 when it's possible
Relates-To: OCMAM-502
> Change NetworkCurl

- olp-cpp-sdk-core/CMakeLists.txt
Otherwise it's possible to get into undefined symbols issue in certain cases
Relates-To: Minor
> Link Foundation framework to iOS core explicitly

- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.h
- olp-cpp-sdk-core/src/http/ios/OLPHttpClient.mm
- olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
It is useful to know more details in further investigation in what circumstances unknown error has been returned like exact status code, background or foreground, etc
Relates-To: OCMAM-494
> Log more when unknown error returned on iOS

- olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
Make sure we are using http2 when it's possible
Relates-To: DATASDK-63
> Change NetworkWinHttp implementation

- .github/workflows/psv_pipelines.yml
- scripts/linux/psv/build_psv.sh
Following github actions changes. For more details, see: https://github.com/actions/runner-images/issues/11101
Updated distros has different set of software versions so
gcc7 updated to gcc9, clang7 updated to clang11
clang11 found warnings in the project code and in the boost
that other compilers are OK with so silenced that warning for clang
Relates-To: DATASDK-73
> Switch CI to ubuntu 22.04

- CHANGELOG.md
- CMakeLists.txt
- olp-cpp-sdk-authentication/CMakeLists.txt
- olp-cpp-sdk-core/CMakeLists.txt
- olp-cpp-sdk-dataservice-read/CMakeLists.txt
- olp-cpp-sdk-dataservice-write/CMakeLists.txt
Updated CHANGELOG.md and CMakeLists.txt files
Relates-To: DATASDK-74
> Release v1.23.0

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Let the cURL itself decide
Relates-To: DATASDK-74
> Do not enforce HTTP/2 for cURL-based network

- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.h
- olp-cpp-sdk-core/include/olp/core/client/CancellationContext.inl
A hash needs a hashing function and a way to determin equality. Since we don't want to add a comparison operator, let's add another helper so we can store CancellationContext in std::unordered_set and friends.
> Allow CancellationContext in hashes

- olp-cpp-sdk-core/src/cache/DiskCache.cpp
Otherwise it is possible to get 'no matching function for call to find' error while compiling.
> Include algorithm to DiskCache explicitly

- .github/workflows/psv_pipelines.yml
- switch gcc13 to gcc14 on Ubuntu
- add job which is testing latest gcc in non-blocking
status using: continue-on-error: true
- when job become stable above flag to be removed on CI
- update windows from deprecated 2019 to 2022
- minor job naming update
Relates-To: OCMAM-532
> Github Actions updates

- olp-cpp-sdk-core/src/cache/DefaultCacheImpl.cpp
- olp-cpp-sdk-core/tests/cache/DefaultCacheImplTest.cpp
Currently, for mutable cache, the key should be in the protected list or LRU to be read. Internal keys are pretty important and should have priority to be read without additional restrictions.
Relates-to: DATASDK-71
> Skip internal keys' lookup in LRU for the DefaultCache.

- .github/workflows/psv_pipelines.yml
- scripts/misc/clang_format_ci.sh
There is no clang-format 6.0 binaries for current ubuntu versions.
Github pool has no old ubuntu images. So preparation steps are
downloading binaries from older ubuntu distros and installing them.
python-is-python2 symlinks python to python2 and covers clang-format 6.0
package requirement for python. python-is-python3 is conflicting with
the python-is-python2 thus removed
> Add clang-format check

- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationCredentials.h
- olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationSettings.h
- olp-cpp-sdk-authentication/include/olp/authentication/AuthorizeRequest.h
- olp-cpp-sdk-authentication/include/olp/authentication/Settings.h
- olp-cpp-sdk-authentication/include/olp/authentication/TokenResult.h
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientImpl.h
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.cpp
- olp-cpp-sdk-authentication/src/AuthenticationClientUtils.h
- olp-cpp-sdk-authentication/src/AuthenticationCredentials.cpp
- olp-cpp-sdk-authentication/src/AuthorizeRequest.cpp
- olp-cpp-sdk-authentication/src/TokenEndpointImpl.cpp
- olp-cpp-sdk-authentication/src/TokenEndpointImpl.h
- olp-cpp-sdk-authentication/src/TokenResult.cpp
- olp-cpp-sdk-authentication/tests/DecisionApiClientTest.cpp
Currently, SDK requires C++11 minimum.
So, boost::optional type is used for optional values. For C++17 and above more convenient is to use std::optional instead. The task NLAM-23 is about making this type configurable. This commit is a second part of the task: olp-cpp-sdk-authentication.
Relates-To: NLAM-23
> Use std::optional if available.

- scripts/misc/clang_format_ci.sh
Verification script returns error for deleted files thus the whole job marked as failed.
There's no need to check deleted files
Added .mm (Objective-C++) files to the list of verified files as such files are present in the repository and have formatting setup as well
> Exclude deleted files from format verification

- olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
Otherwise some combinations of server-clients may fail
to transfer the data with bad request error
and data similar to '"TE" may only be "trailers" in HTTP/2'
It has been fixed in CURL 8.12.0 by explicitly stripping TE header
from HTTP/2 requests
Relates-To: NLAM-55
> Disable transfer encoding for old CURL versions
